// Code generated by ent, DO NOT EDIT.

package socialtasklog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the socialtasklog type in the database.
	Label = "social_task_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSocialAccountID holds the string denoting the social_account_id field in the database.
	FieldSocialAccountID = "social_account_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldTemplateSnapshot holds the string denoting the template_snapshot field in the database.
	FieldTemplateSnapshot = "template_snapshot"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldResultMessage holds the string denoting the result_message field in the database.
	FieldResultMessage = "result_message"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldChargedAmount holds the string denoting the charged_amount field in the database.
	FieldChargedAmount = "charged_amount"
	// FieldChargeStatus holds the string denoting the charge_status field in the database.
	FieldChargeStatus = "charge_status"
	// FieldChargeSource holds the string denoting the charge_source field in the database.
	FieldChargeSource = "charge_source"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldProxySnapshot holds the string denoting the proxy_snapshot field in the database.
	FieldProxySnapshot = "proxy_snapshot"
	// FieldBillingRequestID holds the string denoting the billing_request_id field in the database.
	FieldBillingRequestID = "billing_request_id"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldExecutedAt holds the string denoting the executed_at field in the database.
	FieldExecutedAt = "executed_at"
	// EdgeSocialAccount holds the string denoting the social_account edge name in mutations.
	EdgeSocialAccount = "social_account"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the socialtasklog in the database.
	Table = "social_task_logs"
	// SocialAccountTable is the table that holds the social_account relation/edge.
	SocialAccountTable = "social_task_logs"
	// SocialAccountInverseTable is the table name for the SocialAccount entity.
	// It exists in this package in order to avoid circular dependency with the "socialaccount" package.
	SocialAccountInverseTable = "social_accounts"
	// SocialAccountColumn is the table column denoting the social_account relation/edge.
	SocialAccountColumn = "social_account_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "social_task_logs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for socialtasklog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSocialAccountID,
	FieldUserID,
	FieldAction,
	FieldTarget,
	FieldContent,
	FieldPayload,
	FieldTemplateSnapshot,
	FieldStatus,
	FieldResultMessage,
	FieldPrice,
	FieldChargedAmount,
	FieldChargeStatus,
	FieldChargeSource,
	FieldProxyID,
	FieldProxySnapshot,
	FieldBillingRequestID,
	FieldIdempotencyKey,
	FieldExecutedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultChargedAmount holds the default value on creation for the "charged_amount" field.
	DefaultChargedAmount float64
	// DefaultChargeStatus holds the default value on creation for the "charge_status" field.
	DefaultChargeStatus string
	// ChargeStatusValidator is a validator for the "charge_status" field. It is called by the builders before save.
	ChargeStatusValidator func(string) error
	// ChargeSourceValidator is a validator for the "charge_source" field. It is called by the builders before save.
	ChargeSourceValidator func(string) error
	// BillingRequestIDValidator is a validator for the "billing_request_id" field. It is called by the builders before save.
	BillingRequestIDValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
)

// OrderOption defines the ordering options for the SocialTaskLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySocialAccountID orders the results by the social_account_id field.
func BySocialAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSocialAccountID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByResultMessage orders the results by the result_message field.
func ByResultMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultMessage, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByChargedAmount orders the results by the charged_amount field.
func ByChargedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargedAmount, opts...).ToFunc()
}

// ByChargeStatus orders the results by the charge_status field.
func ByChargeStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargeStatus, opts...).ToFunc()
}

// ByChargeSource orders the results by the charge_source field.
func ByChargeSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargeSource, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByProxySnapshot orders the results by the proxy_snapshot field.
func ByProxySnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxySnapshot, opts...).ToFunc()
}

// ByBillingRequestID orders the results by the billing_request_id field.
func ByBillingRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingRequestID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByExecutedAt orders the results by the executed_at field.
func ByExecutedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutedAt, opts...).ToFunc()
}

// BySocialAccountField orders the results by social_account field.
func BySocialAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSocialAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newSocialAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SocialAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SocialAccountTable, SocialAccountColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
