// Code generated by ent, DO NOT EDIT.

package socialaccount

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the socialaccount type in the database.
	Label = "social_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPlatformKey holds the string denoting the platform_key field in the database.
	FieldPlatformKey = "platform_key"
	// FieldNameKey holds the string denoting the name_key field in the database.
	FieldNameKey = "name_key"
	// FieldIdentityKind holds the string denoting the identity_kind field in the database.
	FieldIdentityKind = "identity_kind"
	// FieldIdentityKey holds the string denoting the identity_key field in the database.
	FieldIdentityKey = "identity_key"
	// FieldPlatformUserID holds the string denoting the platform_user_id field in the database.
	FieldPlatformUserID = "platform_user_id"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldEmailPassword holds the string denoting the email_password field in the database.
	FieldEmailPassword = "email_password"
	// FieldTwoFactor holds the string denoting the two_factor field in the database.
	FieldTwoFactor = "two_factor"
	// FieldBackupCode holds the string denoting the backup_code field in the database.
	FieldBackupCode = "backup_code"
	// FieldEmailClientID holds the string denoting the email_client_id field in the database.
	FieldEmailClientID = "email_client_id"
	// FieldEmailToken holds the string denoting the email_token field in the database.
	FieldEmailToken = "email_token"
	// FieldRegistrationIP holds the string denoting the registration_ip field in the database.
	FieldRegistrationIP = "registration_ip"
	// FieldAuthCookie holds the string denoting the auth_cookie field in the database.
	FieldAuthCookie = "auth_cookie"
	// FieldExecutionAuth holds the string denoting the execution_auth field in the database.
	FieldExecutionAuth = "execution_auth"
	// FieldAccountStatus holds the string denoting the account_status field in the database.
	FieldAccountStatus = "account_status"
	// FieldTaskStatus holds the string denoting the task_status field in the database.
	FieldTaskStatus = "task_status"
	// FieldTaskMessage holds the string denoting the task_message field in the database.
	FieldTaskMessage = "task_message"
	// FieldDefaultProxySnapshot holds the string denoting the default_proxy_snapshot field in the database.
	FieldDefaultProxySnapshot = "default_proxy_snapshot"
	// FieldAssignedUserID holds the string denoting the assigned_user_id field in the database.
	FieldAssignedUserID = "assigned_user_id"
	// FieldUserWorkbenchDeletedAt holds the string denoting the user_workbench_deleted_at field in the database.
	FieldUserWorkbenchDeletedAt = "user_workbench_deleted_at"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeAssignedUser holds the string denoting the assigned_user edge name in mutations.
	EdgeAssignedUser = "assigned_user"
	// EdgeTaskLogs holds the string denoting the task_logs edge name in mutations.
	EdgeTaskLogs = "task_logs"
	// Table holds the table name of the socialaccount in the database.
	Table = "social_accounts"
	// AssignedUserTable is the table that holds the assigned_user relation/edge.
	AssignedUserTable = "social_accounts"
	// AssignedUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AssignedUserInverseTable = "users"
	// AssignedUserColumn is the table column denoting the assigned_user relation/edge.
	AssignedUserColumn = "assigned_user_id"
	// TaskLogsTable is the table that holds the task_logs relation/edge.
	TaskLogsTable = "social_task_logs"
	// TaskLogsInverseTable is the table name for the SocialTaskLog entity.
	// It exists in this package in order to avoid circular dependency with the "socialtasklog" package.
	TaskLogsInverseTable = "social_task_logs"
	// TaskLogsColumn is the table column denoting the task_logs relation/edge.
	TaskLogsColumn = "social_account_id"
)

// Columns holds all SQL columns for socialaccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldPlatform,
	FieldPlatformKey,
	FieldNameKey,
	FieldIdentityKind,
	FieldIdentityKey,
	FieldPlatformUserID,
	FieldPassword,
	FieldPhone,
	FieldEmail,
	FieldEmailPassword,
	FieldTwoFactor,
	FieldBackupCode,
	FieldEmailClientID,
	FieldEmailToken,
	FieldRegistrationIP,
	FieldAuthCookie,
	FieldExecutionAuth,
	FieldAccountStatus,
	FieldTaskStatus,
	FieldTaskMessage,
	FieldDefaultProxySnapshot,
	FieldAssignedUserID,
	FieldUserWorkbenchDeletedAt,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/socialops/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// PlatformKeyValidator is a validator for the "platform_key" field. It is called by the builders before save.
	PlatformKeyValidator func(string) error
	// NameKeyValidator is a validator for the "name_key" field. It is called by the builders before save.
	NameKeyValidator func(string) error
	// DefaultIdentityKind holds the default value on creation for the "identity_kind" field.
	DefaultIdentityKind string
	// IdentityKindValidator is a validator for the "identity_kind" field. It is called by the builders before save.
	IdentityKindValidator func(string) error
	// IdentityKeyValidator is a validator for the "identity_key" field. It is called by the builders before save.
	IdentityKeyValidator func(string) error
	// PlatformUserIDValidator is a validator for the "platform_user_id" field. It is called by the builders before save.
	PlatformUserIDValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// EmailPasswordValidator is a validator for the "email_password" field. It is called by the builders before save.
	EmailPasswordValidator func(string) error
	// TwoFactorValidator is a validator for the "two_factor" field. It is called by the builders before save.
	TwoFactorValidator func(string) error
	// BackupCodeValidator is a validator for the "backup_code" field. It is called by the builders before save.
	BackupCodeValidator func(string) error
	// EmailClientIDValidator is a validator for the "email_client_id" field. It is called by the builders before save.
	EmailClientIDValidator func(string) error
	// RegistrationIPValidator is a validator for the "registration_ip" field. It is called by the builders before save.
	RegistrationIPValidator func(string) error
	// DefaultAccountStatus holds the default value on creation for the "account_status" field.
	DefaultAccountStatus string
	// AccountStatusValidator is a validator for the "account_status" field. It is called by the builders before save.
	AccountStatusValidator func(string) error
	// DefaultTaskStatus holds the default value on creation for the "task_status" field.
	DefaultTaskStatus string
	// TaskStatusValidator is a validator for the "task_status" field. It is called by the builders before save.
	TaskStatusValidator func(string) error
)

// OrderOption defines the ordering options for the SocialAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPlatformKey orders the results by the platform_key field.
func ByPlatformKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformKey, opts...).ToFunc()
}

// ByNameKey orders the results by the name_key field.
func ByNameKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameKey, opts...).ToFunc()
}

// ByIdentityKind orders the results by the identity_kind field.
func ByIdentityKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentityKind, opts...).ToFunc()
}

// ByIdentityKey orders the results by the identity_key field.
func ByIdentityKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentityKey, opts...).ToFunc()
}

// ByPlatformUserID orders the results by the platform_user_id field.
func ByPlatformUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformUserID, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByEmailPassword orders the results by the email_password field.
func ByEmailPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailPassword, opts...).ToFunc()
}

// ByTwoFactor orders the results by the two_factor field.
func ByTwoFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTwoFactor, opts...).ToFunc()
}

// ByBackupCode orders the results by the backup_code field.
func ByBackupCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupCode, opts...).ToFunc()
}

// ByEmailClientID orders the results by the email_client_id field.
func ByEmailClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailClientID, opts...).ToFunc()
}

// ByEmailToken orders the results by the email_token field.
func ByEmailToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmailToken, opts...).ToFunc()
}

// ByRegistrationIP orders the results by the registration_ip field.
func ByRegistrationIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegistrationIP, opts...).ToFunc()
}

// ByAuthCookie orders the results by the auth_cookie field.
func ByAuthCookie(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthCookie, opts...).ToFunc()
}

// ByExecutionAuth orders the results by the execution_auth field.
func ByExecutionAuth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionAuth, opts...).ToFunc()
}

// ByAccountStatus orders the results by the account_status field.
func ByAccountStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountStatus, opts...).ToFunc()
}

// ByTaskStatus orders the results by the task_status field.
func ByTaskStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskStatus, opts...).ToFunc()
}

// ByTaskMessage orders the results by the task_message field.
func ByTaskMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskMessage, opts...).ToFunc()
}

// ByDefaultProxySnapshot orders the results by the default_proxy_snapshot field.
func ByDefaultProxySnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultProxySnapshot, opts...).ToFunc()
}

// ByAssignedUserID orders the results by the assigned_user_id field.
func ByAssignedUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedUserID, opts...).ToFunc()
}

// ByUserWorkbenchDeletedAt orders the results by the user_workbench_deleted_at field.
func ByUserWorkbenchDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserWorkbenchDeletedAt, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByAssignedUserField orders the results by assigned_user field.
func ByAssignedUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignedUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByTaskLogsCount orders the results by task_logs count.
func ByTaskLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaskLogsStep(), opts...)
	}
}

// ByTaskLogs orders the results by task_logs terms.
func ByTaskLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAssignedUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignedUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssignedUserTable, AssignedUserColumn),
	)
}
func newTaskLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TaskLogsTable, TaskLogsColumn),
	)
}
