// Code generated by ent, DO NOT EDIT.

package socialaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/socialops/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldPlatform, v))
}

// PlatformKey applies equality check predicate on the "platform_key" field. It's identical to PlatformKeyEQ.
func PlatformKey(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldPlatformKey, v))
}

// NameKey applies equality check predicate on the "name_key" field. It's identical to NameKeyEQ.
func NameKey(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldNameKey, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldAccountID, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldPassword, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldPhone, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldEmail, v))
}

// EmailPassword applies equality check predicate on the "email_password" field. It's identical to EmailPasswordEQ.
func EmailPassword(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldEmailPassword, v))
}

// AccountStatus applies equality check predicate on the "account_status" field. It's identical to AccountStatusEQ.
func AccountStatus(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldAccountStatus, v))
}

// TaskStatus applies equality check predicate on the "task_status" field. It's identical to TaskStatusEQ.
func TaskStatus(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldTaskStatus, v))
}

// TaskMessage applies equality check predicate on the "task_message" field. It's identical to TaskMessageEQ.
func TaskMessage(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldTaskMessage, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldSource, v))
}

// BoundIP applies equality check predicate on the "bound_ip" field. It's identical to BoundIPEQ.
func BoundIP(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldBoundIP, v))
}

// AssignedUserID applies equality check predicate on the "assigned_user_id" field. It's identical to AssignedUserIDEQ.
func AssignedUserID(v int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldAssignedUserID, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldPlatform, v))
}

// PlatformKeyEQ applies the EQ predicate on the "platform_key" field.
func PlatformKeyEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldPlatformKey, v))
}

// PlatformKeyNEQ applies the NEQ predicate on the "platform_key" field.
func PlatformKeyNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldPlatformKey, v))
}

// PlatformKeyIn applies the In predicate on the "platform_key" field.
func PlatformKeyIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldPlatformKey, vs...))
}

// PlatformKeyNotIn applies the NotIn predicate on the "platform_key" field.
func PlatformKeyNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldPlatformKey, vs...))
}

// PlatformKeyGT applies the GT predicate on the "platform_key" field.
func PlatformKeyGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldPlatformKey, v))
}

// PlatformKeyGTE applies the GTE predicate on the "platform_key" field.
func PlatformKeyGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldPlatformKey, v))
}

// PlatformKeyLT applies the LT predicate on the "platform_key" field.
func PlatformKeyLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldPlatformKey, v))
}

// PlatformKeyLTE applies the LTE predicate on the "platform_key" field.
func PlatformKeyLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldPlatformKey, v))
}

// PlatformKeyContains applies the Contains predicate on the "platform_key" field.
func PlatformKeyContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldPlatformKey, v))
}

// PlatformKeyHasPrefix applies the HasPrefix predicate on the "platform_key" field.
func PlatformKeyHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldPlatformKey, v))
}

// PlatformKeyHasSuffix applies the HasSuffix predicate on the "platform_key" field.
func PlatformKeyHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldPlatformKey, v))
}

// PlatformKeyEqualFold applies the EqualFold predicate on the "platform_key" field.
func PlatformKeyEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldPlatformKey, v))
}

// PlatformKeyContainsFold applies the ContainsFold predicate on the "platform_key" field.
func PlatformKeyContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldPlatformKey, v))
}

// NameKeyEQ applies the EQ predicate on the "name_key" field.
func NameKeyEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldNameKey, v))
}

// NameKeyNEQ applies the NEQ predicate on the "name_key" field.
func NameKeyNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldNameKey, v))
}

// NameKeyIn applies the In predicate on the "name_key" field.
func NameKeyIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldNameKey, vs...))
}

// NameKeyNotIn applies the NotIn predicate on the "name_key" field.
func NameKeyNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldNameKey, vs...))
}

// NameKeyGT applies the GT predicate on the "name_key" field.
func NameKeyGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldNameKey, v))
}

// NameKeyGTE applies the GTE predicate on the "name_key" field.
func NameKeyGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldNameKey, v))
}

// NameKeyLT applies the LT predicate on the "name_key" field.
func NameKeyLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldNameKey, v))
}

// NameKeyLTE applies the LTE predicate on the "name_key" field.
func NameKeyLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldNameKey, v))
}

// NameKeyContains applies the Contains predicate on the "name_key" field.
func NameKeyContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldNameKey, v))
}

// NameKeyHasPrefix applies the HasPrefix predicate on the "name_key" field.
func NameKeyHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldNameKey, v))
}

// NameKeyHasSuffix applies the HasSuffix predicate on the "name_key" field.
func NameKeyHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldNameKey, v))
}

// NameKeyEqualFold applies the EqualFold predicate on the "name_key" field.
func NameKeyEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldNameKey, v))
}

// NameKeyContainsFold applies the ContainsFold predicate on the "name_key" field.
func NameKeyContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldNameKey, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldAccountID))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldAccountID, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldPassword, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldPhone, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldEmail, v))
}

// EmailPasswordEQ applies the EQ predicate on the "email_password" field.
func EmailPasswordEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldEmailPassword, v))
}

// EmailPasswordNEQ applies the NEQ predicate on the "email_password" field.
func EmailPasswordNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldEmailPassword, v))
}

// EmailPasswordIn applies the In predicate on the "email_password" field.
func EmailPasswordIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldEmailPassword, vs...))
}

// EmailPasswordNotIn applies the NotIn predicate on the "email_password" field.
func EmailPasswordNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldEmailPassword, vs...))
}

// EmailPasswordGT applies the GT predicate on the "email_password" field.
func EmailPasswordGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldEmailPassword, v))
}

// EmailPasswordGTE applies the GTE predicate on the "email_password" field.
func EmailPasswordGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldEmailPassword, v))
}

// EmailPasswordLT applies the LT predicate on the "email_password" field.
func EmailPasswordLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldEmailPassword, v))
}

// EmailPasswordLTE applies the LTE predicate on the "email_password" field.
func EmailPasswordLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldEmailPassword, v))
}

// EmailPasswordContains applies the Contains predicate on the "email_password" field.
func EmailPasswordContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldEmailPassword, v))
}

// EmailPasswordHasPrefix applies the HasPrefix predicate on the "email_password" field.
func EmailPasswordHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldEmailPassword, v))
}

// EmailPasswordHasSuffix applies the HasSuffix predicate on the "email_password" field.
func EmailPasswordHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldEmailPassword, v))
}

// EmailPasswordIsNil applies the IsNil predicate on the "email_password" field.
func EmailPasswordIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldEmailPassword))
}

// EmailPasswordNotNil applies the NotNil predicate on the "email_password" field.
func EmailPasswordNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldEmailPassword))
}

// EmailPasswordEqualFold applies the EqualFold predicate on the "email_password" field.
func EmailPasswordEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldEmailPassword, v))
}

// EmailPasswordContainsFold applies the ContainsFold predicate on the "email_password" field.
func EmailPasswordContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldEmailPassword, v))
}

// AccountStatusEQ applies the EQ predicate on the "account_status" field.
func AccountStatusEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldAccountStatus, v))
}

// AccountStatusNEQ applies the NEQ predicate on the "account_status" field.
func AccountStatusNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldAccountStatus, v))
}

// AccountStatusIn applies the In predicate on the "account_status" field.
func AccountStatusIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldAccountStatus, vs...))
}

// AccountStatusNotIn applies the NotIn predicate on the "account_status" field.
func AccountStatusNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldAccountStatus, vs...))
}

// AccountStatusGT applies the GT predicate on the "account_status" field.
func AccountStatusGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldAccountStatus, v))
}

// AccountStatusGTE applies the GTE predicate on the "account_status" field.
func AccountStatusGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldAccountStatus, v))
}

// AccountStatusLT applies the LT predicate on the "account_status" field.
func AccountStatusLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldAccountStatus, v))
}

// AccountStatusLTE applies the LTE predicate on the "account_status" field.
func AccountStatusLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldAccountStatus, v))
}

// AccountStatusContains applies the Contains predicate on the "account_status" field.
func AccountStatusContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldAccountStatus, v))
}

// AccountStatusHasPrefix applies the HasPrefix predicate on the "account_status" field.
func AccountStatusHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldAccountStatus, v))
}

// AccountStatusHasSuffix applies the HasSuffix predicate on the "account_status" field.
func AccountStatusHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldAccountStatus, v))
}

// AccountStatusEqualFold applies the EqualFold predicate on the "account_status" field.
func AccountStatusEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldAccountStatus, v))
}

// AccountStatusContainsFold applies the ContainsFold predicate on the "account_status" field.
func AccountStatusContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldAccountStatus, v))
}

// TaskStatusEQ applies the EQ predicate on the "task_status" field.
func TaskStatusEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldTaskStatus, v))
}

// TaskStatusNEQ applies the NEQ predicate on the "task_status" field.
func TaskStatusNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldTaskStatus, v))
}

// TaskStatusIn applies the In predicate on the "task_status" field.
func TaskStatusIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldTaskStatus, vs...))
}

// TaskStatusNotIn applies the NotIn predicate on the "task_status" field.
func TaskStatusNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldTaskStatus, vs...))
}

// TaskStatusGT applies the GT predicate on the "task_status" field.
func TaskStatusGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldTaskStatus, v))
}

// TaskStatusGTE applies the GTE predicate on the "task_status" field.
func TaskStatusGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldTaskStatus, v))
}

// TaskStatusLT applies the LT predicate on the "task_status" field.
func TaskStatusLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldTaskStatus, v))
}

// TaskStatusLTE applies the LTE predicate on the "task_status" field.
func TaskStatusLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldTaskStatus, v))
}

// TaskStatusContains applies the Contains predicate on the "task_status" field.
func TaskStatusContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldTaskStatus, v))
}

// TaskStatusHasPrefix applies the HasPrefix predicate on the "task_status" field.
func TaskStatusHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldTaskStatus, v))
}

// TaskStatusHasSuffix applies the HasSuffix predicate on the "task_status" field.
func TaskStatusHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldTaskStatus, v))
}

// TaskStatusEqualFold applies the EqualFold predicate on the "task_status" field.
func TaskStatusEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldTaskStatus, v))
}

// TaskStatusContainsFold applies the ContainsFold predicate on the "task_status" field.
func TaskStatusContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldTaskStatus, v))
}

// TaskMessageEQ applies the EQ predicate on the "task_message" field.
func TaskMessageEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldTaskMessage, v))
}

// TaskMessageNEQ applies the NEQ predicate on the "task_message" field.
func TaskMessageNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldTaskMessage, v))
}

// TaskMessageIn applies the In predicate on the "task_message" field.
func TaskMessageIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldTaskMessage, vs...))
}

// TaskMessageNotIn applies the NotIn predicate on the "task_message" field.
func TaskMessageNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldTaskMessage, vs...))
}

// TaskMessageGT applies the GT predicate on the "task_message" field.
func TaskMessageGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldTaskMessage, v))
}

// TaskMessageGTE applies the GTE predicate on the "task_message" field.
func TaskMessageGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldTaskMessage, v))
}

// TaskMessageLT applies the LT predicate on the "task_message" field.
func TaskMessageLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldTaskMessage, v))
}

// TaskMessageLTE applies the LTE predicate on the "task_message" field.
func TaskMessageLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldTaskMessage, v))
}

// TaskMessageContains applies the Contains predicate on the "task_message" field.
func TaskMessageContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldTaskMessage, v))
}

// TaskMessageHasPrefix applies the HasPrefix predicate on the "task_message" field.
func TaskMessageHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldTaskMessage, v))
}

// TaskMessageHasSuffix applies the HasSuffix predicate on the "task_message" field.
func TaskMessageHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldTaskMessage, v))
}

// TaskMessageIsNil applies the IsNil predicate on the "task_message" field.
func TaskMessageIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldTaskMessage))
}

// TaskMessageNotNil applies the NotNil predicate on the "task_message" field.
func TaskMessageNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldTaskMessage))
}

// TaskMessageEqualFold applies the EqualFold predicate on the "task_message" field.
func TaskMessageEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldTaskMessage, v))
}

// TaskMessageContainsFold applies the ContainsFold predicate on the "task_message" field.
func TaskMessageContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldTaskMessage, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldSource, v))
}

// BoundIPEQ applies the EQ predicate on the "bound_ip" field.
func BoundIPEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldBoundIP, v))
}

// BoundIPNEQ applies the NEQ predicate on the "bound_ip" field.
func BoundIPNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldBoundIP, v))
}

// BoundIPIn applies the In predicate on the "bound_ip" field.
func BoundIPIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldBoundIP, vs...))
}

// BoundIPNotIn applies the NotIn predicate on the "bound_ip" field.
func BoundIPNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldBoundIP, vs...))
}

// BoundIPGT applies the GT predicate on the "bound_ip" field.
func BoundIPGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldBoundIP, v))
}

// BoundIPGTE applies the GTE predicate on the "bound_ip" field.
func BoundIPGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldBoundIP, v))
}

// BoundIPLT applies the LT predicate on the "bound_ip" field.
func BoundIPLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldBoundIP, v))
}

// BoundIPLTE applies the LTE predicate on the "bound_ip" field.
func BoundIPLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldBoundIP, v))
}

// BoundIPContains applies the Contains predicate on the "bound_ip" field.
func BoundIPContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldBoundIP, v))
}

// BoundIPHasPrefix applies the HasPrefix predicate on the "bound_ip" field.
func BoundIPHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldBoundIP, v))
}

// BoundIPHasSuffix applies the HasSuffix predicate on the "bound_ip" field.
func BoundIPHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldBoundIP, v))
}

// BoundIPIsNil applies the IsNil predicate on the "bound_ip" field.
func BoundIPIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldBoundIP))
}

// BoundIPNotNil applies the NotNil predicate on the "bound_ip" field.
func BoundIPNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldBoundIP))
}

// BoundIPEqualFold applies the EqualFold predicate on the "bound_ip" field.
func BoundIPEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldBoundIP, v))
}

// BoundIPContainsFold applies the ContainsFold predicate on the "bound_ip" field.
func BoundIPContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldBoundIP, v))
}

// AssignedUserIDEQ applies the EQ predicate on the "assigned_user_id" field.
func AssignedUserIDEQ(v int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldAssignedUserID, v))
}

// AssignedUserIDNEQ applies the NEQ predicate on the "assigned_user_id" field.
func AssignedUserIDNEQ(v int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldAssignedUserID, v))
}

// AssignedUserIDIn applies the In predicate on the "assigned_user_id" field.
func AssignedUserIDIn(vs ...int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldAssignedUserID, vs...))
}

// AssignedUserIDNotIn applies the NotIn predicate on the "assigned_user_id" field.
func AssignedUserIDNotIn(vs ...int64) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldAssignedUserID, vs...))
}

// AssignedUserIDIsNil applies the IsNil predicate on the "assigned_user_id" field.
func AssignedUserIDIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldAssignedUserID))
}

// AssignedUserIDNotNil applies the NotNil predicate on the "assigned_user_id" field.
func AssignedUserIDNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldAssignedUserID))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SocialAccount {
	return predicate.SocialAccount(sql.FieldContainsFold(FieldRemark, v))
}

// HasAssignedUser applies the HasEdge predicate on the "assigned_user" edge.
func HasAssignedUser() predicate.SocialAccount {
	return predicate.SocialAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignedUserTable, AssignedUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedUserWith applies the HasEdge predicate on the "assigned_user" edge with a given conditions (other predicates).
func HasAssignedUserWith(preds ...predicate.User) predicate.SocialAccount {
	return predicate.SocialAccount(func(s *sql.Selector) {
		step := newAssignedUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTaskLogs applies the HasEdge predicate on the "task_logs" edge.
func HasTaskLogs() predicate.SocialAccount {
	return predicate.SocialAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TaskLogsTable, TaskLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskLogsWith applies the HasEdge predicate on the "task_logs" edge with a given conditions (other predicates).
func HasTaskLogsWith(preds ...predicate.SocialTaskLog) predicate.SocialAccount {
	return predicate.SocialAccount(func(s *sql.Selector) {
		step := newTaskLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SocialAccount) predicate.SocialAccount {
	return predicate.SocialAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SocialAccount) predicate.SocialAccount {
	return predicate.SocialAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SocialAccount) predicate.SocialAccount {
	return predicate.SocialAccount(sql.NotPredicates(p))
}
