// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/socialops/ent/globalproxy"
)

// GlobalProxyCreate is the builder for creating a GlobalProxy entity.
type GlobalProxyCreate struct {
	config
	mutation *GlobalProxyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GlobalProxyCreate) SetCreatedAt(v time.Time) *GlobalProxyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableCreatedAt(v *time.Time) *GlobalProxyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GlobalProxyCreate) SetUpdatedAt(v time.Time) *GlobalProxyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableUpdatedAt(v *time.Time) *GlobalProxyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *GlobalProxyCreate) SetDeletedAt(v time.Time) *GlobalProxyCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableDeletedAt(v *time.Time) *GlobalProxyCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *GlobalProxyCreate) SetName(v string) *GlobalProxyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIPType sets the "ip_type" field.
func (_c *GlobalProxyCreate) SetIPType(v string) *GlobalProxyCreate {
	_c.mutation.SetIPType(v)
	return _c
}

// SetNillableIPType sets the "ip_type" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableIPType(v *string) *GlobalProxyCreate {
	if v != nil {
		_c.SetIPType(*v)
	}
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *GlobalProxyCreate) SetEndpoint(v string) *GlobalProxyCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableEndpoint(v *string) *GlobalProxyCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *GlobalProxyCreate) SetStatus(v string) *GlobalProxyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableStatus(v *string) *GlobalProxyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *GlobalProxyCreate) SetLatencyMs(v int) *GlobalProxyCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableLatencyMs(v *int) *GlobalProxyCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetLastCheckAt sets the "last_check_at" field.
func (_c *GlobalProxyCreate) SetLastCheckAt(v time.Time) *GlobalProxyCreate {
	_c.mutation.SetLastCheckAt(v)
	return _c
}

// SetNillableLastCheckAt sets the "last_check_at" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableLastCheckAt(v *time.Time) *GlobalProxyCreate {
	if v != nil {
		_c.SetLastCheckAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *GlobalProxyCreate) SetLastUsedAt(v time.Time) *GlobalProxyCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableLastUsedAt(v *time.Time) *GlobalProxyCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *GlobalProxyCreate) SetRemark(v string) *GlobalProxyCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *GlobalProxyCreate) SetNillableRemark(v *string) *GlobalProxyCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// Mutation returns the GlobalProxyMutation object of the builder.
func (_c *GlobalProxyCreate) Mutation() *GlobalProxyMutation {
	return _c.mutation
}

// Save creates the GlobalProxy in the database.
func (_c *GlobalProxyCreate) Save(ctx context.Context) (*GlobalProxy, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GlobalProxyCreate) SaveX(ctx context.Context) *GlobalProxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GlobalProxyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GlobalProxyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GlobalProxyCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if globalproxy.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized globalproxy.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := globalproxy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if globalproxy.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized globalproxy.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := globalproxy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IPType(); !ok {
		v := globalproxy.DefaultIPType
		_c.mutation.SetIPType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := globalproxy.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *GlobalProxyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GlobalProxy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GlobalProxy.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "GlobalProxy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := globalproxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GlobalProxy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IPType(); !ok {
		return &ValidationError{Name: "ip_type", err: errors.New(`ent: missing required field "GlobalProxy.ip_type"`)}
	}
	if v, ok := _c.mutation.IPType(); ok {
		if err := globalproxy.IPTypeValidator(v); err != nil {
			return &ValidationError{Name: "ip_type", err: fmt.Errorf(`ent: validator failed for field "GlobalProxy.ip_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := globalproxy.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "GlobalProxy.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GlobalProxy.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := globalproxy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GlobalProxy.status": %w`, err)}
		}
	}
	return nil
}

func (_c *GlobalProxyCreate) sqlSave(ctx context.Context) (*GlobalProxy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GlobalProxyCreate) createSpec() (*GlobalProxy, *sqlgraph.CreateSpec) {
	var (
		_node = &GlobalProxy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(globalproxy.Table, sqlgraph.NewFieldSpec(globalproxy.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(globalproxy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(globalproxy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(globalproxy.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(globalproxy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IPType(); ok {
		_spec.SetField(globalproxy.FieldIPType, field.TypeString, value)
		_node.IPType = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(globalproxy.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(globalproxy.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(globalproxy.FieldLatencyMs, field.TypeInt, value)
		_node.LatencyMs = &value
	}
	if value, ok := _c.mutation.LastCheckAt(); ok {
		_spec.SetField(globalproxy.FieldLastCheckAt, field.TypeTime, value)
		_node.LastCheckAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(globalproxy.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(globalproxy.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GlobalProxy.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GlobalProxyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GlobalProxyCreate) OnConflict(opts ...sql.ConflictOption) *GlobalProxyUpsertOne {
	_c.conflict = opts
	return &GlobalProxyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GlobalProxy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GlobalProxyCreate) OnConflictColumns(columns ...string) *GlobalProxyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GlobalProxyUpsertOne{
		create: _c,
	}
}

type (
	// GlobalProxyUpsertOne is the builder for "upsert"-ing
	//  one GlobalProxy node.
	GlobalProxyUpsertOne struct {
		create *GlobalProxyCreate
	}

	// GlobalProxyUpsert is the "OnConflict" setter.
	GlobalProxyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GlobalProxyUpsert) SetUpdatedAt(v time.Time) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateUpdatedAt() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GlobalProxyUpsert) SetDeletedAt(v time.Time) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateDeletedAt() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GlobalProxyUpsert) ClearDeletedAt() *GlobalProxyUpsert {
	u.SetNull(globalproxy.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *GlobalProxyUpsert) SetName(v string) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateName() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldName)
	return u
}

// SetIPType sets the "ip_type" field.
func (u *GlobalProxyUpsert) SetIPType(v string) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldIPType, v)
	return u
}

// UpdateIPType sets the "ip_type" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateIPType() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldIPType)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *GlobalProxyUpsert) SetEndpoint(v string) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateEndpoint() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldEndpoint)
	return u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *GlobalProxyUpsert) ClearEndpoint() *GlobalProxyUpsert {
	u.SetNull(globalproxy.FieldEndpoint)
	return u
}

// SetStatus sets the "status" field.
func (u *GlobalProxyUpsert) SetStatus(v string) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateStatus() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldStatus)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GlobalProxyUpsert) SetLatencyMs(v int) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateLatencyMs() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GlobalProxyUpsert) AddLatencyMs(v int) *GlobalProxyUpsert {
	u.Add(globalproxy.FieldLatencyMs, v)
	return u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GlobalProxyUpsert) ClearLatencyMs() *GlobalProxyUpsert {
	u.SetNull(globalproxy.FieldLatencyMs)
	return u
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *GlobalProxyUpsert) SetLastCheckAt(v time.Time) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldLastCheckAt, v)
	return u
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateLastCheckAt() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldLastCheckAt)
	return u
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *GlobalProxyUpsert) ClearLastCheckAt() *GlobalProxyUpsert {
	u.SetNull(globalproxy.FieldLastCheckAt)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *GlobalProxyUpsert) SetLastUsedAt(v time.Time) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateLastUsedAt() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *GlobalProxyUpsert) ClearLastUsedAt() *GlobalProxyUpsert {
	u.SetNull(globalproxy.FieldLastUsedAt)
	return u
}

// SetRemark sets the "remark" field.
func (u *GlobalProxyUpsert) SetRemark(v string) *GlobalProxyUpsert {
	u.Set(globalproxy.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *GlobalProxyUpsert) UpdateRemark() *GlobalProxyUpsert {
	u.SetExcluded(globalproxy.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *GlobalProxyUpsert) ClearRemark() *GlobalProxyUpsert {
	u.SetNull(globalproxy.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GlobalProxy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GlobalProxyUpsertOne) UpdateNewValues() *GlobalProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(globalproxy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GlobalProxy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GlobalProxyUpsertOne) Ignore() *GlobalProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GlobalProxyUpsertOne) DoNothing() *GlobalProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GlobalProxyCreate.OnConflict
// documentation for more info.
func (u *GlobalProxyUpsertOne) Update(set func(*GlobalProxyUpsert)) *GlobalProxyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GlobalProxyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GlobalProxyUpsertOne) SetUpdatedAt(v time.Time) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateUpdatedAt() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GlobalProxyUpsertOne) SetDeletedAt(v time.Time) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateDeletedAt() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GlobalProxyUpsertOne) ClearDeletedAt() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *GlobalProxyUpsertOne) SetName(v string) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateName() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateName()
	})
}

// SetIPType sets the "ip_type" field.
func (u *GlobalProxyUpsertOne) SetIPType(v string) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetIPType(v)
	})
}

// UpdateIPType sets the "ip_type" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateIPType() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateIPType()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *GlobalProxyUpsertOne) SetEndpoint(v string) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateEndpoint() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateEndpoint()
	})
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *GlobalProxyUpsertOne) ClearEndpoint() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearEndpoint()
	})
}

// SetStatus sets the "status" field.
func (u *GlobalProxyUpsertOne) SetStatus(v string) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateStatus() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateStatus()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GlobalProxyUpsertOne) SetLatencyMs(v int) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GlobalProxyUpsertOne) AddLatencyMs(v int) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateLatencyMs() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GlobalProxyUpsertOne) ClearLatencyMs() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearLatencyMs()
	})
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *GlobalProxyUpsertOne) SetLastCheckAt(v time.Time) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetLastCheckAt(v)
	})
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateLastCheckAt() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateLastCheckAt()
	})
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *GlobalProxyUpsertOne) ClearLastCheckAt() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearLastCheckAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *GlobalProxyUpsertOne) SetLastUsedAt(v time.Time) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateLastUsedAt() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *GlobalProxyUpsertOne) ClearLastUsedAt() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRemark sets the "remark" field.
func (u *GlobalProxyUpsertOne) SetRemark(v string) *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *GlobalProxyUpsertOne) UpdateRemark() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *GlobalProxyUpsertOne) ClearRemark() *GlobalProxyUpsertOne {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *GlobalProxyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GlobalProxyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GlobalProxyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GlobalProxyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GlobalProxyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GlobalProxyCreateBulk is the builder for creating many GlobalProxy entities in bulk.
type GlobalProxyCreateBulk struct {
	config
	err      error
	builders []*GlobalProxyCreate
	conflict []sql.ConflictOption
}

// Save creates the GlobalProxy entities in the database.
func (_c *GlobalProxyCreateBulk) Save(ctx context.Context) ([]*GlobalProxy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GlobalProxy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GlobalProxyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GlobalProxyCreateBulk) SaveX(ctx context.Context) []*GlobalProxy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GlobalProxyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GlobalProxyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GlobalProxy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GlobalProxyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GlobalProxyCreateBulk) OnConflict(opts ...sql.ConflictOption) *GlobalProxyUpsertBulk {
	_c.conflict = opts
	return &GlobalProxyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GlobalProxy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GlobalProxyCreateBulk) OnConflictColumns(columns ...string) *GlobalProxyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GlobalProxyUpsertBulk{
		create: _c,
	}
}

// GlobalProxyUpsertBulk is the builder for "upsert"-ing
// a bulk of GlobalProxy nodes.
type GlobalProxyUpsertBulk struct {
	create *GlobalProxyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GlobalProxy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GlobalProxyUpsertBulk) UpdateNewValues() *GlobalProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(globalproxy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GlobalProxy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GlobalProxyUpsertBulk) Ignore() *GlobalProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GlobalProxyUpsertBulk) DoNothing() *GlobalProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GlobalProxyCreateBulk.OnConflict
// documentation for more info.
func (u *GlobalProxyUpsertBulk) Update(set func(*GlobalProxyUpsert)) *GlobalProxyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GlobalProxyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GlobalProxyUpsertBulk) SetUpdatedAt(v time.Time) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateUpdatedAt() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GlobalProxyUpsertBulk) SetDeletedAt(v time.Time) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateDeletedAt() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GlobalProxyUpsertBulk) ClearDeletedAt() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *GlobalProxyUpsertBulk) SetName(v string) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateName() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateName()
	})
}

// SetIPType sets the "ip_type" field.
func (u *GlobalProxyUpsertBulk) SetIPType(v string) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetIPType(v)
	})
}

// UpdateIPType sets the "ip_type" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateIPType() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateIPType()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *GlobalProxyUpsertBulk) SetEndpoint(v string) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateEndpoint() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateEndpoint()
	})
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *GlobalProxyUpsertBulk) ClearEndpoint() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearEndpoint()
	})
}

// SetStatus sets the "status" field.
func (u *GlobalProxyUpsertBulk) SetStatus(v string) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateStatus() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateStatus()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GlobalProxyUpsertBulk) SetLatencyMs(v int) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GlobalProxyUpsertBulk) AddLatencyMs(v int) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateLatencyMs() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *GlobalProxyUpsertBulk) ClearLatencyMs() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearLatencyMs()
	})
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *GlobalProxyUpsertBulk) SetLastCheckAt(v time.Time) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetLastCheckAt(v)
	})
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateLastCheckAt() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateLastCheckAt()
	})
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *GlobalProxyUpsertBulk) ClearLastCheckAt() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearLastCheckAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *GlobalProxyUpsertBulk) SetLastUsedAt(v time.Time) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateLastUsedAt() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *GlobalProxyUpsertBulk) ClearLastUsedAt() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRemark sets the "remark" field.
func (u *GlobalProxyUpsertBulk) SetRemark(v string) *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *GlobalProxyUpsertBulk) UpdateRemark() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *GlobalProxyUpsertBulk) ClearRemark() *GlobalProxyUpsertBulk {
	return u.Update(func(s *GlobalProxyUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *GlobalProxyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GlobalProxyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GlobalProxyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GlobalProxyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
