// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/socialops/ent/predicate"
	"github.com/Wei-Shaw/socialops/ent/socialaccount"
	"github.com/Wei-Shaw/socialops/ent/socialtasklog"
	"github.com/Wei-Shaw/socialops/ent/user"
)

// SocialTaskLogUpdate is the builder for updating SocialTaskLog entities.
type SocialTaskLogUpdate struct {
	config
	hooks    []Hook
	mutation *SocialTaskLogMutation
}

// Where appends a list predicates to the SocialTaskLogUpdate builder.
func (_u *SocialTaskLogUpdate) Where(ps ...predicate.SocialTaskLog) *SocialTaskLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SocialTaskLogUpdate) SetUpdatedAt(v time.Time) *SocialTaskLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSocialAccountID sets the "social_account_id" field.
func (_u *SocialTaskLogUpdate) SetSocialAccountID(v int64) *SocialTaskLogUpdate {
	_u.mutation.SetSocialAccountID(v)
	return _u
}

// SetNillableSocialAccountID sets the "social_account_id" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableSocialAccountID(v *int64) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetSocialAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SocialTaskLogUpdate) SetUserID(v int64) *SocialTaskLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableUserID(v *int64) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *SocialTaskLogUpdate) SetAction(v string) *SocialTaskLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableAction(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *SocialTaskLogUpdate) SetTarget(v string) *SocialTaskLogUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableTarget(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// ClearTarget clears the value of the "target" field.
func (_u *SocialTaskLogUpdate) ClearTarget() *SocialTaskLogUpdate {
	_u.mutation.ClearTarget()
	return _u
}

// SetContent sets the "content" field.
func (_u *SocialTaskLogUpdate) SetContent(v string) *SocialTaskLogUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableContent(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *SocialTaskLogUpdate) ClearContent() *SocialTaskLogUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SocialTaskLogUpdate) SetStatus(v string) *SocialTaskLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableStatus(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResultMessage sets the "result_message" field.
func (_u *SocialTaskLogUpdate) SetResultMessage(v string) *SocialTaskLogUpdate {
	_u.mutation.SetResultMessage(v)
	return _u
}

// SetNillableResultMessage sets the "result_message" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableResultMessage(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetResultMessage(*v)
	}
	return _u
}

// ClearResultMessage clears the value of the "result_message" field.
func (_u *SocialTaskLogUpdate) ClearResultMessage() *SocialTaskLogUpdate {
	_u.mutation.ClearResultMessage()
	return _u
}

// SetPrice sets the "price" field.
func (_u *SocialTaskLogUpdate) SetPrice(v float64) *SocialTaskLogUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillablePrice(v *float64) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SocialTaskLogUpdate) AddPrice(v float64) *SocialTaskLogUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetChargedAmount sets the "charged_amount" field.
func (_u *SocialTaskLogUpdate) SetChargedAmount(v float64) *SocialTaskLogUpdate {
	_u.mutation.ResetChargedAmount()
	_u.mutation.SetChargedAmount(v)
	return _u
}

// SetNillableChargedAmount sets the "charged_amount" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableChargedAmount(v *float64) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetChargedAmount(*v)
	}
	return _u
}

// AddChargedAmount adds value to the "charged_amount" field.
func (_u *SocialTaskLogUpdate) AddChargedAmount(v float64) *SocialTaskLogUpdate {
	_u.mutation.AddChargedAmount(v)
	return _u
}

// SetChargeStatus sets the "charge_status" field.
func (_u *SocialTaskLogUpdate) SetChargeStatus(v string) *SocialTaskLogUpdate {
	_u.mutation.SetChargeStatus(v)
	return _u
}

// SetNillableChargeStatus sets the "charge_status" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableChargeStatus(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetChargeStatus(*v)
	}
	return _u
}

// SetChargeSource sets the "charge_source" field.
func (_u *SocialTaskLogUpdate) SetChargeSource(v string) *SocialTaskLogUpdate {
	_u.mutation.SetChargeSource(v)
	return _u
}

// SetNillableChargeSource sets the "charge_source" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableChargeSource(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetChargeSource(*v)
	}
	return _u
}

// ClearChargeSource clears the value of the "charge_source" field.
func (_u *SocialTaskLogUpdate) ClearChargeSource() *SocialTaskLogUpdate {
	_u.mutation.ClearChargeSource()
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *SocialTaskLogUpdate) SetProxyID(v int64) *SocialTaskLogUpdate {
	_u.mutation.ResetProxyID()
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableProxyID(v *int64) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// AddProxyID adds value to the "proxy_id" field.
func (_u *SocialTaskLogUpdate) AddProxyID(v int64) *SocialTaskLogUpdate {
	_u.mutation.AddProxyID(v)
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *SocialTaskLogUpdate) ClearProxyID() *SocialTaskLogUpdate {
	_u.mutation.ClearProxyID()
	return _u
}

// SetProxySnapshot sets the "proxy_snapshot" field.
func (_u *SocialTaskLogUpdate) SetProxySnapshot(v string) *SocialTaskLogUpdate {
	_u.mutation.SetProxySnapshot(v)
	return _u
}

// SetNillableProxySnapshot sets the "proxy_snapshot" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableProxySnapshot(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetProxySnapshot(*v)
	}
	return _u
}

// ClearProxySnapshot clears the value of the "proxy_snapshot" field.
func (_u *SocialTaskLogUpdate) ClearProxySnapshot() *SocialTaskLogUpdate {
	_u.mutation.ClearProxySnapshot()
	return _u
}

// SetBillingRequestID sets the "billing_request_id" field.
func (_u *SocialTaskLogUpdate) SetBillingRequestID(v string) *SocialTaskLogUpdate {
	_u.mutation.SetBillingRequestID(v)
	return _u
}

// SetNillableBillingRequestID sets the "billing_request_id" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableBillingRequestID(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetBillingRequestID(*v)
	}
	return _u
}

// ClearBillingRequestID clears the value of the "billing_request_id" field.
func (_u *SocialTaskLogUpdate) ClearBillingRequestID() *SocialTaskLogUpdate {
	_u.mutation.ClearBillingRequestID()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *SocialTaskLogUpdate) SetIdempotencyKey(v string) *SocialTaskLogUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableIdempotencyKey(v *string) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *SocialTaskLogUpdate) ClearIdempotencyKey() *SocialTaskLogUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *SocialTaskLogUpdate) SetExecutedAt(v time.Time) *SocialTaskLogUpdate {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *SocialTaskLogUpdate) SetNillableExecutedAt(v *time.Time) *SocialTaskLogUpdate {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (_u *SocialTaskLogUpdate) ClearExecutedAt() *SocialTaskLogUpdate {
	_u.mutation.ClearExecutedAt()
	return _u
}

// SetSocialAccount sets the "social_account" edge to the SocialAccount entity.
func (_u *SocialTaskLogUpdate) SetSocialAccount(v *SocialAccount) *SocialTaskLogUpdate {
	return _u.SetSocialAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *SocialTaskLogUpdate) SetUser(v *User) *SocialTaskLogUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SocialTaskLogMutation object of the builder.
func (_u *SocialTaskLogUpdate) Mutation() *SocialTaskLogMutation {
	return _u.mutation
}

// ClearSocialAccount clears the "social_account" edge to the SocialAccount entity.
func (_u *SocialTaskLogUpdate) ClearSocialAccount() *SocialTaskLogUpdate {
	_u.mutation.ClearSocialAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SocialTaskLogUpdate) ClearUser() *SocialTaskLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SocialTaskLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SocialTaskLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SocialTaskLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SocialTaskLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SocialTaskLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := socialtasklog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SocialTaskLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := socialtasklog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := socialtasklog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChargeStatus(); ok {
		if err := socialtasklog.ChargeStatusValidator(v); err != nil {
			return &ValidationError{Name: "charge_status", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.charge_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChargeSource(); ok {
		if err := socialtasklog.ChargeSourceValidator(v); err != nil {
			return &ValidationError{Name: "charge_source", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.charge_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingRequestID(); ok {
		if err := socialtasklog.BillingRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "billing_request_id", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.billing_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := socialtasklog.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.SocialAccountCleared() && len(_u.mutation.SocialAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SocialTaskLog.social_account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SocialTaskLog.user"`)
	}
	return nil
}

func (_u *SocialTaskLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(socialtasklog.Table, socialtasklog.Columns, sqlgraph.NewFieldSpec(socialtasklog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(socialtasklog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(socialtasklog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(socialtasklog.FieldTarget, field.TypeString, value)
	}
	if _u.mutation.TargetCleared() {
		_spec.ClearField(socialtasklog.FieldTarget, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(socialtasklog.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(socialtasklog.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(socialtasklog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultMessage(); ok {
		_spec.SetField(socialtasklog.FieldResultMessage, field.TypeString, value)
	}
	if _u.mutation.ResultMessageCleared() {
		_spec.ClearField(socialtasklog.FieldResultMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(socialtasklog.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(socialtasklog.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ChargedAmount(); ok {
		_spec.SetField(socialtasklog.FieldChargedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedChargedAmount(); ok {
		_spec.AddField(socialtasklog.FieldChargedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ChargeStatus(); ok {
		_spec.SetField(socialtasklog.FieldChargeStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChargeSource(); ok {
		_spec.SetField(socialtasklog.FieldChargeSource, field.TypeString, value)
	}
	if _u.mutation.ChargeSourceCleared() {
		_spec.ClearField(socialtasklog.FieldChargeSource, field.TypeString)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(socialtasklog.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyID(); ok {
		_spec.AddField(socialtasklog.FieldProxyID, field.TypeInt64, value)
	}
	if _u.mutation.ProxyIDCleared() {
		_spec.ClearField(socialtasklog.FieldProxyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProxySnapshot(); ok {
		_spec.SetField(socialtasklog.FieldProxySnapshot, field.TypeString, value)
	}
	if _u.mutation.ProxySnapshotCleared() {
		_spec.ClearField(socialtasklog.FieldProxySnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.BillingRequestID(); ok {
		_spec.SetField(socialtasklog.FieldBillingRequestID, field.TypeString, value)
	}
	if _u.mutation.BillingRequestIDCleared() {
		_spec.ClearField(socialtasklog.FieldBillingRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(socialtasklog.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(socialtasklog.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(socialtasklog.FieldExecutedAt, field.TypeTime, value)
	}
	if _u.mutation.ExecutedAtCleared() {
		_spec.ClearField(socialtasklog.FieldExecutedAt, field.TypeTime)
	}
	if _u.mutation.SocialAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialtasklog.SocialAccountTable,
			Columns: []string{socialtasklog.SocialAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialaccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SocialAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialtasklog.SocialAccountTable,
			Columns: []string{socialtasklog.SocialAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialtasklog.UserTable,
			Columns: []string{socialtasklog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialtasklog.UserTable,
			Columns: []string{socialtasklog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{socialtasklog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SocialTaskLogUpdateOne is the builder for updating a single SocialTaskLog entity.
type SocialTaskLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SocialTaskLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SocialTaskLogUpdateOne) SetUpdatedAt(v time.Time) *SocialTaskLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSocialAccountID sets the "social_account_id" field.
func (_u *SocialTaskLogUpdateOne) SetSocialAccountID(v int64) *SocialTaskLogUpdateOne {
	_u.mutation.SetSocialAccountID(v)
	return _u
}

// SetNillableSocialAccountID sets the "social_account_id" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableSocialAccountID(v *int64) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetSocialAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SocialTaskLogUpdateOne) SetUserID(v int64) *SocialTaskLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableUserID(v *int64) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *SocialTaskLogUpdateOne) SetAction(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableAction(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *SocialTaskLogUpdateOne) SetTarget(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableTarget(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// ClearTarget clears the value of the "target" field.
func (_u *SocialTaskLogUpdateOne) ClearTarget() *SocialTaskLogUpdateOne {
	_u.mutation.ClearTarget()
	return _u
}

// SetContent sets the "content" field.
func (_u *SocialTaskLogUpdateOne) SetContent(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableContent(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *SocialTaskLogUpdateOne) ClearContent() *SocialTaskLogUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SocialTaskLogUpdateOne) SetStatus(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableStatus(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResultMessage sets the "result_message" field.
func (_u *SocialTaskLogUpdateOne) SetResultMessage(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetResultMessage(v)
	return _u
}

// SetNillableResultMessage sets the "result_message" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableResultMessage(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetResultMessage(*v)
	}
	return _u
}

// ClearResultMessage clears the value of the "result_message" field.
func (_u *SocialTaskLogUpdateOne) ClearResultMessage() *SocialTaskLogUpdateOne {
	_u.mutation.ClearResultMessage()
	return _u
}

// SetPrice sets the "price" field.
func (_u *SocialTaskLogUpdateOne) SetPrice(v float64) *SocialTaskLogUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillablePrice(v *float64) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SocialTaskLogUpdateOne) AddPrice(v float64) *SocialTaskLogUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetChargedAmount sets the "charged_amount" field.
func (_u *SocialTaskLogUpdateOne) SetChargedAmount(v float64) *SocialTaskLogUpdateOne {
	_u.mutation.ResetChargedAmount()
	_u.mutation.SetChargedAmount(v)
	return _u
}

// SetNillableChargedAmount sets the "charged_amount" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableChargedAmount(v *float64) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetChargedAmount(*v)
	}
	return _u
}

// AddChargedAmount adds value to the "charged_amount" field.
func (_u *SocialTaskLogUpdateOne) AddChargedAmount(v float64) *SocialTaskLogUpdateOne {
	_u.mutation.AddChargedAmount(v)
	return _u
}

// SetChargeStatus sets the "charge_status" field.
func (_u *SocialTaskLogUpdateOne) SetChargeStatus(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetChargeStatus(v)
	return _u
}

// SetNillableChargeStatus sets the "charge_status" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableChargeStatus(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetChargeStatus(*v)
	}
	return _u
}

// SetChargeSource sets the "charge_source" field.
func (_u *SocialTaskLogUpdateOne) SetChargeSource(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetChargeSource(v)
	return _u
}

// SetNillableChargeSource sets the "charge_source" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableChargeSource(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetChargeSource(*v)
	}
	return _u
}

// ClearChargeSource clears the value of the "charge_source" field.
func (_u *SocialTaskLogUpdateOne) ClearChargeSource() *SocialTaskLogUpdateOne {
	_u.mutation.ClearChargeSource()
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *SocialTaskLogUpdateOne) SetProxyID(v int64) *SocialTaskLogUpdateOne {
	_u.mutation.ResetProxyID()
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableProxyID(v *int64) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// AddProxyID adds value to the "proxy_id" field.
func (_u *SocialTaskLogUpdateOne) AddProxyID(v int64) *SocialTaskLogUpdateOne {
	_u.mutation.AddProxyID(v)
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *SocialTaskLogUpdateOne) ClearProxyID() *SocialTaskLogUpdateOne {
	_u.mutation.ClearProxyID()
	return _u
}

// SetProxySnapshot sets the "proxy_snapshot" field.
func (_u *SocialTaskLogUpdateOne) SetProxySnapshot(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetProxySnapshot(v)
	return _u
}

// SetNillableProxySnapshot sets the "proxy_snapshot" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableProxySnapshot(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetProxySnapshot(*v)
	}
	return _u
}

// ClearProxySnapshot clears the value of the "proxy_snapshot" field.
func (_u *SocialTaskLogUpdateOne) ClearProxySnapshot() *SocialTaskLogUpdateOne {
	_u.mutation.ClearProxySnapshot()
	return _u
}

// SetBillingRequestID sets the "billing_request_id" field.
func (_u *SocialTaskLogUpdateOne) SetBillingRequestID(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetBillingRequestID(v)
	return _u
}

// SetNillableBillingRequestID sets the "billing_request_id" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableBillingRequestID(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetBillingRequestID(*v)
	}
	return _u
}

// ClearBillingRequestID clears the value of the "billing_request_id" field.
func (_u *SocialTaskLogUpdateOne) ClearBillingRequestID() *SocialTaskLogUpdateOne {
	_u.mutation.ClearBillingRequestID()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *SocialTaskLogUpdateOne) SetIdempotencyKey(v string) *SocialTaskLogUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableIdempotencyKey(v *string) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *SocialTaskLogUpdateOne) ClearIdempotencyKey() *SocialTaskLogUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetExecutedAt sets the "executed_at" field.
func (_u *SocialTaskLogUpdateOne) SetExecutedAt(v time.Time) *SocialTaskLogUpdateOne {
	_u.mutation.SetExecutedAt(v)
	return _u
}

// SetNillableExecutedAt sets the "executed_at" field if the given value is not nil.
func (_u *SocialTaskLogUpdateOne) SetNillableExecutedAt(v *time.Time) *SocialTaskLogUpdateOne {
	if v != nil {
		_u.SetExecutedAt(*v)
	}
	return _u
}

// ClearExecutedAt clears the value of the "executed_at" field.
func (_u *SocialTaskLogUpdateOne) ClearExecutedAt() *SocialTaskLogUpdateOne {
	_u.mutation.ClearExecutedAt()
	return _u
}

// SetSocialAccount sets the "social_account" edge to the SocialAccount entity.
func (_u *SocialTaskLogUpdateOne) SetSocialAccount(v *SocialAccount) *SocialTaskLogUpdateOne {
	return _u.SetSocialAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *SocialTaskLogUpdateOne) SetUser(v *User) *SocialTaskLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SocialTaskLogMutation object of the builder.
func (_u *SocialTaskLogUpdateOne) Mutation() *SocialTaskLogMutation {
	return _u.mutation
}

// ClearSocialAccount clears the "social_account" edge to the SocialAccount entity.
func (_u *SocialTaskLogUpdateOne) ClearSocialAccount() *SocialTaskLogUpdateOne {
	_u.mutation.ClearSocialAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SocialTaskLogUpdateOne) ClearUser() *SocialTaskLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SocialTaskLogUpdate builder.
func (_u *SocialTaskLogUpdateOne) Where(ps ...predicate.SocialTaskLog) *SocialTaskLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SocialTaskLogUpdateOne) Select(field string, fields ...string) *SocialTaskLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SocialTaskLog entity.
func (_u *SocialTaskLogUpdateOne) Save(ctx context.Context) (*SocialTaskLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SocialTaskLogUpdateOne) SaveX(ctx context.Context) *SocialTaskLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SocialTaskLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SocialTaskLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SocialTaskLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := socialtasklog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SocialTaskLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := socialtasklog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := socialtasklog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChargeStatus(); ok {
		if err := socialtasklog.ChargeStatusValidator(v); err != nil {
			return &ValidationError{Name: "charge_status", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.charge_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChargeSource(); ok {
		if err := socialtasklog.ChargeSourceValidator(v); err != nil {
			return &ValidationError{Name: "charge_source", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.charge_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingRequestID(); ok {
		if err := socialtasklog.BillingRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "billing_request_id", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.billing_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := socialtasklog.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "SocialTaskLog.idempotency_key": %w`, err)}
		}
	}
	if _u.mutation.SocialAccountCleared() && len(_u.mutation.SocialAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SocialTaskLog.social_account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SocialTaskLog.user"`)
	}
	return nil
}

func (_u *SocialTaskLogUpdateOne) sqlSave(ctx context.Context) (_node *SocialTaskLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(socialtasklog.Table, socialtasklog.Columns, sqlgraph.NewFieldSpec(socialtasklog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SocialTaskLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, socialtasklog.FieldID)
		for _, f := range fields {
			if !socialtasklog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != socialtasklog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(socialtasklog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(socialtasklog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(socialtasklog.FieldTarget, field.TypeString, value)
	}
	if _u.mutation.TargetCleared() {
		_spec.ClearField(socialtasklog.FieldTarget, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(socialtasklog.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(socialtasklog.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(socialtasklog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResultMessage(); ok {
		_spec.SetField(socialtasklog.FieldResultMessage, field.TypeString, value)
	}
	if _u.mutation.ResultMessageCleared() {
		_spec.ClearField(socialtasklog.FieldResultMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(socialtasklog.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(socialtasklog.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ChargedAmount(); ok {
		_spec.SetField(socialtasklog.FieldChargedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedChargedAmount(); ok {
		_spec.AddField(socialtasklog.FieldChargedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ChargeStatus(); ok {
		_spec.SetField(socialtasklog.FieldChargeStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChargeSource(); ok {
		_spec.SetField(socialtasklog.FieldChargeSource, field.TypeString, value)
	}
	if _u.mutation.ChargeSourceCleared() {
		_spec.ClearField(socialtasklog.FieldChargeSource, field.TypeString)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(socialtasklog.FieldProxyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProxyID(); ok {
		_spec.AddField(socialtasklog.FieldProxyID, field.TypeInt64, value)
	}
	if _u.mutation.ProxyIDCleared() {
		_spec.ClearField(socialtasklog.FieldProxyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProxySnapshot(); ok {
		_spec.SetField(socialtasklog.FieldProxySnapshot, field.TypeString, value)
	}
	if _u.mutation.ProxySnapshotCleared() {
		_spec.ClearField(socialtasklog.FieldProxySnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.BillingRequestID(); ok {
		_spec.SetField(socialtasklog.FieldBillingRequestID, field.TypeString, value)
	}
	if _u.mutation.BillingRequestIDCleared() {
		_spec.ClearField(socialtasklog.FieldBillingRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(socialtasklog.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(socialtasklog.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutedAt(); ok {
		_spec.SetField(socialtasklog.FieldExecutedAt, field.TypeTime, value)
	}
	if _u.mutation.ExecutedAtCleared() {
		_spec.ClearField(socialtasklog.FieldExecutedAt, field.TypeTime)
	}
	if _u.mutation.SocialAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialtasklog.SocialAccountTable,
			Columns: []string{socialtasklog.SocialAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialaccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SocialAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialtasklog.SocialAccountTable,
			Columns: []string{socialtasklog.SocialAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialtasklog.UserTable,
			Columns: []string{socialtasklog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialtasklog.UserTable,
			Columns: []string{socialtasklog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SocialTaskLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{socialtasklog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
