// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/socialops/ent/socialaccount"
	"github.com/Wei-Shaw/socialops/ent/user"
)

// SocialAccount is the model entity for the SocialAccount schema.
type SocialAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 账号名称 / 用户名，如 @northwind_ops
	Name string `json:"name,omitempty"`
	// 平台：x_twitter / instagram / tiktok / facebook
	Platform string `json:"platform,omitempty"`
	// Normalized platform key for total-pool uniqueness
	PlatformKey string `json:"platform_key,omitempty"`
	// Normalized username key for total-pool uniqueness
	NameKey string `json:"name_key,omitempty"`
	// 平台账号 ID
	AccountID *string `json:"account_id,omitempty"`
	// 账号密码（按业务要求原样存储和返回）
	Password *string `json:"password,omitempty"`
	// 绑定手机号
	Phone *string `json:"phone,omitempty"`
	// 绑定邮箱
	Email *string `json:"email,omitempty"`
	// 邮箱密码（按业务要求原样存储和返回）
	EmailPassword *string `json:"email_password,omitempty"`
	// 账号状态：pending_check / available / limited / invalid / not_stored
	AccountStatus string `json:"account_status,omitempty"`
	// 任务状态：pending / registering / importing / parsing / stored / register_failed / risk_rejected / duplicate / ip_unavailable / manual_review
	TaskStatus string `json:"task_status,omitempty"`
	// 任务状态描述
	TaskMessage *string `json:"task_message,omitempty"`
	// 账号来源：registered / manual_import / file_upload
	Source string `json:"source,omitempty"`
	// 默认执行代理快照
	BoundIP *string `json:"bound_ip,omitempty"`
	// 分配给的用户 ID
	AssignedUserID *int64 `json:"assigned_user_id,omitempty"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SocialAccountQuery when eager-loading is set.
	Edges        SocialAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SocialAccountEdges holds the relations/edges for other nodes in the graph.
type SocialAccountEdges struct {
	// AssignedUser holds the value of the assigned_user edge.
	AssignedUser *User `json:"assigned_user,omitempty"`
	// TaskLogs holds the value of the task_logs edge.
	TaskLogs []*SocialTaskLog `json:"task_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AssignedUserOrErr returns the AssignedUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SocialAccountEdges) AssignedUserOrErr() (*User, error) {
	if e.AssignedUser != nil {
		return e.AssignedUser, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assigned_user"}
}

// TaskLogsOrErr returns the TaskLogs value or an error if the edge
// was not loaded in eager-loading.
func (e SocialAccountEdges) TaskLogsOrErr() ([]*SocialTaskLog, error) {
	if e.loadedTypes[1] {
		return e.TaskLogs, nil
	}
	return nil, &NotLoadedError{edge: "task_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SocialAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case socialaccount.FieldID, socialaccount.FieldAssignedUserID:
			values[i] = new(sql.NullInt64)
		case socialaccount.FieldName, socialaccount.FieldPlatform, socialaccount.FieldPlatformKey, socialaccount.FieldNameKey, socialaccount.FieldAccountID, socialaccount.FieldPassword, socialaccount.FieldPhone, socialaccount.FieldEmail, socialaccount.FieldEmailPassword, socialaccount.FieldAccountStatus, socialaccount.FieldTaskStatus, socialaccount.FieldTaskMessage, socialaccount.FieldSource, socialaccount.FieldBoundIP, socialaccount.FieldRemark:
			values[i] = new(sql.NullString)
		case socialaccount.FieldCreatedAt, socialaccount.FieldUpdatedAt, socialaccount.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SocialAccount fields.
func (_m *SocialAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case socialaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case socialaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case socialaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case socialaccount.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case socialaccount.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case socialaccount.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case socialaccount.FieldPlatformKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_key", values[i])
			} else if value.Valid {
				_m.PlatformKey = value.String
			}
		case socialaccount.FieldNameKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_key", values[i])
			} else if value.Valid {
				_m.NameKey = value.String
			}
		case socialaccount.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(string)
				*_m.AccountID = value.String
			}
		case socialaccount.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = new(string)
				*_m.Password = value.String
			}
		case socialaccount.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				_m.Phone = new(string)
				*_m.Phone = value.String
			}
		case socialaccount.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = new(string)
				*_m.Email = value.String
			}
		case socialaccount.FieldEmailPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_password", values[i])
			} else if value.Valid {
				_m.EmailPassword = new(string)
				*_m.EmailPassword = value.String
			}
		case socialaccount.FieldAccountStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_status", values[i])
			} else if value.Valid {
				_m.AccountStatus = value.String
			}
		case socialaccount.FieldTaskStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_status", values[i])
			} else if value.Valid {
				_m.TaskStatus = value.String
			}
		case socialaccount.FieldTaskMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_message", values[i])
			} else if value.Valid {
				_m.TaskMessage = new(string)
				*_m.TaskMessage = value.String
			}
		case socialaccount.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case socialaccount.FieldBoundIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bound_ip", values[i])
			} else if value.Valid {
				_m.BoundIP = new(string)
				*_m.BoundIP = value.String
			}
		case socialaccount.FieldAssignedUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_user_id", values[i])
			} else if value.Valid {
				_m.AssignedUserID = new(int64)
				*_m.AssignedUserID = value.Int64
			}
		case socialaccount.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SocialAccount.
// This includes values selected through modifiers, order, etc.
func (_m *SocialAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAssignedUser queries the "assigned_user" edge of the SocialAccount entity.
func (_m *SocialAccount) QueryAssignedUser() *UserQuery {
	return NewSocialAccountClient(_m.config).QueryAssignedUser(_m)
}

// QueryTaskLogs queries the "task_logs" edge of the SocialAccount entity.
func (_m *SocialAccount) QueryTaskLogs() *SocialTaskLogQuery {
	return NewSocialAccountClient(_m.config).QueryTaskLogs(_m)
}

// Update returns a builder for updating this SocialAccount.
// Note that you need to call SocialAccount.Unwrap() before calling this method if this SocialAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SocialAccount) Update() *SocialAccountUpdateOne {
	return NewSocialAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SocialAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SocialAccount) Unwrap() *SocialAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SocialAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SocialAccount) String() string {
	var builder strings.Builder
	builder.WriteString("SocialAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("platform_key=")
	builder.WriteString(_m.PlatformKey)
	builder.WriteString(", ")
	builder.WriteString("name_key=")
	builder.WriteString(_m.NameKey)
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Password; v != nil {
		builder.WriteString("password=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Phone; v != nil {
		builder.WriteString("phone=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.EmailPassword; v != nil {
		builder.WriteString("email_password=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("account_status=")
	builder.WriteString(_m.AccountStatus)
	builder.WriteString(", ")
	builder.WriteString("task_status=")
	builder.WriteString(_m.TaskStatus)
	builder.WriteString(", ")
	if v := _m.TaskMessage; v != nil {
		builder.WriteString("task_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.BoundIP; v != nil {
		builder.WriteString("bound_ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AssignedUserID; v != nil {
		builder.WriteString("assigned_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// SocialAccounts is a parsable slice of SocialAccount.
type SocialAccounts []*SocialAccount
