// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/socialops/ent/socialip"
	"github.com/Wei-Shaw/socialops/ent/user"
)

// SocialIPCreate is the builder for creating a SocialIP entity.
type SocialIPCreate struct {
	config
	mutation *SocialIPMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SocialIPCreate) SetCreatedAt(v time.Time) *SocialIPCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableCreatedAt(v *time.Time) *SocialIPCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SocialIPCreate) SetUpdatedAt(v time.Time) *SocialIPCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableUpdatedAt(v *time.Time) *SocialIPCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SocialIPCreate) SetDeletedAt(v time.Time) *SocialIPCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableDeletedAt(v *time.Time) *SocialIPCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SocialIPCreate) SetUserID(v int64) *SocialIPCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SocialIPCreate) SetName(v string) *SocialIPCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIPType sets the "ip_type" field.
func (_c *SocialIPCreate) SetIPType(v string) *SocialIPCreate {
	_c.mutation.SetIPType(v)
	return _c
}

// SetNillableIPType sets the "ip_type" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableIPType(v *string) *SocialIPCreate {
	if v != nil {
		_c.SetIPType(*v)
	}
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *SocialIPCreate) SetEndpoint(v string) *SocialIPCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableEndpoint(v *string) *SocialIPCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SocialIPCreate) SetStatus(v string) *SocialIPCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableStatus(v *string) *SocialIPCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *SocialIPCreate) SetLatencyMs(v int) *SocialIPCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableLatencyMs(v *int) *SocialIPCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetLastCheckAt sets the "last_check_at" field.
func (_c *SocialIPCreate) SetLastCheckAt(v time.Time) *SocialIPCreate {
	_c.mutation.SetLastCheckAt(v)
	return _c
}

// SetNillableLastCheckAt sets the "last_check_at" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableLastCheckAt(v *time.Time) *SocialIPCreate {
	if v != nil {
		_c.SetLastCheckAt(*v)
	}
	return _c
}

// SetBoundSocialAccountID sets the "bound_social_account_id" field.
func (_c *SocialIPCreate) SetBoundSocialAccountID(v int64) *SocialIPCreate {
	_c.mutation.SetBoundSocialAccountID(v)
	return _c
}

// SetNillableBoundSocialAccountID sets the "bound_social_account_id" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableBoundSocialAccountID(v *int64) *SocialIPCreate {
	if v != nil {
		_c.SetBoundSocialAccountID(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *SocialIPCreate) SetRemark(v string) *SocialIPCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *SocialIPCreate) SetNillableRemark(v *string) *SocialIPCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SocialIPCreate) SetUser(v *User) *SocialIPCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SocialIPMutation object of the builder.
func (_c *SocialIPCreate) Mutation() *SocialIPMutation {
	return _c.mutation
}

// Save creates the SocialIP in the database.
func (_c *SocialIPCreate) Save(ctx context.Context) (*SocialIP, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SocialIPCreate) SaveX(ctx context.Context) *SocialIP {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SocialIPCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SocialIPCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SocialIPCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if socialip.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized socialip.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := socialip.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if socialip.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized socialip.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := socialip.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IPType(); !ok {
		v := socialip.DefaultIPType
		_c.mutation.SetIPType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := socialip.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SocialIPCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SocialIP.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SocialIP.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SocialIP.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SocialIP.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := socialip.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SocialIP.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IPType(); !ok {
		return &ValidationError{Name: "ip_type", err: errors.New(`ent: missing required field "SocialIP.ip_type"`)}
	}
	if v, ok := _c.mutation.IPType(); ok {
		if err := socialip.IPTypeValidator(v); err != nil {
			return &ValidationError{Name: "ip_type", err: fmt.Errorf(`ent: validator failed for field "SocialIP.ip_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Endpoint(); ok {
		if err := socialip.EndpointValidator(v); err != nil {
			return &ValidationError{Name: "endpoint", err: fmt.Errorf(`ent: validator failed for field "SocialIP.endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SocialIP.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := socialip.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SocialIP.status": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SocialIP.user"`)}
	}
	return nil
}

func (_c *SocialIPCreate) sqlSave(ctx context.Context) (*SocialIP, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SocialIPCreate) createSpec() (*SocialIP, *sqlgraph.CreateSpec) {
	var (
		_node = &SocialIP{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(socialip.Table, sqlgraph.NewFieldSpec(socialip.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(socialip.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(socialip.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(socialip.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(socialip.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IPType(); ok {
		_spec.SetField(socialip.FieldIPType, field.TypeString, value)
		_node.IPType = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(socialip.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(socialip.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(socialip.FieldLatencyMs, field.TypeInt, value)
		_node.LatencyMs = &value
	}
	if value, ok := _c.mutation.LastCheckAt(); ok {
		_spec.SetField(socialip.FieldLastCheckAt, field.TypeTime, value)
		_node.LastCheckAt = &value
	}
	if value, ok := _c.mutation.BoundSocialAccountID(); ok {
		_spec.SetField(socialip.FieldBoundSocialAccountID, field.TypeInt64, value)
		_node.BoundSocialAccountID = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(socialip.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialip.UserTable,
			Columns: []string{socialip.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SocialIP.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SocialIPUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SocialIPCreate) OnConflict(opts ...sql.ConflictOption) *SocialIPUpsertOne {
	_c.conflict = opts
	return &SocialIPUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SocialIP.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SocialIPCreate) OnConflictColumns(columns ...string) *SocialIPUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SocialIPUpsertOne{
		create: _c,
	}
}

type (
	// SocialIPUpsertOne is the builder for "upsert"-ing
	//  one SocialIP node.
	SocialIPUpsertOne struct {
		create *SocialIPCreate
	}

	// SocialIPUpsert is the "OnConflict" setter.
	SocialIPUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SocialIPUpsert) SetUpdatedAt(v time.Time) *SocialIPUpsert {
	u.Set(socialip.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateUpdatedAt() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SocialIPUpsert) SetDeletedAt(v time.Time) *SocialIPUpsert {
	u.Set(socialip.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateDeletedAt() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SocialIPUpsert) ClearDeletedAt() *SocialIPUpsert {
	u.SetNull(socialip.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SocialIPUpsert) SetUserID(v int64) *SocialIPUpsert {
	u.Set(socialip.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateUserID() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldUserID)
	return u
}

// SetName sets the "name" field.
func (u *SocialIPUpsert) SetName(v string) *SocialIPUpsert {
	u.Set(socialip.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateName() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldName)
	return u
}

// SetIPType sets the "ip_type" field.
func (u *SocialIPUpsert) SetIPType(v string) *SocialIPUpsert {
	u.Set(socialip.FieldIPType, v)
	return u
}

// UpdateIPType sets the "ip_type" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateIPType() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldIPType)
	return u
}

// SetEndpoint sets the "endpoint" field.
func (u *SocialIPUpsert) SetEndpoint(v string) *SocialIPUpsert {
	u.Set(socialip.FieldEndpoint, v)
	return u
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateEndpoint() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldEndpoint)
	return u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *SocialIPUpsert) ClearEndpoint() *SocialIPUpsert {
	u.SetNull(socialip.FieldEndpoint)
	return u
}

// SetStatus sets the "status" field.
func (u *SocialIPUpsert) SetStatus(v string) *SocialIPUpsert {
	u.Set(socialip.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateStatus() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldStatus)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *SocialIPUpsert) SetLatencyMs(v int) *SocialIPUpsert {
	u.Set(socialip.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateLatencyMs() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *SocialIPUpsert) AddLatencyMs(v int) *SocialIPUpsert {
	u.Add(socialip.FieldLatencyMs, v)
	return u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *SocialIPUpsert) ClearLatencyMs() *SocialIPUpsert {
	u.SetNull(socialip.FieldLatencyMs)
	return u
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *SocialIPUpsert) SetLastCheckAt(v time.Time) *SocialIPUpsert {
	u.Set(socialip.FieldLastCheckAt, v)
	return u
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateLastCheckAt() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldLastCheckAt)
	return u
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *SocialIPUpsert) ClearLastCheckAt() *SocialIPUpsert {
	u.SetNull(socialip.FieldLastCheckAt)
	return u
}

// SetBoundSocialAccountID sets the "bound_social_account_id" field.
func (u *SocialIPUpsert) SetBoundSocialAccountID(v int64) *SocialIPUpsert {
	u.Set(socialip.FieldBoundSocialAccountID, v)
	return u
}

// UpdateBoundSocialAccountID sets the "bound_social_account_id" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateBoundSocialAccountID() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldBoundSocialAccountID)
	return u
}

// AddBoundSocialAccountID adds v to the "bound_social_account_id" field.
func (u *SocialIPUpsert) AddBoundSocialAccountID(v int64) *SocialIPUpsert {
	u.Add(socialip.FieldBoundSocialAccountID, v)
	return u
}

// ClearBoundSocialAccountID clears the value of the "bound_social_account_id" field.
func (u *SocialIPUpsert) ClearBoundSocialAccountID() *SocialIPUpsert {
	u.SetNull(socialip.FieldBoundSocialAccountID)
	return u
}

// SetRemark sets the "remark" field.
func (u *SocialIPUpsert) SetRemark(v string) *SocialIPUpsert {
	u.Set(socialip.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *SocialIPUpsert) UpdateRemark() *SocialIPUpsert {
	u.SetExcluded(socialip.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *SocialIPUpsert) ClearRemark() *SocialIPUpsert {
	u.SetNull(socialip.FieldRemark)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SocialIP.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SocialIPUpsertOne) UpdateNewValues() *SocialIPUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(socialip.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SocialIP.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SocialIPUpsertOne) Ignore() *SocialIPUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SocialIPUpsertOne) DoNothing() *SocialIPUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SocialIPCreate.OnConflict
// documentation for more info.
func (u *SocialIPUpsertOne) Update(set func(*SocialIPUpsert)) *SocialIPUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SocialIPUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SocialIPUpsertOne) SetUpdatedAt(v time.Time) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateUpdatedAt() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SocialIPUpsertOne) SetDeletedAt(v time.Time) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateDeletedAt() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SocialIPUpsertOne) ClearDeletedAt() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SocialIPUpsertOne) SetUserID(v int64) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateUserID() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *SocialIPUpsertOne) SetName(v string) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateName() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateName()
	})
}

// SetIPType sets the "ip_type" field.
func (u *SocialIPUpsertOne) SetIPType(v string) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetIPType(v)
	})
}

// UpdateIPType sets the "ip_type" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateIPType() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateIPType()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *SocialIPUpsertOne) SetEndpoint(v string) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateEndpoint() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateEndpoint()
	})
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *SocialIPUpsertOne) ClearEndpoint() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearEndpoint()
	})
}

// SetStatus sets the "status" field.
func (u *SocialIPUpsertOne) SetStatus(v string) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateStatus() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateStatus()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *SocialIPUpsertOne) SetLatencyMs(v int) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *SocialIPUpsertOne) AddLatencyMs(v int) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateLatencyMs() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *SocialIPUpsertOne) ClearLatencyMs() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearLatencyMs()
	})
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *SocialIPUpsertOne) SetLastCheckAt(v time.Time) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetLastCheckAt(v)
	})
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateLastCheckAt() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateLastCheckAt()
	})
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *SocialIPUpsertOne) ClearLastCheckAt() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearLastCheckAt()
	})
}

// SetBoundSocialAccountID sets the "bound_social_account_id" field.
func (u *SocialIPUpsertOne) SetBoundSocialAccountID(v int64) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetBoundSocialAccountID(v)
	})
}

// AddBoundSocialAccountID adds v to the "bound_social_account_id" field.
func (u *SocialIPUpsertOne) AddBoundSocialAccountID(v int64) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.AddBoundSocialAccountID(v)
	})
}

// UpdateBoundSocialAccountID sets the "bound_social_account_id" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateBoundSocialAccountID() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateBoundSocialAccountID()
	})
}

// ClearBoundSocialAccountID clears the value of the "bound_social_account_id" field.
func (u *SocialIPUpsertOne) ClearBoundSocialAccountID() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearBoundSocialAccountID()
	})
}

// SetRemark sets the "remark" field.
func (u *SocialIPUpsertOne) SetRemark(v string) *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *SocialIPUpsertOne) UpdateRemark() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *SocialIPUpsertOne) ClearRemark() *SocialIPUpsertOne {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *SocialIPUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SocialIPCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SocialIPUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SocialIPUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SocialIPUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SocialIPCreateBulk is the builder for creating many SocialIP entities in bulk.
type SocialIPCreateBulk struct {
	config
	err      error
	builders []*SocialIPCreate
	conflict []sql.ConflictOption
}

// Save creates the SocialIP entities in the database.
func (_c *SocialIPCreateBulk) Save(ctx context.Context) ([]*SocialIP, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SocialIP, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SocialIPMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SocialIPCreateBulk) SaveX(ctx context.Context) []*SocialIP {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SocialIPCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SocialIPCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SocialIP.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SocialIPUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SocialIPCreateBulk) OnConflict(opts ...sql.ConflictOption) *SocialIPUpsertBulk {
	_c.conflict = opts
	return &SocialIPUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SocialIP.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SocialIPCreateBulk) OnConflictColumns(columns ...string) *SocialIPUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SocialIPUpsertBulk{
		create: _c,
	}
}

// SocialIPUpsertBulk is the builder for "upsert"-ing
// a bulk of SocialIP nodes.
type SocialIPUpsertBulk struct {
	create *SocialIPCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SocialIP.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SocialIPUpsertBulk) UpdateNewValues() *SocialIPUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(socialip.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SocialIP.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SocialIPUpsertBulk) Ignore() *SocialIPUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SocialIPUpsertBulk) DoNothing() *SocialIPUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SocialIPCreateBulk.OnConflict
// documentation for more info.
func (u *SocialIPUpsertBulk) Update(set func(*SocialIPUpsert)) *SocialIPUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SocialIPUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SocialIPUpsertBulk) SetUpdatedAt(v time.Time) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateUpdatedAt() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SocialIPUpsertBulk) SetDeletedAt(v time.Time) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateDeletedAt() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SocialIPUpsertBulk) ClearDeletedAt() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SocialIPUpsertBulk) SetUserID(v int64) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateUserID() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *SocialIPUpsertBulk) SetName(v string) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateName() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateName()
	})
}

// SetIPType sets the "ip_type" field.
func (u *SocialIPUpsertBulk) SetIPType(v string) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetIPType(v)
	})
}

// UpdateIPType sets the "ip_type" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateIPType() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateIPType()
	})
}

// SetEndpoint sets the "endpoint" field.
func (u *SocialIPUpsertBulk) SetEndpoint(v string) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetEndpoint(v)
	})
}

// UpdateEndpoint sets the "endpoint" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateEndpoint() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateEndpoint()
	})
}

// ClearEndpoint clears the value of the "endpoint" field.
func (u *SocialIPUpsertBulk) ClearEndpoint() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearEndpoint()
	})
}

// SetStatus sets the "status" field.
func (u *SocialIPUpsertBulk) SetStatus(v string) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateStatus() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateStatus()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *SocialIPUpsertBulk) SetLatencyMs(v int) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *SocialIPUpsertBulk) AddLatencyMs(v int) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateLatencyMs() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateLatencyMs()
	})
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (u *SocialIPUpsertBulk) ClearLatencyMs() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearLatencyMs()
	})
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *SocialIPUpsertBulk) SetLastCheckAt(v time.Time) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetLastCheckAt(v)
	})
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateLastCheckAt() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateLastCheckAt()
	})
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *SocialIPUpsertBulk) ClearLastCheckAt() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearLastCheckAt()
	})
}

// SetBoundSocialAccountID sets the "bound_social_account_id" field.
func (u *SocialIPUpsertBulk) SetBoundSocialAccountID(v int64) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetBoundSocialAccountID(v)
	})
}

// AddBoundSocialAccountID adds v to the "bound_social_account_id" field.
func (u *SocialIPUpsertBulk) AddBoundSocialAccountID(v int64) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.AddBoundSocialAccountID(v)
	})
}

// UpdateBoundSocialAccountID sets the "bound_social_account_id" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateBoundSocialAccountID() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateBoundSocialAccountID()
	})
}

// ClearBoundSocialAccountID clears the value of the "bound_social_account_id" field.
func (u *SocialIPUpsertBulk) ClearBoundSocialAccountID() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearBoundSocialAccountID()
	})
}

// SetRemark sets the "remark" field.
func (u *SocialIPUpsertBulk) SetRemark(v string) *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *SocialIPUpsertBulk) UpdateRemark() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *SocialIPUpsertBulk) ClearRemark() *SocialIPUpsertBulk {
	return u.Update(func(s *SocialIPUpsert) {
		s.ClearRemark()
	})
}

// Exec executes the query.
func (u *SocialIPUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SocialIPCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SocialIPCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SocialIPUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
