// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/socialops/ent/predicate"
	"github.com/Wei-Shaw/socialops/ent/socialaccount"
	"github.com/Wei-Shaw/socialops/ent/socialtasklog"
	"github.com/Wei-Shaw/socialops/ent/user"
)

// SocialAccountUpdate is the builder for updating SocialAccount entities.
type SocialAccountUpdate struct {
	config
	hooks    []Hook
	mutation *SocialAccountMutation
}

// Where appends a list predicates to the SocialAccountUpdate builder.
func (_u *SocialAccountUpdate) Where(ps ...predicate.SocialAccount) *SocialAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SocialAccountUpdate) SetUpdatedAt(v time.Time) *SocialAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SocialAccountUpdate) SetDeletedAt(v time.Time) *SocialAccountUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableDeletedAt(v *time.Time) *SocialAccountUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SocialAccountUpdate) ClearDeletedAt() *SocialAccountUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *SocialAccountUpdate) SetName(v string) *SocialAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableName(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *SocialAccountUpdate) SetPlatform(v string) *SocialAccountUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillablePlatform(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPlatformKey sets the "platform_key" field.
func (_u *SocialAccountUpdate) SetPlatformKey(v string) *SocialAccountUpdate {
	_u.mutation.SetPlatformKey(v)
	return _u
}

// SetNillablePlatformKey sets the "platform_key" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillablePlatformKey(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetPlatformKey(*v)
	}
	return _u
}

// SetNameKey sets the "name_key" field.
func (_u *SocialAccountUpdate) SetNameKey(v string) *SocialAccountUpdate {
	_u.mutation.SetNameKey(v)
	return _u
}

// SetNillableNameKey sets the "name_key" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableNameKey(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetNameKey(*v)
	}
	return _u
}

// SetIdentityKind sets the "identity_kind" field.
func (_u *SocialAccountUpdate) SetIdentityKind(v string) *SocialAccountUpdate {
	_u.mutation.SetIdentityKind(v)
	return _u
}

// SetNillableIdentityKind sets the "identity_kind" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableIdentityKind(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetIdentityKind(*v)
	}
	return _u
}

// SetIdentityKey sets the "identity_key" field.
func (_u *SocialAccountUpdate) SetIdentityKey(v string) *SocialAccountUpdate {
	_u.mutation.SetIdentityKey(v)
	return _u
}

// SetNillableIdentityKey sets the "identity_key" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableIdentityKey(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetIdentityKey(*v)
	}
	return _u
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_u *SocialAccountUpdate) SetPlatformUserID(v string) *SocialAccountUpdate {
	_u.mutation.SetPlatformUserID(v)
	return _u
}

// SetNillablePlatformUserID sets the "platform_user_id" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillablePlatformUserID(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetPlatformUserID(*v)
	}
	return _u
}

// ClearPlatformUserID clears the value of the "platform_user_id" field.
func (_u *SocialAccountUpdate) ClearPlatformUserID() *SocialAccountUpdate {
	_u.mutation.ClearPlatformUserID()
	return _u
}

// SetPassword sets the "password" field.
func (_u *SocialAccountUpdate) SetPassword(v string) *SocialAccountUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillablePassword(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *SocialAccountUpdate) ClearPassword() *SocialAccountUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *SocialAccountUpdate) SetPhone(v string) *SocialAccountUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillablePhone(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *SocialAccountUpdate) ClearPhone() *SocialAccountUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetEmail sets the "email" field.
func (_u *SocialAccountUpdate) SetEmail(v string) *SocialAccountUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableEmail(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *SocialAccountUpdate) ClearEmail() *SocialAccountUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetEmailPassword sets the "email_password" field.
func (_u *SocialAccountUpdate) SetEmailPassword(v string) *SocialAccountUpdate {
	_u.mutation.SetEmailPassword(v)
	return _u
}

// SetNillableEmailPassword sets the "email_password" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableEmailPassword(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetEmailPassword(*v)
	}
	return _u
}

// ClearEmailPassword clears the value of the "email_password" field.
func (_u *SocialAccountUpdate) ClearEmailPassword() *SocialAccountUpdate {
	_u.mutation.ClearEmailPassword()
	return _u
}

// SetTwoFactor sets the "two_factor" field.
func (_u *SocialAccountUpdate) SetTwoFactor(v string) *SocialAccountUpdate {
	_u.mutation.SetTwoFactor(v)
	return _u
}

// SetNillableTwoFactor sets the "two_factor" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableTwoFactor(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetTwoFactor(*v)
	}
	return _u
}

// ClearTwoFactor clears the value of the "two_factor" field.
func (_u *SocialAccountUpdate) ClearTwoFactor() *SocialAccountUpdate {
	_u.mutation.ClearTwoFactor()
	return _u
}

// SetBackupCode sets the "backup_code" field.
func (_u *SocialAccountUpdate) SetBackupCode(v string) *SocialAccountUpdate {
	_u.mutation.SetBackupCode(v)
	return _u
}

// SetNillableBackupCode sets the "backup_code" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableBackupCode(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetBackupCode(*v)
	}
	return _u
}

// ClearBackupCode clears the value of the "backup_code" field.
func (_u *SocialAccountUpdate) ClearBackupCode() *SocialAccountUpdate {
	_u.mutation.ClearBackupCode()
	return _u
}

// SetEmailClientID sets the "email_client_id" field.
func (_u *SocialAccountUpdate) SetEmailClientID(v string) *SocialAccountUpdate {
	_u.mutation.SetEmailClientID(v)
	return _u
}

// SetNillableEmailClientID sets the "email_client_id" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableEmailClientID(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetEmailClientID(*v)
	}
	return _u
}

// ClearEmailClientID clears the value of the "email_client_id" field.
func (_u *SocialAccountUpdate) ClearEmailClientID() *SocialAccountUpdate {
	_u.mutation.ClearEmailClientID()
	return _u
}

// SetEmailToken sets the "email_token" field.
func (_u *SocialAccountUpdate) SetEmailToken(v string) *SocialAccountUpdate {
	_u.mutation.SetEmailToken(v)
	return _u
}

// SetNillableEmailToken sets the "email_token" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableEmailToken(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetEmailToken(*v)
	}
	return _u
}

// ClearEmailToken clears the value of the "email_token" field.
func (_u *SocialAccountUpdate) ClearEmailToken() *SocialAccountUpdate {
	_u.mutation.ClearEmailToken()
	return _u
}

// SetRegistrationIP sets the "registration_ip" field.
func (_u *SocialAccountUpdate) SetRegistrationIP(v string) *SocialAccountUpdate {
	_u.mutation.SetRegistrationIP(v)
	return _u
}

// SetNillableRegistrationIP sets the "registration_ip" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableRegistrationIP(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetRegistrationIP(*v)
	}
	return _u
}

// ClearRegistrationIP clears the value of the "registration_ip" field.
func (_u *SocialAccountUpdate) ClearRegistrationIP() *SocialAccountUpdate {
	_u.mutation.ClearRegistrationIP()
	return _u
}

// SetAuthCookie sets the "auth_cookie" field.
func (_u *SocialAccountUpdate) SetAuthCookie(v string) *SocialAccountUpdate {
	_u.mutation.SetAuthCookie(v)
	return _u
}

// SetNillableAuthCookie sets the "auth_cookie" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableAuthCookie(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetAuthCookie(*v)
	}
	return _u
}

// ClearAuthCookie clears the value of the "auth_cookie" field.
func (_u *SocialAccountUpdate) ClearAuthCookie() *SocialAccountUpdate {
	_u.mutation.ClearAuthCookie()
	return _u
}

// SetExecutionAuth sets the "execution_auth" field.
func (_u *SocialAccountUpdate) SetExecutionAuth(v string) *SocialAccountUpdate {
	_u.mutation.SetExecutionAuth(v)
	return _u
}

// SetNillableExecutionAuth sets the "execution_auth" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableExecutionAuth(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetExecutionAuth(*v)
	}
	return _u
}

// ClearExecutionAuth clears the value of the "execution_auth" field.
func (_u *SocialAccountUpdate) ClearExecutionAuth() *SocialAccountUpdate {
	_u.mutation.ClearExecutionAuth()
	return _u
}

// SetAccountStatus sets the "account_status" field.
func (_u *SocialAccountUpdate) SetAccountStatus(v string) *SocialAccountUpdate {
	_u.mutation.SetAccountStatus(v)
	return _u
}

// SetNillableAccountStatus sets the "account_status" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableAccountStatus(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetAccountStatus(*v)
	}
	return _u
}

// SetTaskStatus sets the "task_status" field.
func (_u *SocialAccountUpdate) SetTaskStatus(v string) *SocialAccountUpdate {
	_u.mutation.SetTaskStatus(v)
	return _u
}

// SetNillableTaskStatus sets the "task_status" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableTaskStatus(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetTaskStatus(*v)
	}
	return _u
}

// SetTaskMessage sets the "task_message" field.
func (_u *SocialAccountUpdate) SetTaskMessage(v string) *SocialAccountUpdate {
	_u.mutation.SetTaskMessage(v)
	return _u
}

// SetNillableTaskMessage sets the "task_message" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableTaskMessage(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetTaskMessage(*v)
	}
	return _u
}

// ClearTaskMessage clears the value of the "task_message" field.
func (_u *SocialAccountUpdate) ClearTaskMessage() *SocialAccountUpdate {
	_u.mutation.ClearTaskMessage()
	return _u
}

// SetDefaultProxySnapshot sets the "default_proxy_snapshot" field.
func (_u *SocialAccountUpdate) SetDefaultProxySnapshot(v string) *SocialAccountUpdate {
	_u.mutation.SetDefaultProxySnapshot(v)
	return _u
}

// SetNillableDefaultProxySnapshot sets the "default_proxy_snapshot" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableDefaultProxySnapshot(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetDefaultProxySnapshot(*v)
	}
	return _u
}

// ClearDefaultProxySnapshot clears the value of the "default_proxy_snapshot" field.
func (_u *SocialAccountUpdate) ClearDefaultProxySnapshot() *SocialAccountUpdate {
	_u.mutation.ClearDefaultProxySnapshot()
	return _u
}

// SetAssignedUserID sets the "assigned_user_id" field.
func (_u *SocialAccountUpdate) SetAssignedUserID(v int64) *SocialAccountUpdate {
	_u.mutation.SetAssignedUserID(v)
	return _u
}

// SetNillableAssignedUserID sets the "assigned_user_id" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableAssignedUserID(v *int64) *SocialAccountUpdate {
	if v != nil {
		_u.SetAssignedUserID(*v)
	}
	return _u
}

// ClearAssignedUserID clears the value of the "assigned_user_id" field.
func (_u *SocialAccountUpdate) ClearAssignedUserID() *SocialAccountUpdate {
	_u.mutation.ClearAssignedUserID()
	return _u
}

// SetUserWorkbenchDeletedAt sets the "user_workbench_deleted_at" field.
func (_u *SocialAccountUpdate) SetUserWorkbenchDeletedAt(v time.Time) *SocialAccountUpdate {
	_u.mutation.SetUserWorkbenchDeletedAt(v)
	return _u
}

// SetNillableUserWorkbenchDeletedAt sets the "user_workbench_deleted_at" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableUserWorkbenchDeletedAt(v *time.Time) *SocialAccountUpdate {
	if v != nil {
		_u.SetUserWorkbenchDeletedAt(*v)
	}
	return _u
}

// ClearUserWorkbenchDeletedAt clears the value of the "user_workbench_deleted_at" field.
func (_u *SocialAccountUpdate) ClearUserWorkbenchDeletedAt() *SocialAccountUpdate {
	_u.mutation.ClearUserWorkbenchDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *SocialAccountUpdate) SetRemark(v string) *SocialAccountUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *SocialAccountUpdate) SetNillableRemark(v *string) *SocialAccountUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *SocialAccountUpdate) ClearRemark() *SocialAccountUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetAssignedUser sets the "assigned_user" edge to the User entity.
func (_u *SocialAccountUpdate) SetAssignedUser(v *User) *SocialAccountUpdate {
	return _u.SetAssignedUserID(v.ID)
}

// AddTaskLogIDs adds the "task_logs" edge to the SocialTaskLog entity by IDs.
func (_u *SocialAccountUpdate) AddTaskLogIDs(ids ...int64) *SocialAccountUpdate {
	_u.mutation.AddTaskLogIDs(ids...)
	return _u
}

// AddTaskLogs adds the "task_logs" edges to the SocialTaskLog entity.
func (_u *SocialAccountUpdate) AddTaskLogs(v ...*SocialTaskLog) *SocialAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskLogIDs(ids...)
}

// Mutation returns the SocialAccountMutation object of the builder.
func (_u *SocialAccountUpdate) Mutation() *SocialAccountMutation {
	return _u.mutation
}

// ClearAssignedUser clears the "assigned_user" edge to the User entity.
func (_u *SocialAccountUpdate) ClearAssignedUser() *SocialAccountUpdate {
	_u.mutation.ClearAssignedUser()
	return _u
}

// ClearTaskLogs clears all "task_logs" edges to the SocialTaskLog entity.
func (_u *SocialAccountUpdate) ClearTaskLogs() *SocialAccountUpdate {
	_u.mutation.ClearTaskLogs()
	return _u
}

// RemoveTaskLogIDs removes the "task_logs" edge to SocialTaskLog entities by IDs.
func (_u *SocialAccountUpdate) RemoveTaskLogIDs(ids ...int64) *SocialAccountUpdate {
	_u.mutation.RemoveTaskLogIDs(ids...)
	return _u
}

// RemoveTaskLogs removes "task_logs" edges to SocialTaskLog entities.
func (_u *SocialAccountUpdate) RemoveTaskLogs(v ...*SocialTaskLog) *SocialAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SocialAccountUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SocialAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SocialAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SocialAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SocialAccountUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if socialaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized socialaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := socialaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SocialAccountUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := socialaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := socialaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformKey(); ok {
		if err := socialaccount.PlatformKeyValidator(v); err != nil {
			return &ValidationError{Name: "platform_key", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.platform_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameKey(); ok {
		if err := socialaccount.NameKeyValidator(v); err != nil {
			return &ValidationError{Name: "name_key", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.name_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdentityKind(); ok {
		if err := socialaccount.IdentityKindValidator(v); err != nil {
			return &ValidationError{Name: "identity_kind", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.identity_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdentityKey(); ok {
		if err := socialaccount.IdentityKeyValidator(v); err != nil {
			return &ValidationError{Name: "identity_key", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.identity_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformUserID(); ok {
		if err := socialaccount.PlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_user_id", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.platform_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := socialaccount.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := socialaccount.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := socialaccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmailPassword(); ok {
		if err := socialaccount.EmailPasswordValidator(v); err != nil {
			return &ValidationError{Name: "email_password", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.email_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TwoFactor(); ok {
		if err := socialaccount.TwoFactorValidator(v); err != nil {
			return &ValidationError{Name: "two_factor", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.two_factor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BackupCode(); ok {
		if err := socialaccount.BackupCodeValidator(v); err != nil {
			return &ValidationError{Name: "backup_code", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.backup_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmailClientID(); ok {
		if err := socialaccount.EmailClientIDValidator(v); err != nil {
			return &ValidationError{Name: "email_client_id", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.email_client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegistrationIP(); ok {
		if err := socialaccount.RegistrationIPValidator(v); err != nil {
			return &ValidationError{Name: "registration_ip", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.registration_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountStatus(); ok {
		if err := socialaccount.AccountStatusValidator(v); err != nil {
			return &ValidationError{Name: "account_status", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.account_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskStatus(); ok {
		if err := socialaccount.TaskStatusValidator(v); err != nil {
			return &ValidationError{Name: "task_status", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.task_status": %w`, err)}
		}
	}
	return nil
}

func (_u *SocialAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(socialaccount.Table, socialaccount.Columns, sqlgraph.NewFieldSpec(socialaccount.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(socialaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(socialaccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(socialaccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(socialaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(socialaccount.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformKey(); ok {
		_spec.SetField(socialaccount.FieldPlatformKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameKey(); ok {
		_spec.SetField(socialaccount.FieldNameKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdentityKind(); ok {
		_spec.SetField(socialaccount.FieldIdentityKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdentityKey(); ok {
		_spec.SetField(socialaccount.FieldIdentityKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformUserID(); ok {
		_spec.SetField(socialaccount.FieldPlatformUserID, field.TypeString, value)
	}
	if _u.mutation.PlatformUserIDCleared() {
		_spec.ClearField(socialaccount.FieldPlatformUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(socialaccount.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(socialaccount.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(socialaccount.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(socialaccount.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(socialaccount.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(socialaccount.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.EmailPassword(); ok {
		_spec.SetField(socialaccount.FieldEmailPassword, field.TypeString, value)
	}
	if _u.mutation.EmailPasswordCleared() {
		_spec.ClearField(socialaccount.FieldEmailPassword, field.TypeString)
	}
	if value, ok := _u.mutation.TwoFactor(); ok {
		_spec.SetField(socialaccount.FieldTwoFactor, field.TypeString, value)
	}
	if _u.mutation.TwoFactorCleared() {
		_spec.ClearField(socialaccount.FieldTwoFactor, field.TypeString)
	}
	if value, ok := _u.mutation.BackupCode(); ok {
		_spec.SetField(socialaccount.FieldBackupCode, field.TypeString, value)
	}
	if _u.mutation.BackupCodeCleared() {
		_spec.ClearField(socialaccount.FieldBackupCode, field.TypeString)
	}
	if value, ok := _u.mutation.EmailClientID(); ok {
		_spec.SetField(socialaccount.FieldEmailClientID, field.TypeString, value)
	}
	if _u.mutation.EmailClientIDCleared() {
		_spec.ClearField(socialaccount.FieldEmailClientID, field.TypeString)
	}
	if value, ok := _u.mutation.EmailToken(); ok {
		_spec.SetField(socialaccount.FieldEmailToken, field.TypeString, value)
	}
	if _u.mutation.EmailTokenCleared() {
		_spec.ClearField(socialaccount.FieldEmailToken, field.TypeString)
	}
	if value, ok := _u.mutation.RegistrationIP(); ok {
		_spec.SetField(socialaccount.FieldRegistrationIP, field.TypeString, value)
	}
	if _u.mutation.RegistrationIPCleared() {
		_spec.ClearField(socialaccount.FieldRegistrationIP, field.TypeString)
	}
	if value, ok := _u.mutation.AuthCookie(); ok {
		_spec.SetField(socialaccount.FieldAuthCookie, field.TypeString, value)
	}
	if _u.mutation.AuthCookieCleared() {
		_spec.ClearField(socialaccount.FieldAuthCookie, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutionAuth(); ok {
		_spec.SetField(socialaccount.FieldExecutionAuth, field.TypeString, value)
	}
	if _u.mutation.ExecutionAuthCleared() {
		_spec.ClearField(socialaccount.FieldExecutionAuth, field.TypeString)
	}
	if value, ok := _u.mutation.AccountStatus(); ok {
		_spec.SetField(socialaccount.FieldAccountStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskStatus(); ok {
		_spec.SetField(socialaccount.FieldTaskStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskMessage(); ok {
		_spec.SetField(socialaccount.FieldTaskMessage, field.TypeString, value)
	}
	if _u.mutation.TaskMessageCleared() {
		_spec.ClearField(socialaccount.FieldTaskMessage, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultProxySnapshot(); ok {
		_spec.SetField(socialaccount.FieldDefaultProxySnapshot, field.TypeString, value)
	}
	if _u.mutation.DefaultProxySnapshotCleared() {
		_spec.ClearField(socialaccount.FieldDefaultProxySnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.UserWorkbenchDeletedAt(); ok {
		_spec.SetField(socialaccount.FieldUserWorkbenchDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.UserWorkbenchDeletedAtCleared() {
		_spec.ClearField(socialaccount.FieldUserWorkbenchDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(socialaccount.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(socialaccount.FieldRemark, field.TypeString)
	}
	if _u.mutation.AssignedUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialaccount.AssignedUserTable,
			Columns: []string{socialaccount.AssignedUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialaccount.AssignedUserTable,
			Columns: []string{socialaccount.AssignedUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   socialaccount.TaskLogsTable,
			Columns: []string{socialaccount.TaskLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialtasklog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskLogsIDs(); len(nodes) > 0 && !_u.mutation.TaskLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   socialaccount.TaskLogsTable,
			Columns: []string{socialaccount.TaskLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialtasklog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   socialaccount.TaskLogsTable,
			Columns: []string{socialaccount.TaskLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialtasklog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{socialaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SocialAccountUpdateOne is the builder for updating a single SocialAccount entity.
type SocialAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SocialAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SocialAccountUpdateOne) SetUpdatedAt(v time.Time) *SocialAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SocialAccountUpdateOne) SetDeletedAt(v time.Time) *SocialAccountUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableDeletedAt(v *time.Time) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SocialAccountUpdateOne) ClearDeletedAt() *SocialAccountUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *SocialAccountUpdateOne) SetName(v string) *SocialAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableName(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *SocialAccountUpdateOne) SetPlatform(v string) *SocialAccountUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillablePlatform(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPlatformKey sets the "platform_key" field.
func (_u *SocialAccountUpdateOne) SetPlatformKey(v string) *SocialAccountUpdateOne {
	_u.mutation.SetPlatformKey(v)
	return _u
}

// SetNillablePlatformKey sets the "platform_key" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillablePlatformKey(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetPlatformKey(*v)
	}
	return _u
}

// SetNameKey sets the "name_key" field.
func (_u *SocialAccountUpdateOne) SetNameKey(v string) *SocialAccountUpdateOne {
	_u.mutation.SetNameKey(v)
	return _u
}

// SetNillableNameKey sets the "name_key" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableNameKey(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetNameKey(*v)
	}
	return _u
}

// SetIdentityKind sets the "identity_kind" field.
func (_u *SocialAccountUpdateOne) SetIdentityKind(v string) *SocialAccountUpdateOne {
	_u.mutation.SetIdentityKind(v)
	return _u
}

// SetNillableIdentityKind sets the "identity_kind" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableIdentityKind(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetIdentityKind(*v)
	}
	return _u
}

// SetIdentityKey sets the "identity_key" field.
func (_u *SocialAccountUpdateOne) SetIdentityKey(v string) *SocialAccountUpdateOne {
	_u.mutation.SetIdentityKey(v)
	return _u
}

// SetNillableIdentityKey sets the "identity_key" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableIdentityKey(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetIdentityKey(*v)
	}
	return _u
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_u *SocialAccountUpdateOne) SetPlatformUserID(v string) *SocialAccountUpdateOne {
	_u.mutation.SetPlatformUserID(v)
	return _u
}

// SetNillablePlatformUserID sets the "platform_user_id" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillablePlatformUserID(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetPlatformUserID(*v)
	}
	return _u
}

// ClearPlatformUserID clears the value of the "platform_user_id" field.
func (_u *SocialAccountUpdateOne) ClearPlatformUserID() *SocialAccountUpdateOne {
	_u.mutation.ClearPlatformUserID()
	return _u
}

// SetPassword sets the "password" field.
func (_u *SocialAccountUpdateOne) SetPassword(v string) *SocialAccountUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillablePassword(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *SocialAccountUpdateOne) ClearPassword() *SocialAccountUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *SocialAccountUpdateOne) SetPhone(v string) *SocialAccountUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillablePhone(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *SocialAccountUpdateOne) ClearPhone() *SocialAccountUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetEmail sets the "email" field.
func (_u *SocialAccountUpdateOne) SetEmail(v string) *SocialAccountUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableEmail(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *SocialAccountUpdateOne) ClearEmail() *SocialAccountUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetEmailPassword sets the "email_password" field.
func (_u *SocialAccountUpdateOne) SetEmailPassword(v string) *SocialAccountUpdateOne {
	_u.mutation.SetEmailPassword(v)
	return _u
}

// SetNillableEmailPassword sets the "email_password" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableEmailPassword(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetEmailPassword(*v)
	}
	return _u
}

// ClearEmailPassword clears the value of the "email_password" field.
func (_u *SocialAccountUpdateOne) ClearEmailPassword() *SocialAccountUpdateOne {
	_u.mutation.ClearEmailPassword()
	return _u
}

// SetTwoFactor sets the "two_factor" field.
func (_u *SocialAccountUpdateOne) SetTwoFactor(v string) *SocialAccountUpdateOne {
	_u.mutation.SetTwoFactor(v)
	return _u
}

// SetNillableTwoFactor sets the "two_factor" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableTwoFactor(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetTwoFactor(*v)
	}
	return _u
}

// ClearTwoFactor clears the value of the "two_factor" field.
func (_u *SocialAccountUpdateOne) ClearTwoFactor() *SocialAccountUpdateOne {
	_u.mutation.ClearTwoFactor()
	return _u
}

// SetBackupCode sets the "backup_code" field.
func (_u *SocialAccountUpdateOne) SetBackupCode(v string) *SocialAccountUpdateOne {
	_u.mutation.SetBackupCode(v)
	return _u
}

// SetNillableBackupCode sets the "backup_code" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableBackupCode(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetBackupCode(*v)
	}
	return _u
}

// ClearBackupCode clears the value of the "backup_code" field.
func (_u *SocialAccountUpdateOne) ClearBackupCode() *SocialAccountUpdateOne {
	_u.mutation.ClearBackupCode()
	return _u
}

// SetEmailClientID sets the "email_client_id" field.
func (_u *SocialAccountUpdateOne) SetEmailClientID(v string) *SocialAccountUpdateOne {
	_u.mutation.SetEmailClientID(v)
	return _u
}

// SetNillableEmailClientID sets the "email_client_id" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableEmailClientID(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetEmailClientID(*v)
	}
	return _u
}

// ClearEmailClientID clears the value of the "email_client_id" field.
func (_u *SocialAccountUpdateOne) ClearEmailClientID() *SocialAccountUpdateOne {
	_u.mutation.ClearEmailClientID()
	return _u
}

// SetEmailToken sets the "email_token" field.
func (_u *SocialAccountUpdateOne) SetEmailToken(v string) *SocialAccountUpdateOne {
	_u.mutation.SetEmailToken(v)
	return _u
}

// SetNillableEmailToken sets the "email_token" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableEmailToken(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetEmailToken(*v)
	}
	return _u
}

// ClearEmailToken clears the value of the "email_token" field.
func (_u *SocialAccountUpdateOne) ClearEmailToken() *SocialAccountUpdateOne {
	_u.mutation.ClearEmailToken()
	return _u
}

// SetRegistrationIP sets the "registration_ip" field.
func (_u *SocialAccountUpdateOne) SetRegistrationIP(v string) *SocialAccountUpdateOne {
	_u.mutation.SetRegistrationIP(v)
	return _u
}

// SetNillableRegistrationIP sets the "registration_ip" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableRegistrationIP(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetRegistrationIP(*v)
	}
	return _u
}

// ClearRegistrationIP clears the value of the "registration_ip" field.
func (_u *SocialAccountUpdateOne) ClearRegistrationIP() *SocialAccountUpdateOne {
	_u.mutation.ClearRegistrationIP()
	return _u
}

// SetAuthCookie sets the "auth_cookie" field.
func (_u *SocialAccountUpdateOne) SetAuthCookie(v string) *SocialAccountUpdateOne {
	_u.mutation.SetAuthCookie(v)
	return _u
}

// SetNillableAuthCookie sets the "auth_cookie" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableAuthCookie(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetAuthCookie(*v)
	}
	return _u
}

// ClearAuthCookie clears the value of the "auth_cookie" field.
func (_u *SocialAccountUpdateOne) ClearAuthCookie() *SocialAccountUpdateOne {
	_u.mutation.ClearAuthCookie()
	return _u
}

// SetExecutionAuth sets the "execution_auth" field.
func (_u *SocialAccountUpdateOne) SetExecutionAuth(v string) *SocialAccountUpdateOne {
	_u.mutation.SetExecutionAuth(v)
	return _u
}

// SetNillableExecutionAuth sets the "execution_auth" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableExecutionAuth(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetExecutionAuth(*v)
	}
	return _u
}

// ClearExecutionAuth clears the value of the "execution_auth" field.
func (_u *SocialAccountUpdateOne) ClearExecutionAuth() *SocialAccountUpdateOne {
	_u.mutation.ClearExecutionAuth()
	return _u
}

// SetAccountStatus sets the "account_status" field.
func (_u *SocialAccountUpdateOne) SetAccountStatus(v string) *SocialAccountUpdateOne {
	_u.mutation.SetAccountStatus(v)
	return _u
}

// SetNillableAccountStatus sets the "account_status" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableAccountStatus(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetAccountStatus(*v)
	}
	return _u
}

// SetTaskStatus sets the "task_status" field.
func (_u *SocialAccountUpdateOne) SetTaskStatus(v string) *SocialAccountUpdateOne {
	_u.mutation.SetTaskStatus(v)
	return _u
}

// SetNillableTaskStatus sets the "task_status" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableTaskStatus(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetTaskStatus(*v)
	}
	return _u
}

// SetTaskMessage sets the "task_message" field.
func (_u *SocialAccountUpdateOne) SetTaskMessage(v string) *SocialAccountUpdateOne {
	_u.mutation.SetTaskMessage(v)
	return _u
}

// SetNillableTaskMessage sets the "task_message" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableTaskMessage(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetTaskMessage(*v)
	}
	return _u
}

// ClearTaskMessage clears the value of the "task_message" field.
func (_u *SocialAccountUpdateOne) ClearTaskMessage() *SocialAccountUpdateOne {
	_u.mutation.ClearTaskMessage()
	return _u
}

// SetDefaultProxySnapshot sets the "default_proxy_snapshot" field.
func (_u *SocialAccountUpdateOne) SetDefaultProxySnapshot(v string) *SocialAccountUpdateOne {
	_u.mutation.SetDefaultProxySnapshot(v)
	return _u
}

// SetNillableDefaultProxySnapshot sets the "default_proxy_snapshot" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableDefaultProxySnapshot(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetDefaultProxySnapshot(*v)
	}
	return _u
}

// ClearDefaultProxySnapshot clears the value of the "default_proxy_snapshot" field.
func (_u *SocialAccountUpdateOne) ClearDefaultProxySnapshot() *SocialAccountUpdateOne {
	_u.mutation.ClearDefaultProxySnapshot()
	return _u
}

// SetAssignedUserID sets the "assigned_user_id" field.
func (_u *SocialAccountUpdateOne) SetAssignedUserID(v int64) *SocialAccountUpdateOne {
	_u.mutation.SetAssignedUserID(v)
	return _u
}

// SetNillableAssignedUserID sets the "assigned_user_id" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableAssignedUserID(v *int64) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetAssignedUserID(*v)
	}
	return _u
}

// ClearAssignedUserID clears the value of the "assigned_user_id" field.
func (_u *SocialAccountUpdateOne) ClearAssignedUserID() *SocialAccountUpdateOne {
	_u.mutation.ClearAssignedUserID()
	return _u
}

// SetUserWorkbenchDeletedAt sets the "user_workbench_deleted_at" field.
func (_u *SocialAccountUpdateOne) SetUserWorkbenchDeletedAt(v time.Time) *SocialAccountUpdateOne {
	_u.mutation.SetUserWorkbenchDeletedAt(v)
	return _u
}

// SetNillableUserWorkbenchDeletedAt sets the "user_workbench_deleted_at" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableUserWorkbenchDeletedAt(v *time.Time) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetUserWorkbenchDeletedAt(*v)
	}
	return _u
}

// ClearUserWorkbenchDeletedAt clears the value of the "user_workbench_deleted_at" field.
func (_u *SocialAccountUpdateOne) ClearUserWorkbenchDeletedAt() *SocialAccountUpdateOne {
	_u.mutation.ClearUserWorkbenchDeletedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *SocialAccountUpdateOne) SetRemark(v string) *SocialAccountUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *SocialAccountUpdateOne) SetNillableRemark(v *string) *SocialAccountUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *SocialAccountUpdateOne) ClearRemark() *SocialAccountUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetAssignedUser sets the "assigned_user" edge to the User entity.
func (_u *SocialAccountUpdateOne) SetAssignedUser(v *User) *SocialAccountUpdateOne {
	return _u.SetAssignedUserID(v.ID)
}

// AddTaskLogIDs adds the "task_logs" edge to the SocialTaskLog entity by IDs.
func (_u *SocialAccountUpdateOne) AddTaskLogIDs(ids ...int64) *SocialAccountUpdateOne {
	_u.mutation.AddTaskLogIDs(ids...)
	return _u
}

// AddTaskLogs adds the "task_logs" edges to the SocialTaskLog entity.
func (_u *SocialAccountUpdateOne) AddTaskLogs(v ...*SocialTaskLog) *SocialAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskLogIDs(ids...)
}

// Mutation returns the SocialAccountMutation object of the builder.
func (_u *SocialAccountUpdateOne) Mutation() *SocialAccountMutation {
	return _u.mutation
}

// ClearAssignedUser clears the "assigned_user" edge to the User entity.
func (_u *SocialAccountUpdateOne) ClearAssignedUser() *SocialAccountUpdateOne {
	_u.mutation.ClearAssignedUser()
	return _u
}

// ClearTaskLogs clears all "task_logs" edges to the SocialTaskLog entity.
func (_u *SocialAccountUpdateOne) ClearTaskLogs() *SocialAccountUpdateOne {
	_u.mutation.ClearTaskLogs()
	return _u
}

// RemoveTaskLogIDs removes the "task_logs" edge to SocialTaskLog entities by IDs.
func (_u *SocialAccountUpdateOne) RemoveTaskLogIDs(ids ...int64) *SocialAccountUpdateOne {
	_u.mutation.RemoveTaskLogIDs(ids...)
	return _u
}

// RemoveTaskLogs removes "task_logs" edges to SocialTaskLog entities.
func (_u *SocialAccountUpdateOne) RemoveTaskLogs(v ...*SocialTaskLog) *SocialAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskLogIDs(ids...)
}

// Where appends a list predicates to the SocialAccountUpdate builder.
func (_u *SocialAccountUpdateOne) Where(ps ...predicate.SocialAccount) *SocialAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SocialAccountUpdateOne) Select(field string, fields ...string) *SocialAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SocialAccount entity.
func (_u *SocialAccountUpdateOne) Save(ctx context.Context) (*SocialAccount, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SocialAccountUpdateOne) SaveX(ctx context.Context) *SocialAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SocialAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SocialAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SocialAccountUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if socialaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized socialaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := socialaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SocialAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := socialaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := socialaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformKey(); ok {
		if err := socialaccount.PlatformKeyValidator(v); err != nil {
			return &ValidationError{Name: "platform_key", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.platform_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameKey(); ok {
		if err := socialaccount.NameKeyValidator(v); err != nil {
			return &ValidationError{Name: "name_key", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.name_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdentityKind(); ok {
		if err := socialaccount.IdentityKindValidator(v); err != nil {
			return &ValidationError{Name: "identity_kind", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.identity_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdentityKey(); ok {
		if err := socialaccount.IdentityKeyValidator(v); err != nil {
			return &ValidationError{Name: "identity_key", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.identity_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformUserID(); ok {
		if err := socialaccount.PlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_user_id", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.platform_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := socialaccount.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := socialaccount.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := socialaccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmailPassword(); ok {
		if err := socialaccount.EmailPasswordValidator(v); err != nil {
			return &ValidationError{Name: "email_password", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.email_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TwoFactor(); ok {
		if err := socialaccount.TwoFactorValidator(v); err != nil {
			return &ValidationError{Name: "two_factor", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.two_factor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BackupCode(); ok {
		if err := socialaccount.BackupCodeValidator(v); err != nil {
			return &ValidationError{Name: "backup_code", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.backup_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmailClientID(); ok {
		if err := socialaccount.EmailClientIDValidator(v); err != nil {
			return &ValidationError{Name: "email_client_id", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.email_client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegistrationIP(); ok {
		if err := socialaccount.RegistrationIPValidator(v); err != nil {
			return &ValidationError{Name: "registration_ip", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.registration_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountStatus(); ok {
		if err := socialaccount.AccountStatusValidator(v); err != nil {
			return &ValidationError{Name: "account_status", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.account_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskStatus(); ok {
		if err := socialaccount.TaskStatusValidator(v); err != nil {
			return &ValidationError{Name: "task_status", err: fmt.Errorf(`ent: validator failed for field "SocialAccount.task_status": %w`, err)}
		}
	}
	return nil
}

func (_u *SocialAccountUpdateOne) sqlSave(ctx context.Context) (_node *SocialAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(socialaccount.Table, socialaccount.Columns, sqlgraph.NewFieldSpec(socialaccount.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SocialAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, socialaccount.FieldID)
		for _, f := range fields {
			if !socialaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != socialaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(socialaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(socialaccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(socialaccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(socialaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(socialaccount.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformKey(); ok {
		_spec.SetField(socialaccount.FieldPlatformKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameKey(); ok {
		_spec.SetField(socialaccount.FieldNameKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdentityKind(); ok {
		_spec.SetField(socialaccount.FieldIdentityKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdentityKey(); ok {
		_spec.SetField(socialaccount.FieldIdentityKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformUserID(); ok {
		_spec.SetField(socialaccount.FieldPlatformUserID, field.TypeString, value)
	}
	if _u.mutation.PlatformUserIDCleared() {
		_spec.ClearField(socialaccount.FieldPlatformUserID, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(socialaccount.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(socialaccount.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(socialaccount.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(socialaccount.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(socialaccount.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(socialaccount.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.EmailPassword(); ok {
		_spec.SetField(socialaccount.FieldEmailPassword, field.TypeString, value)
	}
	if _u.mutation.EmailPasswordCleared() {
		_spec.ClearField(socialaccount.FieldEmailPassword, field.TypeString)
	}
	if value, ok := _u.mutation.TwoFactor(); ok {
		_spec.SetField(socialaccount.FieldTwoFactor, field.TypeString, value)
	}
	if _u.mutation.TwoFactorCleared() {
		_spec.ClearField(socialaccount.FieldTwoFactor, field.TypeString)
	}
	if value, ok := _u.mutation.BackupCode(); ok {
		_spec.SetField(socialaccount.FieldBackupCode, field.TypeString, value)
	}
	if _u.mutation.BackupCodeCleared() {
		_spec.ClearField(socialaccount.FieldBackupCode, field.TypeString)
	}
	if value, ok := _u.mutation.EmailClientID(); ok {
		_spec.SetField(socialaccount.FieldEmailClientID, field.TypeString, value)
	}
	if _u.mutation.EmailClientIDCleared() {
		_spec.ClearField(socialaccount.FieldEmailClientID, field.TypeString)
	}
	if value, ok := _u.mutation.EmailToken(); ok {
		_spec.SetField(socialaccount.FieldEmailToken, field.TypeString, value)
	}
	if _u.mutation.EmailTokenCleared() {
		_spec.ClearField(socialaccount.FieldEmailToken, field.TypeString)
	}
	if value, ok := _u.mutation.RegistrationIP(); ok {
		_spec.SetField(socialaccount.FieldRegistrationIP, field.TypeString, value)
	}
	if _u.mutation.RegistrationIPCleared() {
		_spec.ClearField(socialaccount.FieldRegistrationIP, field.TypeString)
	}
	if value, ok := _u.mutation.AuthCookie(); ok {
		_spec.SetField(socialaccount.FieldAuthCookie, field.TypeString, value)
	}
	if _u.mutation.AuthCookieCleared() {
		_spec.ClearField(socialaccount.FieldAuthCookie, field.TypeString)
	}
	if value, ok := _u.mutation.ExecutionAuth(); ok {
		_spec.SetField(socialaccount.FieldExecutionAuth, field.TypeString, value)
	}
	if _u.mutation.ExecutionAuthCleared() {
		_spec.ClearField(socialaccount.FieldExecutionAuth, field.TypeString)
	}
	if value, ok := _u.mutation.AccountStatus(); ok {
		_spec.SetField(socialaccount.FieldAccountStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskStatus(); ok {
		_spec.SetField(socialaccount.FieldTaskStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskMessage(); ok {
		_spec.SetField(socialaccount.FieldTaskMessage, field.TypeString, value)
	}
	if _u.mutation.TaskMessageCleared() {
		_spec.ClearField(socialaccount.FieldTaskMessage, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultProxySnapshot(); ok {
		_spec.SetField(socialaccount.FieldDefaultProxySnapshot, field.TypeString, value)
	}
	if _u.mutation.DefaultProxySnapshotCleared() {
		_spec.ClearField(socialaccount.FieldDefaultProxySnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.UserWorkbenchDeletedAt(); ok {
		_spec.SetField(socialaccount.FieldUserWorkbenchDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.UserWorkbenchDeletedAtCleared() {
		_spec.ClearField(socialaccount.FieldUserWorkbenchDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(socialaccount.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(socialaccount.FieldRemark, field.TypeString)
	}
	if _u.mutation.AssignedUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialaccount.AssignedUserTable,
			Columns: []string{socialaccount.AssignedUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialaccount.AssignedUserTable,
			Columns: []string{socialaccount.AssignedUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   socialaccount.TaskLogsTable,
			Columns: []string{socialaccount.TaskLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialtasklog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskLogsIDs(); len(nodes) > 0 && !_u.mutation.TaskLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   socialaccount.TaskLogsTable,
			Columns: []string{socialaccount.TaskLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialtasklog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   socialaccount.TaskLogsTable,
			Columns: []string{socialaccount.TaskLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialtasklog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SocialAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{socialaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
