import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const sourcePath = resolve(__dirname, '../TotalAccountsView.vue')
const source = readFileSync(sourcePath, 'utf8')
const credentialPreviewComposablePath = resolve(__dirname, '../../../composables/useSocialAccountCredentialPreview.ts')
const credentialPreviewComposableSource = readFileSync(credentialPreviewComposablePath, 'utf8')
const credentialCopyComposablePath = resolve(__dirname, '../../../composables/useSocialAccountCredentialCopy.ts')
const credentialCopyComposableSource = readFileSync(credentialCopyComposablePath, 'utf8')
const editPayloadUtilPath = resolve(__dirname, '../../../utils/accountWorkbenchEditPayload.ts')
const editPayloadUtilSource = readFileSync(editPayloadUtilPath, 'utf8')
const accountStatusUtilPath = resolve(__dirname, '../../../utils/accountWorkbenchStatus.ts')
const accountStatusUtilSource = readFileSync(accountStatusUtilPath, 'utf8')
const accountDateUtilPath = resolve(__dirname, '../../../utils/accountWorkbenchDate.ts')
const accountDateUtilSource = readFileSync(accountDateUtilPath, 'utf8')
const taskMessagePanelPath = resolve(__dirname, '../../../components/accounts/SocialAccountTaskMessagePanel.vue')
const taskMessagePanelSource = readFileSync(taskMessagePanelPath, 'utf8')
const operationResultsPath = resolve(__dirname, '../totalAccountOperationResults.ts')
const operationResultsSource = readFileSync(operationResultsPath, 'utf8')
const totalAccountErrorMessagesPath = resolve(__dirname, '../totalAccountErrorMessages.ts')
const totalAccountErrorMessagesSource = readFileSync(totalAccountErrorMessagesPath, 'utf8')
const totalAccountActionTitlesPath = resolve(__dirname, '../totalAccountActionTitles.ts')
const totalAccountActionTitlesSource = readFileSync(totalAccountActionTitlesPath, 'utf8')
const enLocalePath = resolve(__dirname, '../../../i18n/locales/en.ts')
const enLocaleSource = readFileSync(enLocalePath, 'utf8')
const zhLocalePath = resolve(__dirname, '../../../i18n/locales/zh.ts')
const zhLocaleSource = readFileSync(zhLocalePath, 'utf8')

function extractFunctionSource(sourceText: string, signature: string) {
  const start = sourceText.indexOf(signature)
  expect(start).toBeGreaterThanOrEqual(0)
  const bodyStart = sourceText.indexOf('{', start)
  expect(bodyStart).toBeGreaterThanOrEqual(start)
  let depth = 0
  for (let index = bodyStart; index < sourceText.length; index += 1) {
    const char = sourceText[index]
    if (char === '{') depth += 1
    if (char === '}') {
      depth -= 1
      if (depth === 0) return sourceText.slice(start, index + 1)
    }
  }
  throw new Error(`Unable to extract function source for ${signature}`)
}

describe('admin TotalAccountsView total account pool contract', () => {
  it('uses the shared social account stats grid without changing stat test ids', () => {
    const statsGridPath = resolve(__dirname, '../../../components/accounts/SocialAccountStatsGrid.vue')
    const statsGridSource = readFileSync(statsGridPath, 'utf8')

    expect(source).toContain("import LoadErrorBanner from '@/components/common/LoadErrorBanner.vue'")
    expect(source).toContain("import SocialAccountStatsGrid from '@/components/accounts/SocialAccountStatsGrid.vue'")
    expect(source).toContain('<LoadErrorBanner')
    expect(source).toContain('v-if="loadError"')
    expect(source).toContain(":title=\"t('admin.socialAccountWorkbench.failedToLoad')\"")
    expect(source).toContain(':message="loadError"')
    expect(source).toContain(":retry-label=\"t('common.retry')\"")
    expect(source).toContain('@retry="loadAccounts"')
    expect(source).toContain('<SocialAccountStatsGrid')
    expect(source).toContain('test-id-prefix="total-account-stat"')
    expect(source).toContain('grid-class="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"')
    expect(statsGridSource).toContain("import CommonStatsGrid")
    expect(statsGridSource).toContain('testId: `${props.testIdPrefix}-${stat.key}`')
    expect(statsGridSource).toContain('<CommonStatsGrid')
    expect(statsGridSource).not.toContain('defineEmits')
    expect(statsGridSource).not.toContain('<button')
  })

  it('does not duplicate the AppHeader page title inside the content area', () => {
    expect(source).not.toContain("<h1 class=\"text-2xl font-bold text-gray-900 dark:text-white\">{{ t('admin.totalAccounts.title') }}</h1>")
    expect(source).not.toContain("{{ t('admin.totalAccounts.description') }}")
  })

  it('keeps total account pool governance actions visible in a unified toolbar', () => {
    expect(source).toContain('data-testid="total-accounts-toolbar"')
    expect(source).toContain("t('admin.socialAccountWorkbench.actions.assign')")
    expect(source).toContain("t('admin.socialAccountWorkbench.actions.reclaim')")
    expect(source).toContain("t('admin.socialAccountWorkbench.actions.delete')")
    expect(source).not.toContain("t('admin.socialAccountWorkbench.toolbar.createAccount')")
    expect(source).not.toContain('@click="openCreateDialog"')
    expect(source).not.toContain('const createDialogOpen = ref(false)')
    expect(source).not.toContain('const creatingAccount = ref(false)')
    expect(source).toContain(':disabled="loading || !canAssignSelected || assigning"')
    expect(source).toContain(':disabled="loading || !canReclaimSelected || reclaiming"')
    expect(source).toContain(':disabled="loading || !hasSelection || deleting"')
    expect(source).not.toContain(':title="createAccountToolbarTitle"')
    expect(source).not.toContain(':aria-label="createAccountToolbarTitle"')
    expect(source).toContain(':title="refreshAccountsButtonTitle"')
    expect(source).toContain(':aria-label="refreshAccountsButtonTitle"')
    expect(source).toContain(':title="importAccountsButtonTitle"')
    expect(source).toContain(':aria-label="importAccountsButtonTitle"')
    expect(source).toContain(':title="exportAccountsButtonTitle"')
    expect(source).toContain(':aria-label="exportAccountsButtonTitle"')
    expect(source).toContain(':title="rowDetailButtonTitle"')
    expect(source).toContain(':aria-label="rowDetailButtonTitle"')
    expect(source).toContain(':title="rowEditButtonTitle"')
    expect(source).toContain(':aria-label="rowEditButtonTitle"')
    expect(source).toContain(':title="clearSelectionButtonTitle"')
    expect(source).toContain(':aria-label="clearSelectionButtonTitle"')
    expect(source).toContain(':title="assignSelectedButtonTitle"')
    expect(source).toContain(':aria-label="assignSelectedButtonTitle"')
    expect(source).toContain(':title="assignBackButtonTitle"')
    expect(source).toContain(':aria-label="assignBackButtonTitle"')
    expect(source).toContain(':title="assignConfirmButtonTitle"')
    expect(source).toContain(':title="assignReviewButtonTitle"')
    expect(source).toContain(':aria-label="assignReviewButtonTitle"')
    expect(source).toContain(':title="reclaimSelectedButtonTitle"')
    expect(source).toContain(':aria-label="reclaimSelectedButtonTitle"')
    expect(source).toContain(':title="deleteSelectedButtonTitle"')
    expect(source).toContain(':aria-label="deleteSelectedButtonTitle"')
    expect(source).toContain(':aria-label="assignDialogCancelButtonTitle"')
    expect(source).toContain(':title="assignDialogCancelButtonTitle"')
    expect(source).toContain(':aria-label="reclaimDialogCancelButtonTitle"')
    expect(source).toContain(':title="reclaimDialogCancelButtonTitle"')
    expect(source).toContain(':title="reclaimConfirmButtonTitle"')
    expect(source).toContain(':aria-label="deleteDialogCancelButtonTitle"')
    expect(source).toContain(':title="deleteDialogCancelButtonTitle"')
    expect(source).toContain(':title="deleteConfirmButtonTitle"')
    expect(source).toContain("from './totalAccountActionTitles'")
    expect(source).not.toContain('const createAccountToolbarTitle = computed(() => buildCreateAccountToolbarTitle')
    expect(source).toContain('const rowDetailButtonTitle = computed(() => buildRowDetailButtonTitle')
    expect(source).toContain('const rowEditButtonTitle = computed(() => buildRowEditButtonTitle')
    expect(source).toContain('const assignSelectedButtonTitle = computed(() => buildAssignSelectedButtonTitle')
    expect(source).toContain('const assignDialogCancelButtonTitle = computed(() => buildDialogCancelButtonTitle')
    expect(source).toContain('const assignBackButtonTitle = computed(() => buildAssignBackButtonTitle')
    expect(source).toContain('const assignConfirmButtonTitle = computed(() => buildAssignConfirmButtonTitle')
    expect(source).toContain('const assignReviewButtonTitle = computed(() => buildAssignReviewButtonTitle')
    expect(source).toContain('hasTargetUser: Boolean(targetUser.value)')
    expect(source).toContain('const reclaimDialogCancelButtonTitle = computed(() => buildDialogCancelButtonTitle')
    expect(source).toContain('const reclaimConfirmButtonTitle = computed(() => buildReclaimConfirmButtonTitle')
    expect(source).toContain('const deleteDialogCancelButtonTitle = computed(() => buildDialogCancelButtonTitle')
    expect(source).toContain('const deleteConfirmButtonTitle = computed(() => buildDeleteConfirmButtonTitle')
    expect(totalAccountActionTitlesSource).toContain("const selectionRequiredKey = 'admin.socialAccountWorkbench.executionBar.selectionRequired'")
    expect(totalAccountActionTitlesSource).toContain('export function totalAccountAssignBackButtonTitle')
    expect(totalAccountActionTitlesSource).toContain('export function totalAccountAssignConfirmButtonTitle')
    expect(totalAccountActionTitlesSource).toContain('export function totalAccountAssignReviewButtonTitle')
    expect(totalAccountActionTitlesSource).not.toContain('export function totalAccountCreateToolbarTitle')
    expect(totalAccountActionTitlesSource).toContain('export function totalAccountReclaimConfirmButtonTitle')
    expect(totalAccountActionTitlesSource).toContain('export function totalAccountDeleteConfirmButtonTitle')
    expect(totalAccountActionTitlesSource).toContain('if (!state.hasSelection) return t(selectionRequiredKey)')
    expect(totalAccountActionTitlesSource).toContain("if (!state.hasTargetUser) return t('admin.socialAccountWorkbench.toasts.selectTargetUser')")
    expect(totalAccountActionTitlesSource).toContain("t('admin.socialAccountWorkbench.toasts.assignRequiresUnassigned', { count: state.selectedAssignedCount })")
    expect(totalAccountActionTitlesSource).toContain("if (!state.canReclaim) return t('admin.socialAccountWorkbench.executionBar.noAssignedSelection')")
    expect(enLocaleSource).toContain('"selectionRequired": "Select at least one account first."')
    expect(enLocaleSource).toContain('"noAssignedSelection": "Select at least one assigned account to return to the pool."')
    expect(zhLocaleSource).toContain('"selectionRequired": "请至少选择一个账号。"')
    expect(zhLocaleSource).toContain('"noAssignedSelection": "请至少选择一个已分配账号后再回收。"')
    expect(source).toContain('@click="openAssignDialog"')
    expect(source).toContain('@click="openReclaimDialog"')
    expect(source).toContain('@click="openDeleteDialog"')
    expect(source).toContain('const assignConfirmDialogOpen = ref(false)')
    expect(source).toContain('const reclaimDialogOpen = ref(false)')
    expect(source).toContain('class="flex flex-col gap-2 2xl:flex-row 2xl:items-center"')
    expect(source).toContain('class="flex w-full shrink-0 flex-col gap-2 sm:flex-row xl:ml-auto xl:w-auto xl:items-center 2xl:ml-2"')
    expect(source).not.toContain('flex flex-col gap-2 xl:flex-row xl:items-center')
    expect(source).not.toContain('v-if="selectedIds.length > 0" class="flex flex-col gap-3 rounded-lg')
  })

  it('maps total account service availability errors to localized safe messages', () => {
    expect(source).toContain("import { createTotalAccountErrorMessages } from './totalAccountErrorMessages'")
    expect(source).toContain('const totalAccountErrorMessages = computed(() => createTotalAccountErrorMessages(t))')
    expect(source).toContain('extractSafeApiErrorMessage(error, t(')
    expect(totalAccountErrorMessagesSource).toContain('SOCIAL_ACCOUNT_SERVICE_UNAVAILABLE')
    expect(totalAccountErrorMessagesSource).toContain("t('admin.socialAccountWorkbench.errors.SOCIAL_ACCOUNT_SERVICE_UNAVAILABLE')")
    expect(totalAccountErrorMessagesSource).toContain('SOCIAL_ACCOUNT_EXECUTION_AUTH_INVALID')
    expect(totalAccountErrorMessagesSource).toContain('USER_NOT_FOUND')
    expect(enLocaleSource).toContain('"SOCIAL_ACCOUNT_SERVICE_UNAVAILABLE": "Account service is temporarily unavailable. Try again later."')
    expect(zhLocaleSource).toContain('"SOCIAL_ACCOUNT_SERVICE_UNAVAILABLE": "账号服务暂不可用，请稍后重试。"')
  })

  it('uses shared selection helpers for selected total-account rows', () => {
    expect(source).toContain('selectedRowsById,')
    expect(source).toContain('const selectedAccounts = computed(() => selectedRowsById(accounts.value, selectedIds.value))')
    expect(source).not.toContain('accounts.value.filter(account => selectedIds.value.includes(account.id))')
  })

  it('keeps the total account table visually continuous without folded sticky edge columns', () => {
    expect(source).toContain(':sticky-first-column="false"')
    expect(source).toContain(':sticky-actions-column="true"')
    expect(source).toContain('class="total-accounts-table"')
    expect(source).toContain('.total-accounts-table :deep(.sticky-col-right::before)')
    expect(source).toContain("class: 'w-[56px] min-w-[56px] text-center'")
    expect(source).toContain("class: 'w-[128px] min-w-[128px]'")
  })

  it('keeps total account mobile card cells fluid while preserving desktop table widths', () => {
    expect(source).toContain('class="flex w-full min-w-0 max-w-full items-center gap-3 text-left disabled:cursor-not-allowed disabled:opacity-60 md:min-w-[220px] md:max-w-[260px]"')
    expect(source).toContain('class="block w-full max-w-full truncate text-sm text-gray-700 dark:text-gray-300 md:w-[200px]"')
    expect(source).toContain('class="block w-full max-w-full truncate text-sm text-gray-700 dark:text-gray-300 md:w-[220px]"')
    expect(source).not.toContain('class="flex min-w-[220px] max-w-[260px] items-center gap-3 text-left')
    expect(source).not.toContain('class="block w-[200px] truncate text-sm text-gray-700 dark:text-gray-300"')
    expect(source).not.toContain('class="block w-[220px] truncate text-sm text-gray-700 dark:text-gray-300"')
  })

  it('keeps assign, reclaim, and delete behind final confirmation dialogs', () => {
    const openAssignSource = source.slice(
      source.indexOf('function openAssignDialog'),
      source.indexOf('function closeAssignDialog'),
    )
    const openAssignConfirmSource = source.slice(
      source.indexOf('function openAssignConfirmDialog'),
      source.indexOf('async function confirmAssignDialog'),
    )
    const openReclaimSource = source.slice(
      source.indexOf('function openReclaimDialog'),
      source.indexOf('async function reclaimSelectedAccounts'),
    )
    const openDeleteSource = source.slice(
      source.indexOf('function openDeleteDialog'),
      source.indexOf('async function confirmDeleteDialog'),
    )

    expect(source).toContain('@click="openAssignConfirmDialog"')
    expect(source).toContain('@click="confirmAssignDialog"')
    expect(source).toContain('@click="reclaimSelectedAccounts"')
    expect(source).toContain('@click="confirmDeleteDialog"')
    expect(source).toContain(':disabled="loading || !targetUser || !canAssignSelected || assigning"')
    expect(source).toContain(':disabled="loading || !canReclaimSelected || reclaiming"')
    expect(source).toContain(':disabled="loading || !hasSelection || deleting"')
    expect(source).toContain("t('admin.socialAccountWorkbench.assignDialog.confirmTitle')")
    expect(source).toContain("t('admin.socialAccountWorkbench.reclaimDialog.title')")
    expect(source).toContain("t('admin.socialAccountWorkbench.deleteDialog.impactHint')")
    expect(openAssignSource).toContain('if (loading.value || assigning.value || !hasSelection.value) return')
    expect(openAssignConfirmSource).not.toContain('adminAPI.totalAccounts.assign')
    expect(openReclaimSource).not.toContain('adminAPI.totalAccounts.reclaim')
    expect(openDeleteSource).not.toContain('adminAPI.accountWorkbench.batchDelete')
    expect(openReclaimSource).toContain('if (loading.value || reclaiming.value) return')
    expect(openDeleteSource).toContain('if (loading.value || deleting.value) return')
    expect(source).toContain('if (loading.value || assigning.value || !canAssignSelected.value) return')
    expect(source).toContain('if (loading.value || reclaiming.value || !canReclaimSelected.value) return')
    expect(source).toContain('if (loading.value || deleting.value || !hasSelection.value) return')
  })

  it('preserves existing total account pool API paths and action restrictions', () => {
    expect(source).toContain('adminAPI.totalAccounts.list')
    expect(source).toContain('const accountFilterParams = computed')
    expect(source).toContain('const accountListParams = computed')
    expect(source).toContain('adminAPI.totalAccounts.list(accountListParams.value)')
    expect(source).toContain('const exportAccountParams = computed<TotalAccountExportParams>')
    expect(source).toContain("selectedIds.value.length > 0 ? { account_ids: [...selectedIds.value] } : {}")
    expect(source).toContain('adminAPI.totalAccounts.exportAccounts(exportAccountParams.value)')
    expect(source).toContain("if (search) params.search = search")
    expect(source).toContain("if (accountStatusFilter.value !== 'all') params.account_status = accountStatusFilter.value")
    expect(source).toContain("if (assignmentFilter.value === 'assigned') params.assigned = true")
    expect(source).toContain("if (assignmentFilter.value === 'unassigned') params.unassigned = true")
    expect(source).toContain('watch([searchQuery, accountStatusFilter, assignmentFilter]')
    expect(source).toContain('adminAPI.totalAccounts.batchAssign')
    expect(source).toContain('adminAPI.totalAccounts.batchReclaim')
    expect(source).toContain('adminAPI.totalAccounts.batchDelete')
    expect(source).not.toContain('adminAPI.totalAccounts.create')
    expect(source).toContain('adminAPI.totalAccounts.exportAccounts')
    expect(source).toContain('adminAPI.totalAccounts.importAccounts')
    expect(source).toContain('adminAPI.totalAccounts.update')
    expect(source).toContain(':disabled="loading || importingAccounts"')
    expect(source).toContain('if (loading.value || importingAccounts.value) return')
    expect(source).toContain(':disabled="loading || exportingAccounts"')
    expect(source).toContain('if (loading.value || exportingAccounts.value) return')
    expect(source).not.toContain('adminAPI.accountWorkbench.importAccounts')
    expect(source).not.toContain('adminAPI.accountWorkbench.update')
    expect(source).toContain('accountWorkbenchImportResultStatusLabel')
    expect(source).toContain('accountWorkbenchImportResultItemMessage')
    expect(source).toContain(':status-label="importOperationStatusLabel"')
    expect(source).toContain(':item-message="importOperationItemMessage"')
    expect(source).toContain('assignRequiresUnassigned')
    expect(source).not.toContain('adminAPI.accountWorkbench.list')
  })

  it('uses shared account status normalization while preserving total-pool status behavior', () => {
    expect(source).toContain("import {\n  normalizeKnownWorkbenchAccountStatus,\n  normalizeWorkbenchTaskStatus,\n  totalPoolAccountStatusBadgeClass,\n  type WorkbenchAccountStatus,\n} from '@/utils/accountWorkbenchStatus'")
    expect(source).toContain('type AccountStatus = WorkbenchAccountStatus')
    expect(source).toContain('accountStatus: normalizeKnownWorkbenchAccountStatus(account.account_status)')
    expect(source).toContain("['badge', totalPoolAccountStatusBadgeClass(String(value))]")
    expect(source).not.toContain('function toAccountStatus')
    expect(source).not.toContain('function accountStatusBadgeClass')
    expect(accountStatusUtilSource).toContain('export const WORKBENCH_ACCOUNT_STATUSES')
    expect(accountStatusUtilSource).toContain('export function normalizeKnownWorkbenchAccountStatus')
    expect(accountStatusUtilSource).toContain('export function totalPoolAccountStatusBadgeClass')
  })

  it('uses normalized task status to tone total-pool task messages', () => {
    expect(source).toContain("import { socialAccountTaskStatusFromAccountSnapshot } from '@/utils/socialAccountTaskStatus'")
    expect(source).toContain('taskStatus: socialAccountTaskStatusFromAccountSnapshot(normalizeWorkbenchTaskStatus(account.task_status), taskMessage)')
    expect(source).toContain("import SocialAccountTaskMessagePanel from '@/components/accounts/SocialAccountTaskMessagePanel.vue'")
    expect(source).toContain('<SocialAccountTaskMessagePanel')
    expect(source).toContain(':status="selectedAccount.taskStatus"')
    expect(taskMessagePanelSource).toContain('workbenchTaskMessagePanelClass(status)')
    expect(source).not.toContain('resultMessagePanelClass(selectedAccount.accountStatus)')
    expect(source).not.toContain('function resultMessagePanelClass')
    expect(accountStatusUtilSource).toContain('export function normalizeWorkbenchTaskStatus')
    expect(accountStatusUtilSource).toContain('export function workbenchTaskMessagePanelClass')
  })

  it('uses the shared account workbench date formatter for total-pool detail dates', () => {
    expect(source).toContain("import { formatAccountWorkbenchDate } from '@/utils/accountWorkbenchDate'")
    expect(source).toContain('createdAt: formatAccountWorkbenchDate(account.created_at)')
    expect(source).not.toContain('createdAt: new Date(account.created_at).toLocaleString()')
    expect(accountDateUtilSource).toContain('export function formatAccountWorkbenchDate')
    expect(accountDateUtilSource).toContain("return '-'")
  })

  it('does not expose account intake source in the total account pool', () => {
    expect(source).not.toContain('type Source')
    expect(source).not.toContain('source:')
    expect(source).not.toContain('toSource')
    expect(source).not.toContain('account.source')
    expect(source).not.toContain('columns.source')
    expect(source).not.toContain('sources.')
  })

  it('keeps account delivery previews aligned with accounts while omitting the table credential column', () => {
    expect(source).not.toContain('#cell-credentials')
    expect(source).not.toContain("key: 'credentials'")
    expect(source).not.toContain('admin.socialAccountWorkbench.columns.credentials')
    expect(source).not.toContain('{{ row.password || \'-\' }}')
    expect(source).not.toContain('{{ row.emailPassword || \'-\' }}')
    expect(source).not.toContain('{{ row.authCookie || \'-\' }}')
    expect(source).not.toContain('{{ row.executionAuth || \'-\' }}')
    expect(source).toContain('buildDeliveryCredentialItems(selectedAccount.value')
    expect(source).toContain('SocialAccountCredentialPreviewPanel')
    expect(source).toContain('test-id-prefix="total-account"')
    expect(source).toContain("emailTokenTestId: 'total-account-email-token-preview'")
    expect(source).toContain("emailTokenCopyTestId: 'total-account-email-token-copy'")
    expect(source).toContain('buildCredentialPreviews(selectedAccount.value)')
    expect(credentialPreviewComposableSource).toContain('value: account.password')
    expect(credentialPreviewComposableSource).toContain('value: account.emailPassword')
    expect(credentialPreviewComposableSource).toContain('value: credentialCharacterCountText(emailToken)')
    expect(credentialPreviewComposableSource).toContain("buildCredentialPreview('authCookie', account.authCookie)")
    expect(credentialPreviewComposableSource).toContain("buildCredentialPreview('executionAuth', account.executionAuth, account.authCookie)")
    expect(source).toContain("import { useSocialAccountCredentialCopy } from '@/composables/useSocialAccountCredentialCopy'")
    expect(source).toContain("credentialDiagnosticContext: 'admin.total_accounts.copy_credential'")
    expect(source).toContain("emailTokenDiagnosticContext: 'admin.total_accounts.copy_email_token'")
    expect(source).toContain('await copySelectedAccountCredential(key)')
    expect(source).toContain('await copySelectedAccountEmailToken()')
    expect(credentialCopyComposableSource).toContain("key === 'authCookie' ? account.authCookie : account.executionAuth")
    expect(credentialCopyComposableSource).toContain("options.getAccount()?.emailToken ?? ''")
    expect(credentialCopyComposableSource).toContain('await copyTextToClipboard(value)')
    expect(source).not.toContain('value: selectedAccount.value.authCookie')
    expect(source).not.toContain('value: selectedAccount.value.executionAuth')
    expect(source).not.toContain('show-execution-auth-refresh')
    expect(source).toContain('value: selectedAccount.value.defaultProxySnapshot')
    expect(source).toContain('value: selectedAccount.value.remark')
    expect(source).toContain("item.value || '-'")
    expect(source).not.toContain('maskedCredentialLabel(row.password)')
    expect(source).not.toContain('maskedCredentialLabel(row.emailPassword)')
    expect(source).not.toContain('maskedCredentialLabel(selectedAccount.value.password)')
    expect(source).not.toContain('maskedCredentialLabel(selectedAccount.value.emailPassword)')
    expect(source).not.toContain('defaultProxyLabel(row.defaultProxySnapshot)')
    expect(source).not.toContain('defaultProxyLabel(selectedAccount.value.defaultProxySnapshot)')
  })

  it('keeps raw account delivery fields editable and searchable from the list', () => {
    const filteredAccountsSource = source.slice(
      source.indexOf('const filteredAccounts = computed'),
      source.indexOf('const stats = computed'),
    )

    expect(source).toContain('accountForm.password = row.password')
    expect(source).toContain('accountForm.emailPassword = row.emailPassword')
    expect(source).toContain('accountForm.authCookie = row.authCookie')
    expect(source).toContain('accountForm.executionAuth = row.executionAuth')
    expect(filteredAccountsSource).toContain('account.password')
    expect(filteredAccountsSource).toContain('account.emailPassword')
    expect(filteredAccountsSource).toContain('account.authCookie')
    expect(filteredAccountsSource).not.toContain('account.executionAuth')
    expect(source).toContain('authCookie: account.auth_cookie ??')
  })

  it('does not keep a manual total account create path in the pool page', () => {
    expect(source).not.toContain('<BaseDialog :show="createDialogOpen"')
    expect(source).not.toContain('data-testid="total-account-create-form"')
    expect(source).not.toContain('function openCreateDialog')
    expect(source).not.toContain('async function submitCreateDialog')
    expect(source).not.toContain('createAccountForm')
    expect(source).not.toContain('validateTotalAccountCreateForm')
    expect(source).not.toContain('buildTotalAccountCreatePayload')
    expect(totalAccountActionTitlesSource).not.toContain('export function totalAccountCreateSubmitButtonTitle')
    expect(editPayloadUtilSource).not.toContain('export function buildTotalAccountCreatePayload')
    expect(editPayloadUtilSource).not.toContain('export function validateTotalAccountCreateForm')
  })

  it('submits empty delivery field edits instead of omitting them', () => {
    const submitSource = source.slice(
      source.indexOf('async function submitEditDialog'),
      source.indexOf('function triggerImport'),
    )

    expect(source).toContain("import { buildTotalAccountEditPayload, trimEditableField } from '@/utils/accountWorkbenchEditPayload'")
    expect(submitSource).toContain('buildTotalAccountEditPayload(accountForm)')
    expect(source).toContain('trimEditableField(accountForm.phone) === trimEditableField(account.phone)')
    expect(source).toContain('trimEditableField(accountForm.email) === trimEditableField(account.email)')
    expect(source).toContain('trimEditableField(accountForm.registrationIp) === trimEditableField(account.registrationIp)')
    expect(source).toContain('trimEditableField(accountForm.accountStatus) === trimEditableField(account.accountStatus)')
    expect(source).toContain('editableAccountFormString(accountForm.password) === editableAccountFormString(account.password)')
    expect(source).toContain('editableAccountFormString(accountForm.authCookie) === editableAccountFormString(account.authCookie)')
    expect(source).toContain('editableAccountFormString(accountForm.executionAuth) === editableAccountFormString(account.executionAuth)')
    expect(editPayloadUtilSource).toContain('password: preserveEditableDeliveryField(form.password)')
    expect(editPayloadUtilSource).toContain('phone: trimEditableField(form.phone)')
    expect(editPayloadUtilSource).toContain('email: trimEditableField(form.email)')
    expect(editPayloadUtilSource).toContain('email_password: preserveEditableDeliveryField(form.emailPassword)')
    expect(editPayloadUtilSource).toContain('registration_ip: trimEditableField(form.registrationIp)')
    expect(editPayloadUtilSource).toContain('auth_cookie: preserveEditableDeliveryField(form.authCookie)')
    expect(editPayloadUtilSource).toContain('execution_auth: preserveEditableDeliveryField(form.executionAuth)')
    expect(editPayloadUtilSource).toContain('remark: preserveEditableDeliveryField(form.remark)')
    expect(editPayloadUtilSource).toContain('account_status: trimEditableField(form.accountStatus)')
    expect(submitSource).toContain('if (savingAccount.value')
    expect(submitSource).toContain('savingAccount.value = true')
    expect(submitSource).toContain('savingAccount.value = false')
    expect(submitSource).not.toContain('name:')
    expect(submitSource).not.toContain('platform_user_id:')
    expect(submitSource).not.toContain('accountForm.platformUserId || undefined')
    expect(submitSource).not.toContain('accountForm.password || undefined')
    expect(submitSource).not.toContain('accountForm.phone || undefined')
    expect(submitSource).not.toContain('accountForm.email || undefined')
    expect(submitSource).not.toContain('accountForm.emailPassword || undefined')
    expect(submitSource).not.toContain('accountForm.authCookie || undefined')
    expect(submitSource).not.toContain('accountForm.executionAuth || undefined')
    expect(submitSource).not.toContain('accountForm.remark || undefined')
  })

  it('clears stale operation result panels after edit success', () => {
    const editSubmitSource = source.slice(
      source.indexOf('async function submitEditDialog'),
      source.indexOf('function triggerImport'),
    )

    expect(editSubmitSource).toContain('clearTotalAccountOperationResults()')

    const clearResultSource = source.slice(
      source.indexOf('function clearTotalAccountOperationResults'),
      source.indexOf('async function exportAccounts'),
    )
    expect(clearResultSource).toContain('importOperationResult.value = null')
    expect(clearResultSource).toContain('batchOperationResult.value = null')
  })

  it('keeps total account operation result previews centralized for batch and import panels', () => {
    expect(source).toContain("import {\n  totalAccountBatchOperationSummaryParams,\n  useTotalAccountOperationResultPreview,\n} from './totalAccountOperationResults'")
    expect(source).toContain('const batchOperationResultPreview = useTotalAccountOperationResultPreview')
    expect(source).toContain('const importOperationResultPreview = useTotalAccountOperationResultPreview')
    expect(source).toContain('const batchOperationResultItems = batchOperationResultPreview.items')
    expect(source).toContain('const remainingBatchOperationResultItemCount = batchOperationResultPreview.remainingCount')
    expect(source).toContain('const importOperationResultItems = importOperationResultPreview.items')
    expect(source).toContain('const remainingImportOperationResultItemCount = importOperationResultPreview.remainingCount')
    expect(source).toContain('totalAccountBatchOperationSummaryParams(state)')
    expect(operationResultsSource).toContain('TOTAL_ACCOUNT_OPERATION_RESULT_PREVIEW_LIMIT = 8')
    expect(operationResultsSource).toContain("import { useOperationResultPreview } from '@/utils/operationResults'")
    expect(operationResultsSource).toContain('return useOperationResultPreview({ ...options, previewLimit })')
    expect(operationResultsSource).toContain('state.targetUser ? { user: state.targetUser } : {}')
  })

  it('keeps immutable identity read-only while allowing registration IP delivery edits', () => {
    const editDialogSource = source.slice(
      source.indexOf('<BaseDialog :show="editDialogOpen"'),
      source.indexOf('<BaseDialog :show="assignDialogOpen"'),
    )

    expect(editDialogSource).toContain('data-testid="total-account-edit-identity"')
    expect(editDialogSource).toContain('data-testid="total-account-edit-form"')
    expect(editDialogSource).toContain('@close="closeEditDialog"')
    expect(editDialogSource).toContain('v-if="accountFormError"')
    expect(editDialogSource).toContain('role="alert"')
    expect(editDialogSource).toContain(':disabled="savingAccount"')
    expect(editDialogSource).toContain(':disabled="!canSubmitAccount || savingAccount"')
    expect(source).toContain('const accountEditSubmitDisabledReason = computed(() => {')
    expect(source).toContain('const accountEditCancelButtonTitle = computed(() => buildDialogCancelButtonTitle')
    expect(source).toContain('const accountEditSubmitButtonTitle = computed(() => buildAccountEditSubmitButtonTitle')
    expect(source).toContain('const accountEditSubmitButtonLabel = computed(() => buildSubmitButtonLabel')
    expect(editDialogSource).toContain(':aria-label="accountEditCancelButtonTitle"')
    expect(editDialogSource).toContain(':title="accountEditCancelButtonTitle"')
    expect(editDialogSource).toContain(':title="accountEditSubmitButtonTitle"')
    expect(editDialogSource).toContain(':aria-label="accountEditSubmitButtonLabel"')
    expect(totalAccountActionTitlesSource).toContain('export function totalAccountEditSubmitButtonTitle')
    expect(source).toContain("t('admin.socialAccountWorkbench.noChanges')")
    expect(editDialogSource).toContain('editIdentityItems')
    expect(editDialogSource).toContain("t('accountWorkbench.edit.identityHint')")
    expect(editDialogSource).toContain("t('accountWorkbench.detailSections.credentials')")
    expect(editDialogSource).toContain("t('accountWorkbench.detailSections.operations')")
    expect(editDialogSource).toContain('for="total-account-edit-password"')
    expect(editDialogSource).toContain('for="total-account-edit-registration-ip"')
    expect(editDialogSource).toContain('v-model="accountForm.registrationIp"')
    expect(editDialogSource).toContain('for="total-account-edit-auth-cookie"')
    expect(editDialogSource).toContain('for="total-account-edit-remark"')
    expect(editDialogSource).not.toContain('v-model="accountForm.name"')
    expect(editDialogSource).not.toContain('v-model="accountForm.platformUserId"')
  })

  it('keeps total account edit save failures visible inside the existing edit dialog', () => {
    const openEditSource = extractFunctionSource(source, 'function openEditDialog')
    const closeEditSource = extractFunctionSource(source, 'function closeEditDialog()')
    const submitEditSource = extractFunctionSource(source, 'async function submitEditDialog()')

    expect(source).toContain("const accountFormError = ref('')")
    expect(openEditSource).toContain("accountFormError.value = ''")
    expect(closeEditSource).toContain("accountFormError.value = ''")
    expect(submitEditSource).toContain("accountFormError.value = ''")
    expect(submitEditSource).toContain("recordClientDiagnostic('admin.total_accounts.edit', error)")
    expect(submitEditSource).toContain("accountFormError.value = extractSafeApiErrorMessage(error, t('admin.socialAccountWorkbench.saveFailed'), totalAccountErrorMessages.value)")
    expect(submitEditSource).toContain('appStore.showError(accountFormError.value)')
  })

  it('clears hidden selected account context when detail and edit dialogs close', () => {
    const detailDialogSource = source.slice(
      source.indexOf('<BaseDialog :show="detailDialogOpen"'),
      source.indexOf('<BaseDialog :show="editDialogOpen"'),
    )
    const closeDetailSource = extractFunctionSource(source, 'function closeDetailDialog()')
    const closeEditSource = extractFunctionSource(source, 'function closeEditDialog()')
    const submitEditSource = extractFunctionSource(source, 'async function submitEditDialog()')

    expect(detailDialogSource).toContain('@close="closeDetailDialog"')
    expect(detailDialogSource).toContain('@click="closeDetailDialog"')
    expect(closeDetailSource).toContain('detailDialogOpen.value = false')
    expect(closeDetailSource).toContain('selectedAccount.value = null')
    expect(closeEditSource).toContain('if (savingAccount.value) return')
    expect(closeEditSource).toContain('selectedAccount.value = null')
    expect(closeEditSource).toContain('selectedAccountId.value = null')
    expect(submitEditSource).toContain('selectedAccount.value = null')
    expect(submitEditSource).toContain('selectedAccountId.value = null')
  })
})
