import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const testDir = dirname(fileURLToPath(import.meta.url))
const viewPath = resolve(testDir, '../../accounts/UnifiedAccountWorkbenchView.vue')
const routeViewPath = resolve(testDir, '../../AccountWorkbenchRoute.vue')
const staleUserWorkbenchPath = resolve(testDir, '../AccountWorkbenchView.vue')
const staleAccountWorkbenchShellPath = resolve(testDir, '../../../components/accounts/AccountWorkbenchShell.vue')
const routerPath = resolve(testDir, '../../../router/index.ts')
const sidebarPath = resolve(testDir, '../../../components/layout/AppSidebar.vue')
const zhLocalePath = resolve(testDir, '../../../i18n/locales/zh.ts')
const enLocalePath = resolve(testDir, '../../../i18n/locales/en.ts')
const taskTemplateUtilPath = resolve(testDir, '../../../utils/accountWorkbenchTaskTemplate.ts')
const editPayloadUtilPath = resolve(testDir, '../../../utils/accountWorkbenchEditPayload.ts')
const importResultUtilPath = resolve(testDir, '../../../utils/accountWorkbenchImportResult.ts')
const proxyStatusUtilPath = resolve(testDir, '../../../utils/proxyStatus.ts')
const socialAccountStatsGridPath = resolve(testDir, '../../../components/accounts/SocialAccountStatsGrid.vue')
const credentialPreviewComposablePath = resolve(testDir, '../../../composables/useSocialAccountCredentialPreview.ts')
const operationResultsComposablePath = resolve(testDir, '../../accounts/useAccountOperationResults.ts')
const accountWorkbenchErrorMessagesPath = resolve(testDir, '../../accounts/accountWorkbenchErrorMessages.ts')
const accountWorkbenchActionTitlesPath = resolve(testDir, '../../accounts/accountWorkbenchActionTitles.ts')

const routerSource = readFileSync(routerPath, 'utf8')
const sidebarSource = readFileSync(sidebarPath, 'utf8')
const routeViewSource = readFileSync(routeViewPath, 'utf8')
const taskTemplateUtilSource = readFileSync(taskTemplateUtilPath, 'utf8')
const editPayloadUtilSource = readFileSync(editPayloadUtilPath, 'utf8')
const importResultUtilSource = readFileSync(importResultUtilPath, 'utf8')
const proxyStatusUtilSource = readFileSync(proxyStatusUtilPath, 'utf8')
const socialAccountStatsGridSource = readFileSync(socialAccountStatsGridPath, 'utf8')
const credentialPreviewComposableSource = readFileSync(credentialPreviewComposablePath, 'utf8')
const operationResultsComposableSource = readFileSync(operationResultsComposablePath, 'utf8')
const accountWorkbenchErrorMessagesSource = readFileSync(accountWorkbenchErrorMessagesPath, 'utf8')
const accountWorkbenchActionTitlesSource = readFileSync(accountWorkbenchActionTitlesPath, 'utf8')
const accountWorkbenchLocaleSource = [
  readFileSync(zhLocalePath, 'utf8'),
  readFileSync(enLocalePath, 'utf8'),
].join('\n')

function readViewSource() {
  return readFileSync(viewPath, 'utf8')
}

function extractFunctionSource(source: string, signature: string) {
  const start = source.indexOf(signature)
  expect(start).toBeGreaterThanOrEqual(0)
  const bodyStart = source.indexOf('{', start)
  expect(bodyStart).toBeGreaterThanOrEqual(start)
  let depth = 0
  for (let index = bodyStart; index < source.length; index += 1) {
    const char = source[index]
    if (char === '{') depth += 1
    if (char === '}') {
      depth -= 1
      if (depth === 0) return source.slice(start, index + 1)
    }
  }
  throw new Error(`Unable to extract function source for ${signature}`)
}

describe('user AccountWorkbenchView source contract', () => {
  it('removes the stale user workbench implementation so /accounts has one source of truth', () => {
    expect(existsSync(staleUserWorkbenchPath)).toBe(false)
    expect(existsSync(staleAccountWorkbenchShellPath)).toBe(false)
  })

  it('is reachable from the router and discoverable from the user sidebar', () => {
    expect(routerSource).toContain("path: '/accounts'")
    expect(routerSource).toContain("name: 'AccountWorkbench'")
    expect(routerSource).toContain("component: () => import('@/views/AccountWorkbenchRoute.vue')")
    expect(routerSource).toContain("titleKey: 'accountWorkbench.title'")
    expect(routerSource).toContain("path: '/admin/accounts'")
    expect(routerSource).toContain("redirect: '/accounts'")
    expect(routerSource).not.toContain("path: '/admin/accounts',\n    name: 'AdminAccounts'")
    expect(routerSource).not.toContain("path: '/social-accounts'")
    expect(sidebarSource).toContain("path: '/accounts'")
    expect(sidebarSource.indexOf("path: '/accounts'")).toBeLessThan(sidebarSource.indexOf("path: '/usage'"))
  })

  it('uses the table-first account management layout instead of the old workbench card shell', () => {
    const viewSource = readViewSource()

    expect(viewSource).toContain("import AppLayout from '@/components/layout/AppLayout.vue'")
    expect(viewSource).toContain("import TablePageLayout from '@/components/layout/TablePageLayout.vue'")
    expect(viewSource).toContain("import LoadErrorBanner from '@/components/common/LoadErrorBanner.vue'")
    expect(viewSource).toContain("import SocialAccountStatsGrid from '@/components/accounts/SocialAccountStatsGrid.vue'")
    expect(viewSource).toContain('<AppLayout')
    expect(viewSource).toContain('<TablePageLayout')
    expect(viewSource).toContain('<LoadErrorBanner')
    expect(viewSource).toContain('v-if="loadError"')
    expect(viewSource).toContain(":title=\"t('accountWorkbench.failedToLoad')\"")
    expect(viewSource).toContain(':message="loadError"')
    expect(viewSource).toContain(":retry-label=\"t('common.retry')\"")
    expect(viewSource).toContain('@retry="loadData()"')
    expect(viewSource).toContain('<SocialAccountStatsGrid')
    expect(viewSource).toContain('test-id-prefix="account-stat"')
    expect(socialAccountStatsGridSource).toContain("import CommonStatsGrid")
    expect(socialAccountStatsGridSource).toContain('testId: `${props.testIdPrefix}-${stat.key}`')
    expect(socialAccountStatsGridSource).toContain('<CommonStatsGrid')
    expect(socialAccountStatsGridSource).not.toContain('defineEmits')
    expect(socialAccountStatsGridSource).not.toContain('<button')
    expect(viewSource).toContain('data-testid="accounts-toolbar"')
    expect(viewSource).toContain(':title="refreshAccountsButtonTitle"')
    expect(viewSource).toContain(':aria-label="refreshAccountsButtonTitle"')
    expect(viewSource).toContain(':title="batchImportButtonTitle"')
    expect(viewSource).toContain(':aria-label="batchImportButtonTitle"')
    expect(viewSource.match(/:title="batchImportButtonTitle"/g)).toHaveLength(2)
    expect(viewSource.match(/:aria-label="batchImportButtonTitle"/g)).toHaveLength(2)
    expect(viewSource).toContain(':title="batchImportCancelButtonTitle"')
    expect(viewSource).toContain(':title="exportAccountsButtonTitle"')
    expect(viewSource).toContain(':aria-label="exportAccountsButtonTitle"')
    expect(viewSource).toContain(':title="batchProxyButtonTitle"')
    expect(viewSource).toContain(':aria-label="batchProxyButtonTitle"')
    expect(viewSource).toContain(':title="clearSelectionButtonTitle"')
    expect(viewSource).toContain(':aria-label="clearSelectionButtonTitle"')
    expect(viewSource).toContain(':title="deleteSelectedButtonTitle"')
    expect(viewSource).toContain(':aria-label="deleteSelectedButtonTitle"')
    expect(viewSource).toContain(":aria-label=\"storeWorkbenchDisabledReason || t('admin.socialAccountWorkbench.actions.fileUpload')\"")
    expect(viewSource).toContain(':title="storeWorkbenchCancelButtonTitle"')
    expect(viewSource).toContain(':title="accountDetailCloseButtonTitle"')
    expect(viewSource).toContain(':title="executionStartButtonTitle"')
    expect(viewSource).toContain(':aria-label="executionStartButtonTitle"')
    expect(viewSource).toContain(':title="accountRowProxyButtonTitle"')
    expect(viewSource).toContain(':aria-label="accountRowProxyButtonTitle"')
    expect(viewSource).toContain(':title="accountRowEditButtonTitle"')
    expect(viewSource).toContain(':aria-label="accountRowEditButtonTitle"')
    expect(viewSource).toContain(':title="accountRowDeleteButtonTitle"')
    expect(viewSource).toContain(':aria-label="accountRowDeleteButtonTitle"')
    expect(viewSource).toContain(':title="accountEditCancelButtonTitle"')
    expect(viewSource).toContain(':aria-label="accountEditSaveButtonLabel"')
    expect(viewSource).toContain(':title="proxyAssignmentCancelButtonTitle"')
    expect(viewSource).toContain(':title="deleteDialogCancelButtonTitle"')
    expect(viewSource).toContain(':title="executionCancelButtonTitle"')
    expect(viewSource).toContain(':title="executionConfirmButtonTitle"')
    expect(viewSource).toContain(':aria-label="accountEditCancelButtonTitle"')
    expect(viewSource).toContain(':aria-label="batchImportCancelButtonTitle"')
    expect(viewSource).toContain(':aria-label="storeWorkbenchCancelButtonTitle"')
    expect(viewSource).toContain(':aria-label="proxyAssignmentCancelButtonTitle"')
    expect(viewSource).toContain(':aria-label="deleteDialogCancelButtonTitle"')
    expect(viewSource).toContain(':aria-label="executionCancelButtonTitle"')
    expect(viewSource).toContain(':aria-label="executionConfirmButtonTitle"')
    expect(viewSource).toContain("from './accountWorkbenchActionTitles'")
    expect(viewSource).toContain('const refreshAccountsButtonTitle = computed(() => buildRefreshButtonTitle')
    expect(viewSource).toContain('const batchImportCancelButtonTitle = computed(() => buildBatchImportCancelButtonTitle')
    expect(viewSource).toContain('const batchProxyButtonTitle = computed(() => buildBatchProxyButtonTitle')
    expect(viewSource).toContain('const accountDetailCloseButtonTitle = computed(() => buildAccountDetailCloseButtonTitle')
    expect(viewSource).toContain('const accountEditCancelButtonTitle = computed(() => buildAccountEditCancelButtonTitle')
    expect(viewSource).toContain('const accountEditSaveButtonTitle = computed(() => buildAccountEditSaveButtonTitle')
    expect(viewSource).toContain('const accountEditSaveButtonLabel = computed(() => buildAccountEditSaveButtonLabel')
    expect(viewSource).toContain('const proxyAssignmentCancelButtonTitle = computed(() => buildProxyAssignmentCancelButtonTitle')
    expect(viewSource).toContain('const deleteDialogCancelButtonTitle = computed(() => buildDeleteDialogCancelButtonTitle')
    expect(viewSource).toContain('const executionStartButtonTitle = computed(() => buildExecutionStartButtonTitle')
    expect(viewSource).toContain('const executionCancelButtonTitle = computed(() => buildExecutionCancelButtonTitle')
    expect(viewSource).toContain('const executionConfirmButtonTitle = computed(() => buildExecutionConfirmButtonTitle')
    expect(viewSource).toContain('const accountRowProxyButtonTitle = computed(() => buildRowProxyButtonTitle')
    expect(viewSource).toContain('const accountRowEditButtonTitle = computed(() => buildRowEditButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain("'admin.socialAccountWorkbench.executionBar.selectionRequired'")
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountBatchImportCancelButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountBatchProxyButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountProxyCancelButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountDeleteCancelButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountDetailCloseButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountEditCancelButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountEditSaveButtonLabel')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountEditSaveButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountExecutionStartButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountExecutionCancelButtonTitle')
    expect(accountWorkbenchActionTitlesSource).toContain('export function accountExecutionConfirmButtonTitle')
    expect(viewSource).toContain('data-testid="accounts-batch-import-dialog"')
    expect(viewSource).not.toContain("import AccountWorkbenchShell")
    expect(viewSource).not.toContain('<AccountWorkbenchShell')
    expect(viewSource).not.toContain('<template #import>')
    expect(viewSource).not.toContain('data-testid="accounts-import-dialog"')
    expect(viewSource).not.toContain("t('accountWorkbench.billing.title')")
  })

  it('keeps /accounts on one implementation for admins and users', () => {
    expect(routeViewSource).toContain("import UnifiedAccountWorkbenchView from '@/views/accounts/UnifiedAccountWorkbenchView.vue'")
    expect(routeViewSource).toContain('<UnifiedAccountWorkbenchView')
    expect(routeViewSource).not.toContain('AdminAccountWorkbenchView')
  })

  it('keeps /accounts scoped to the current user workbench APIs', () => {
    const viewSource = readViewSource()

    expect(viewSource).toContain('accountWorkbenchAPI.listMyAccounts')
    expect(viewSource).toContain('accountWorkbenchAPI.batchImportMyAccounts')
    expect(viewSource).toContain('accountWorkbenchAPI.deleteMyAccount')
    expect(viewSource).toContain('accountWorkbenchAPI.batchDeleteMyAccounts')
    expect(viewSource).toContain('accountWorkbenchAPI.updateMyAccount')
    expect(viewSource).toContain('accountWorkbenchAPI.submitTask')
    expect(viewSource).toContain('accountWorkbenchAPI.listTaskLogs')
    expect(viewSource).toContain('accountWorkbenchAPI.setDefaultProxy')
    expect(viewSource).toContain('accountWorkbenchAPI.batchSetDefaultProxy')
    expect(viewSource).toContain("import proxiesAPI from '@/api/proxies'")
    expect(viewSource).toContain("import taskSettingsAPI from '@/api/taskSettings'")
    expect(viewSource).toContain('buildDeliveryCredentialItems(selectedAccount.value')
    expect(viewSource).toContain("emailTokenTestId: 'account-email-token-preview'")
    expect(viewSource).toContain("emailTokenCopyTestId: 'account-email-token-copy'")
    expect(viewSource).toContain('buildCredentialPreviews(selectedAccount.value)')
    expect(credentialPreviewComposableSource).toContain('value: account.password')
    expect(credentialPreviewComposableSource).toContain('value: account.emailPassword')
    expect(credentialPreviewComposableSource).toContain("buildCredentialPreview('authCookie', account.authCookie)")
    expect(credentialPreviewComposableSource).toContain("buildCredentialPreview('executionAuth', account.executionAuth, account.authCookie)")
    expect(viewSource).toContain('selectedAccount.value.defaultProxySnapshot')
    expect(viewSource).toContain('selectedAccount.value.remark')
    expect(viewSource).toContain('account.password ??')
    expect(viewSource).toContain('account.email_password ??')
    expect(viewSource).toContain('account.auth_cookie ??')
    expect(viewSource).toContain('account.execution_auth ??')
    expect(viewSource).toContain('account.default_proxy_snapshot ??')
    expect(viewSource).toContain('account.remark ??')
    expect(viewSource).toContain("const EXECUTION_ACTIONS = ['login', 'login_check', 'follow', 'post', 'like', 'retweet', 'update_profile', 'update_avatar', 'update_banner'] as const")
    expect(viewSource).toContain('executionActionOptions')
    expect(viewSource).toContain("t('accountWorkbench.execution.noActions')")
    expect(viewSource).not.toContain("value: '" + 'message' + "'")
    expect(viewSource).not.toContain('message' + 'Unavailable')
    expect(viewSource).toContain('canUseAdminAccountTools')
    expect(viewSource).not.toContain('adminTools')
    expect(viewSource).not.toContain('adminUploadDialog')
    expect(viewSource).not.toContain('adminRegisterDialog')
    expect(viewSource).not.toContain('adminRegisterForm')
    expect(viewSource).not.toContain('accountWorkbenchAdminAPI.register')
    expect(viewSource).toContain('accountWorkbenchAdminAPI.storeWorkbenchAccounts')
    expect(viewSource).toContain('storeableWorkbenchAccounts')
    expect(viewSource).not.toContain('selectedUploadableAccounts')
    expect(viewSource).toContain('presentationWorkbenchAccountStatus(account.accountStatus)')
    expect(viewSource).toContain('workbenchAccountStatusBadgeClass')
    expect(viewSource).toContain('workbenchTaskStatusBadgeClass')
    expect(viewSource).toContain("t(`accountWorkbench.accountStatus.${normalized}`")
    expect(viewSource).not.toContain('accountWorkbench.accountStatus.illegal')
    expect(viewSource).not.toContain('非法账号')
    expect(viewSource).not.toContain('无效账号')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.create')
    expect(viewSource).not.toContain('buildPoolAccountPayload')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.importAccounts')
    expect(viewSource).not.toContain('accountWorkbenchAdminAPI.importAccounts')
    expect(viewSource).not.toContain('actionPickerValue')
    expect(viewSource).toContain('platformFilterOptions')
    expect(viewSource).toContain('openBatchImportDialog')
    expect(viewSource).toContain("import * as XLSX from 'xlsx'")
    expect(viewSource).toContain('handleBatchImportFileChange')
    expect(viewSource).toContain('batchImportFileRows')
    expect(viewSource).toContain('activeBatchImportRows')
    expect(viewSource).toContain('existingWorkbenchImportKeys')
    expect(viewSource).toContain('markExistingWorkbenchDuplicates')
    expect(viewSource).toContain("status: 'existing_workbench_duplicate' as const")
    expect(viewSource).toContain('filter(isBatchImportRowSubmittable)')
    expect(viewSource).toContain('function isBatchImportRowSubmittable')
    expect(viewSource).not.toContain("row.status === 'format_valid'")
    expect(viewSource).toContain('batchImportFileRows.value = parseBatchImportRows(fileText, importForm.platform.trim())')
    expect(viewSource).toContain('@input="clearBatchImportFileSource"')
    expect(viewSource).not.toContain('batchImportText.value = await file.text()')
    expect(viewSource).not.toContain('batchImportText.value = await importWorkbookToText(file)')
    expect(viewSource).toContain('accept=".txt,.xls,.xlsx')
    expect(viewSource).toContain('socialAccountImportDedupKey')
    expect(viewSource).toContain('normalizeSocialImportUsername')
    expect(viewSource).toContain('parseSocialAccountImportTextRows')
    expect(viewSource).toContain('socialAccountImportWorkbookRowsToText')
    expect(viewSource).not.toContain('function importAccountDedupKey')
    expect(viewSource).not.toContain('function normalizeImportUsername')
    expect(viewSource).not.toContain('function parseImportLine')
    expect(viewSource).not.toContain('function splitImportLine')
    expect(viewSource).not.toContain('function looksLikeImportHeader')
    expect(viewSource).not.toContain('function normalizeImportHeader')
    expect(viewSource).not.toContain('function workbookRowsToImportText')
    expect(viewSource).toContain('return parseSocialAccountImportTextRows(')
    expect(viewSource).toContain('return socialAccountImportWorkbookRowsToText(rows)')
    expect(viewSource).toContain("t('accountWorkbench.import.errors.duplicateAccount')")
    expect(viewSource).not.toContain('openImportDialog')
    expect(viewSource).not.toContain('importDialogOpen')
    expect(viewSource).not.toContain('importAccount(')
    const normalizeImportSource = viewSource.slice(
      viewSource.indexOf('function normalizeImportAccount'),
      viewSource.indexOf('function setImportField'),
    )
    expect(normalizeImportSource).not.toContain('default_proxy_snapshot')
    expect(viewSource).toContain("t('accountWorkbench.import.pendingCount')")
    expect(viewSource).toContain("t('accountWorkbench.import.submitReady')")
    expect(viewSource).toContain("t('accountWorkbench.import.previewMeta'")
    expect(viewSource).toContain("t('accountWorkbench.import.previewScopeUser')")
    expect(viewSource).not.toContain('pendingBackendCheckCount')
    expect(viewSource).not.toContain('localCheckReady')
    expect(viewSource).not.toContain('previewMetaAdmin')
    expect(viewSource).not.toContain('previewScopeAdmin')
    expect(viewSource).not.toContain("t('accountWorkbench.import.previewScope')")
    expect(viewSource).toContain('batchImportRowStatusLabel')
    expect(viewSource).toContain("t('accountWorkbench.import.status.batchDuplicate')")
    expect(viewSource).toContain("t('accountWorkbench.import.status.existingWorkbenchDuplicate')")
    expect(viewSource).toContain("t('accountWorkbench.import.status.pendingBackendMatch')")
    expect(viewSource).toContain("t('accountWorkbench.import.errors.duplicateInWorkbench')")
    expect(viewSource).toContain('batchImportResultMessage')
    expect(viewSource).toContain('accountWorkbenchImportResultItemMessage(item, t)')
    expect(importResultUtilSource).toContain('accountWorkbench.import.resultReasons.matchedTotalPool')
    expect(importResultUtilSource).toContain('accountWorkbench.import.resultReasons.stagedNotStored')
    expect(viewSource).not.toContain('pendingBackendCheck')
    expect(viewSource).not.toContain('platformAccount')
    expect(viewSource).not.toContain('平台账号')
    expect(viewSource).not.toContain("t('accountWorkbench.import.status.formatValid')")
    expect(viewSource).not.toContain('pending_backend_check')
    expect(viewSource).not.toContain("t('accountWorkbench.import.valid')")
    expect(viewSource).not.toContain("t('accountWorkbench.import.invalid')")
    expect(viewSource).not.toContain("t('admin.socialAccountWorkbench.uploadPreview.ready')")
    expect(viewSource).not.toContain('可导入')
    expect(viewSource).not.toContain('待导入')
    expect(viewSource).toContain('batchImportResult')
    expect(viewSource).toContain('batchImportResultPreviewItems')
    expect(viewSource).toContain('remainingBatchImportResultItemCount')
    expect(viewSource).toContain("t('accountWorkbench.import.resultSummary'")
    expect(viewSource).toContain("t('accountWorkbench.import.resultTitle')")
    expect(viewSource).toContain("t('accountWorkbench.import.resultRowsMore'")
    expect(viewSource).toContain('<SocialAccountBatchResultRows')
    expect(viewSource).toContain(':items="batchImportResultPreviewItems"')
    expect(viewSource).toContain(':item-label="batchImportResultItemLabel"')
    expect(viewSource).toContain(':status-label="batchImportResultStatusLabel"')
    expect(viewSource).toContain(':item-message="batchImportResultMessage"')
    expect(viewSource).toContain(':row-tone-class="socialAccountBatchResultRowToneClass"')
    expect(viewSource).not.toContain('v-for="item in batchImportResultPreviewItems"')
    expect(viewSource).not.toContain('line-clamp-2 opacity-80')
    expect(viewSource).toContain("import { createListPreview } from '@/utils/listPreview'")
    expect(viewSource).toContain("import { useAccountOperationResults } from './useAccountOperationResults'")
    expect(viewSource).toContain('useAccountOperationResults({')
    expect(operationResultsComposableSource).toContain("import { clearOperationResultRefs, useOperationResultPreview } from '@/utils/operationResults'")
    expect(operationResultsComposableSource).toContain('useOperationResultPreview({')
    expect(viewSource).toContain('dependencyLoadError')
    expect(viewSource).toContain("t('accountWorkbench.dependencyLoadWarning')")
    expect(viewSource).toContain('async function loadOptionalAccountDependencies(requestID: number)')
    expect(viewSource).toContain('Promise.allSettled')
    expect(viewSource).not.toContain('const [accountsResult, proxyResult, templateResult] = await Promise.all([')
    expect(viewSource).not.toContain('addMenu')
    expect(viewSource).not.toContain('accountWorkbenchAPI.listMy' + 'TaskLogs')
    expect(viewSource).not.toContain('source' + 'Filter')
    expect(viewSource).not.toContain('source' + 'FilterOptions')
    expect(viewSource).not.toContain('source' + 'Label')
    expect(viewSource).not.toContain('recentTask' + 'Summaries')
    expect(viewSource).toContain('taskLogsByAccountId')
    expect(viewSource).not.toContain('logs' + 'Loading')
    expect(viewSource).not.toContain('selected' + 'Log')
    expect(viewSource).not.toContain('logDetail' + 'DialogOpen')
    expect(viewSource).not.toContain('loadTaskLogs')
    expect(viewSource).not.toContain('openLogDetail')
    expect(viewSource).not.toContain('chargedTasks')
    expect(viewSource).not.toContain("t('accountWorkbench." + 'logs')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.list')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.delete')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.batchDelete')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.submitTask')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.list' + 'TaskLogs')
    expect(viewSource).not.toContain('accountWorkbenchAdminAPI.list(')
    expect(viewSource).not.toContain('accountWorkbenchAdminAPI.delete')
    expect(viewSource).not.toContain('accountWorkbenchAdminAPI.batchDelete')
    expect(viewSource).not.toContain('accountWorkbenchAdminAPI.submitTask')
    expect(viewSource).not.toContain('loadAdminAccounts')
    expect(viewSource).not.toContain('assignedUser')
    expect(viewSource).not.toContain('assignDialog')
    expect(viewSource).not.toContain('reclaimDialog')
    expect(viewSource).not.toContain('accountWorkbenchAdminAPI.reclaim')
    expect(viewSource).not.toContain('poolTabCount')
    expect(viewSource).not.toContain("to=\"/admin/total-accounts\"")
    expect(viewSource).not.toContain(' 路 ')
    expect(viewSource).not.toContain("t('admin.socialAccountWorkbench.title')")
  })

  it('uses shared selection helpers for selected account rows', () => {
    const viewSource = readViewSource()

    expect(viewSource).toContain('selectedRowsById,')
    expect(viewSource).toContain('const selectedAccounts = computed(() => selectedRowsById(accounts.value, selectedIds.value))')
    expect(viewSource).not.toContain('accounts.value.filter(account => selectedIds.value.includes(account.id))')
  })

  it('locks account export while the list is refreshing or a download is already pending', () => {
    const viewSource = readViewSource()
    const exportSource = extractFunctionSource(viewSource, 'async function exportAccounts()')

    expect(viewSource).toContain(':disabled="loading || exportingAccounts"')
    expect(exportSource).toContain('if (loading.value || exportingAccounts.value) return')
    expect(viewSource).toContain('const exportAccountParams = computed<MyAccountExportParams>')
    expect(viewSource).toContain("selectedIds.value.length > 0 ? { account_ids: [...selectedIds.value] } : {}")
    expect(exportSource).toContain('accountWorkbenchAPI.exportMyAccounts(exportAccountParams.value)')
  })

  it('lets users edit mutable credentials without editing identity fields', () => {
    const viewSource = readViewSource()
    const saveSource = extractFunctionSource(viewSource, 'async function saveAccountEdit()')

    expect(viewSource).toContain('editDialogOpen')
    expect(viewSource).toContain('openEditDialog(row)')
    expect(viewSource).toContain('data-testid="account-edit-identity"')
    expect(viewSource).toContain('data-testid="account-edit-form"')
    expect(viewSource).toContain("t('accountWorkbench.detailSections.credentials')")
    expect(viewSource).toContain("t('accountWorkbench.detailSections.operations')")
    expect(viewSource).toContain('for="account-edit-password"')
    expect(viewSource).toContain('for="account-edit-phone"')
    expect(viewSource).toContain('for="account-edit-email"')
    expect(viewSource).toContain('for="account-edit-auth-cookie"')
    expect(viewSource).toContain('for="account-edit-remark"')
    expect(viewSource).toContain('editAccountForm.password')
    expect(viewSource).toContain('editAccountForm.phone')
    expect(viewSource).toContain('editAccountForm.email')
    expect(viewSource).toContain('editAccountForm.emailPassword')
    expect(viewSource).toContain('editAccountForm.twoFactor')
    expect(viewSource).toContain('editAccountForm.authCookie')
    expect(viewSource).toContain('editAccountForm.executionAuth')
    expect(viewSource).toContain('editAccountForm.remark')
    expect(viewSource).toContain('const canSaveAccountEdit = computed(() => {')
    expect(viewSource).toContain('return !!editAccount.value && !accountActionsLocked.value && !editAccountFormMatchesAccount(editAccount.value)')
    expect(viewSource).toContain('const accountEditSaveDisabledReason = computed(() => {')
    expect(viewSource).toContain("t('accountWorkbench.edit.noChanges')")
    expect(viewSource).not.toContain("const canSaveAccountEdit = computed(() => !!editAccount.value && trimEditableField(editAccountForm.password) !== '')")
    expect(saveSource).toContain('accountWorkbenchAPI.updateMyAccount(editAccount.value.id')
    expect(saveSource).toContain('buildAccountEditPayload(editAccountForm)')
    expect(editPayloadUtilSource).toContain('password: preserveEditableDeliveryField(form.password)')
    expect(editPayloadUtilSource).toContain('phone: trimEditableField(form.phone)')
    expect(editPayloadUtilSource).toContain('email: trimEditableField(form.email)')
    expect(editPayloadUtilSource).toContain('email_password: preserveEditableDeliveryField(form.emailPassword)')
    expect(editPayloadUtilSource).toContain('two_factor: preserveEditableDeliveryField(form.twoFactor)')
    expect(editPayloadUtilSource).toContain('backup_code: preserveEditableDeliveryField(form.backupCode)')
    expect(editPayloadUtilSource).toContain('email_client_id: preserveEditableDeliveryField(form.emailClientId)')
    expect(editPayloadUtilSource).toContain('email_token: preserveEditableDeliveryField(form.emailToken)')
    expect(editPayloadUtilSource).toContain('registration_ip: trimEditableField(form.registrationIp)')
    expect(editPayloadUtilSource).toContain('auth_cookie: preserveEditableDeliveryField(form.authCookie)')
    expect(editPayloadUtilSource).toContain('execution_auth: preserveEditableDeliveryField(form.executionAuth)')
    expect(editPayloadUtilSource).toContain('remark: preserveEditableDeliveryField(form.remark)')
    expect(saveSource).not.toContain('name:')
    expect(saveSource).not.toContain('platform:')
    expect(saveSource).not.toContain('platform_user_id')
    expect(saveSource).not.toContain('account_status')
    expect(saveSource).not.toContain('task_status')
    expect(saveSource).not.toContain('default_proxy_snapshot')
  })

  it('keeps account edit save failures visible inside the existing edit dialog', () => {
    const viewSource = readViewSource()
    const openEditSource = extractFunctionSource(viewSource, 'function openEditDialog')
    const closeEditSource = extractFunctionSource(viewSource, 'function closeEditDialog()')
    const saveSource = extractFunctionSource(viewSource, 'async function saveAccountEdit()')

    expect(viewSource).toContain("const editAccountError = ref('')")
    expect(viewSource).toContain('v-if="editAccountError"')
    expect(viewSource).toContain('role="alert"')
    expect(openEditSource).toContain("editAccountError.value = ''")
    expect(closeEditSource).toContain("editAccountError.value = ''")
    expect(saveSource).toContain("editAccountError.value = ''")
    expect(saveSource).toContain("recordClientDiagnostic('account_workbench.unified.update_account', error)")
    expect(saveSource).toContain("editAccountError.value = extractSafeApiErrorMessage(error, t('accountWorkbench.edit.failed'), accountEditErrorMessages.value)")
    expect(saveSource).toContain('appStore.showError(editAccountError.value)')
  })

  it('keeps upload-to-pool request failures visible inside the existing confirmation dialog', () => {
    const viewSource = readViewSource()
    const openSource = extractFunctionSource(viewSource, 'function openStoreWorkbenchDialog()')
    const closeSource = extractFunctionSource(viewSource, 'function closeStoreWorkbenchDialog()')
    const confirmSource = extractFunctionSource(viewSource, 'async function confirmStoreWorkbenchSelection()')

    expect(viewSource).toContain("const storeWorkbenchError = ref('')")
    expect(viewSource).toContain('v-if="storeWorkbenchError"')
    expect(viewSource).toContain(':title="storeWorkbenchError"')
    expect(openSource).toContain("storeWorkbenchError.value = ''")
    expect(closeSource).toContain("storeWorkbenchError.value = ''")
    expect(confirmSource).toContain("storeWorkbenchError.value = ''")
    expect(confirmSource).toContain("recordClientDiagnostic('account_workbench.unified.store_workbench_accounts', error)")
    expect(confirmSource).toContain("storeWorkbenchError.value = extractSafeApiErrorMessage(error, t('accountWorkbench.storeWorkbench.failed'), accountWorkbenchErrorMessages.value)")
    expect(confirmSource).toContain('appStore.showError(storeWorkbenchError.value)')
  })

  it('clears hidden selected account context when the detail dialog closes', () => {
    const viewSource = readViewSource()
    const closeDetailSource = extractFunctionSource(viewSource, 'function closeDetailDialog()')

    expect(viewSource).toContain('<BaseDialog :show="detailDialogOpen"')
    expect(viewSource).toContain('@close="closeDetailDialog"')
    expect(viewSource).toContain(':refreshing="selectedAccountRefreshingExecutionAuth"')
    expect(viewSource).toContain('if (!account || executionAuthRefreshInProgress.value) return')
    expect(closeDetailSource).toContain('if (selectedAccountRefreshingExecutionAuth.value) return')
    expect(closeDetailSource).toContain('detailDialogOpen.value = false')
    expect(closeDetailSource).toContain('selectedAccount.value = null')
  })

  it('keeps execution submission direct and user-safe', () => {
    const viewSource = readViewSource()

    expect(taskTemplateUtilSource).toContain('ACCOUNT_WORKBENCH_MAX_TEMPLATE_POOL_VALUES = 500')
    expect(taskTemplateUtilSource).toContain('ACCOUNT_WORKBENCH_MAX_TEMPLATE_VALUE_LENGTH = 2048')
    expect(viewSource).toContain('workbenchTaskTemplateDisabled')
    expect(viewSource).toContain('selectedAction')
    expect(viewSource).toContain('defaultTemplateByAction')
    expect(viewSource).toContain('buildTaskPayload')
    expect(viewSource).toContain('action,')
    expect(viewSource).not.toContain('selectedTemplateId')
    expect(viewSource).not.toContain('template_id')
    expect(viewSource).not.toContain('action: selectedTemplate.value.type')
    expect(viewSource).toContain('executionConfirmDialogOpen')
    expect(viewSource).toContain('taskActivityStatusCounts')
    expect(viewSource).not.toContain('trackedTaskLogIds')
    expect(viewSource).not.toContain('taskActivityPreviewLogs')
    expect(viewSource).not.toContain('taskResultPanelToneClass')
    expect(viewSource).not.toContain('taskResultRowToneClass(log)')
    expect(viewSource).not.toContain('hasFailedTaskNoChargeSummary')
    expect(viewSource).not.toContain("t('accountWorkbench.execution.failureNoChargeSummary')")
    expect(accountWorkbenchLocaleSource).not.toContain('failureNoChargeSummary')
    expect(viewSource).not.toContain('isFailedTaskResultLog')
    expect(viewSource).not.toContain("import { formatSocialTaskResultMessage } from '@/utils/socialTaskResultMessage'")
    expect(viewSource).toContain("from '@/utils/socialAccountTaskStatus'")
    expect(viewSource).toContain('socialAccountTaskStatusFromTaskResult')
    expect(viewSource).not.toContain("import { formatWorkbenchTaskSummary, formatWorkbenchTaskSummaryMeta } from '@/utils/workbenchTaskSummary'")
    expect(viewSource).not.toContain('taskResultMessage(log)')
    expect(viewSource).not.toContain('taskResultSummary(log)')
    expect(viewSource).not.toContain('taskResultSummaryMeta(log)')
    expect(viewSource).not.toContain("t('accountWorkbench.execution.resultRows')")
    expect(viewSource).not.toContain('accountWorkbench.execution.taskStatuses.${normalized}')
    expect(viewSource).not.toContain('accountWorkbench.execution.chargeStatuses.${normalized}')
    expect(accountWorkbenchLocaleSource).not.toContain('"charge_failed"')
    expect(viewSource).not.toContain('{{ log.result_message }}')
    expect(viewSource).not.toContain('log.charged_amount')
    expect(viewSource).toContain('proxyAssignmentResult')
    expect(viewSource).toContain('proxyAssignmentResultPreviewItems')
    expect(viewSource).toContain('remainingProxyAssignmentResultItemCount')
    expect(operationResultsComposableSource).toContain("export type AccountOperationResultKey = 'batchImport' | 'storeWorkbench' | 'proxyAssignment'")
    expect(operationResultsComposableSource).toContain('function clearAccountOperationResults')
    expect(operationResultsComposableSource).toContain('clearOperationResultRefs<AccountOperationResultKey>')
    expect(viewSource).toContain('proxyAssignmentResultSummary')
    expect(viewSource).toContain('proxyAssignmentResultSummaryText')
    expect(viewSource).toContain('storeWorkbenchResultSummary')
    expect(viewSource).toContain('storeWorkbenchResultSummaryText')
    expect((viewSource.match(/accountWorkbench\.proxy\.resultSummary/g) || []).length).toBe(1)
    expect((viewSource.match(/accountWorkbench\.storeWorkbench\.resultSummary/g) || []).length).toBe(1)
    expect(viewSource).toContain('proxyAssignmentResultStatusLabel')
    expect(viewSource).toContain('SocialAccountBatchResultRows')
    expect(viewSource).toContain(':row-tone-class="socialAccountBatchResultRowToneClass"')
    expect(viewSource).not.toContain('function batchImportResultRowToneClass')
    expect(viewSource).not.toContain('function proxyAssignmentResultRowToneClass')
    expect(viewSource).toContain('combine-status-and-message')
    expect(viewSource).toContain('client_request_id')
    expect(viewSource).toContain('canStartExecution')
    expect(viewSource).toContain('hasNonExecutableSelection')
    expect(viewSource).toContain('batchImportText')
    expect(viewSource).toContain('deleteSelectedAccounts')
    expect(viewSource).toContain('loadError')
    expect(viewSource).toContain('@retry="loadData()"')
    expect(viewSource).toContain('extractSafeApiErrorMessage')
    expect(viewSource).toContain("import { createAccountWorkbenchErrorMessages } from './accountWorkbenchErrorMessages'")
    expect(viewSource).toContain('accountWorkbenchErrorMessages.value')
    expect(accountWorkbenchErrorMessagesSource).toContain('SOCIAL_ACCOUNT_SERVICE_UNAVAILABLE')
    expect(accountWorkbenchErrorMessagesSource).toContain('SOCIAL_IP_SERVICE_UNAVAILABLE')
    expect(accountWorkbenchLocaleSource).toContain('"SOCIAL_TASK_SERVICE_UNAVAILABLE":')
    expect(accountWorkbenchLocaleSource).toContain('"TASK_TEMPLATE_SERVICE_UNAVAILABLE":')
    expect(accountWorkbenchLocaleSource).toContain('"SOCIAL_IP_SERVICE_UNAVAILABLE":')
    expect(viewSource).toContain('recordClientDiagnostic')
    expect(viewSource).not.toContain('accountWorkbenchAPI.estimateTask')
    expect(viewSource).not.toContain('billingEstimate')
    expect(viewSource).not.toContain('canEstimateExecution')
    expect(viewSource).not.toContain('executionTarget')
    expect(viewSource).not.toContain('executionContent')
    expect(viewSource).not.toContain('targetPlaceholder')
    expect(viewSource).not.toContain('contentPlaceholder')
    expect(viewSource).not.toContain('proxyForm.proxyId')
    expect(viewSource).not.toContain('adminRegisterForm.proxyId')
    expect(viewSource).not.toContain('proxy_id: Number')
    expect(viewSource).not.toContain("t('accountWorkbench.billing")
    expect(viewSource).not.toContain('extractApiErrorMessage')
    expect(viewSource).not.toContain('console.error')
  })

  it('treats accounts without an assignable default proxy as not execution-ready', () => {
    const viewSource = readViewSource()
    const readinessSource = extractFunctionSource(viewSource, 'function isExecutableAccount(account: AccountRow)')

    expect(readinessSource).toContain('account.defaultProxyConfigured')
  })

  it('normalizes usable proxy statuses before account proxy assignment uses them', () => {
    const viewSource = readViewSource()
    const usableProxySource = extractFunctionSource(viewSource, 'function isUsableProxy(proxy: UserProxy)')

    expect(viewSource).toContain("import { normalizeProxyStatus } from '@/utils/proxyStatus'")
    expect(usableProxySource).toContain("normalizeProxyStatus(proxy.status) === 'online'")
    expect(usableProxySource).not.toContain("proxy.status === 'online'")
    expect(proxyStatusUtilSource).toContain('export function normalizeProxyStatus')
    expect(proxyStatusUtilSource).toContain("return 'unknown'")
  })

  it('does not allow stale oversized task templates to be auto-selected for execution', () => {
    const viewSource = readViewSource()
    const templateDisabledSource = taskTemplateUtilSource
    const poolValidSource = extractFunctionSource(taskTemplateUtilSource, 'export function templatePoolValuesValid(values?: string[])')

    expect(templateDisabledSource).toContain('templatePoolValuesValid')
    expect(templateDisabledSource).toContain("template.type === 'update_profile'")
    expect(templateDisabledSource).toContain("template.type === 'update_avatar'")
    expect(templateDisabledSource).toContain("template.type === 'update_banner'")
    expect(templateDisabledSource).toContain('templateMediaRefsValid')
    expect(templateDisabledSource).toContain('socialPostMediaRefsSupported(template.params.media)')
    expect(templateDisabledSource).toContain('socialTaskMediaRefExecutable(template.params.avatar)')
    expect(templateDisabledSource).toContain('socialTaskMediaRefExecutable(template.params.banner)')
    expect(templateDisabledSource).toContain('ACCOUNT_WORKBENCH_REQUIRED_AVATAR_IMAGE_WIDTH')
    expect(templateDisabledSource).toContain('ACCOUNT_WORKBENCH_REQUIRED_AVATAR_IMAGE_HEIGHT')
    expect(templateDisabledSource).toContain('ACCOUNT_WORKBENCH_REQUIRED_BANNER_IMAGE_WIDTH')
    expect(templateDisabledSource).toContain('ACCOUNT_WORKBENCH_REQUIRED_BANNER_IMAGE_HEIGHT')
    expect(poolValidSource).toContain('ACCOUNT_WORKBENCH_MAX_TEMPLATE_POOL_VALUES')
    expect(poolValidSource).toContain('ACCOUNT_WORKBENCH_MAX_TEMPLATE_VALUE_LENGTH')
    expect(poolValidSource).toContain('Array.from(value).length')
    expect(viewSource).toContain('function templateDisabled(template: TaskTemplate)')
    expect(viewSource).toContain('workbenchTaskTemplateDisabled(template')
    expect(viewSource).toContain('defaultTemplateByAction')
    expect(viewSource).toContain('taskTemplates.value.find(item => item.type === action && item.is_default)')
  })

  it('keeps optional account dependencies under the latest list request guard', () => {
    const viewSource = readViewSource()

    expect(viewSource).toContain('await loadOptionalAccountDependencies(requestID)')
    expect(viewSource).toContain('async function loadOptionalAccountDependencies(requestID: number)')
    expect(viewSource).toContain('if (requestID !== latestLoadRequestID) return')
  })

  it('summarizes structured templates instead of assuming every template is a target/content pool', () => {
    const viewSource = readViewSource()
    const templateSummarySource = extractFunctionSource(viewSource, 'function templateSummary(template: TaskTemplate)')

    expect(viewSource).toContain('selectedActionTemplateMetricRows')
    expect(viewSource).toContain('selectedActionTemplateMediaPreview')
    expect(viewSource).toContain('selectedActionTemplatePreviewCards')
    expect(viewSource).toContain('loadSelectedActionTemplateMediaPreview')
    expect(viewSource).toContain('clearSelectedActionTemplateMediaPreview')
    expect(viewSource).toContain('taskSettingsAPI.previewMedia(storageKey)')
    expect(viewSource).toContain("socialTaskMediaRefExecutableStored(item)")
    expect(viewSource).toContain('createObjectURLSafe(blob)')
    expect(viewSource).toContain('revokeObjectURLSafe(url)')
    expect(viewSource).toContain('onBeforeUnmount(() => {')
    expect(viewSource).toContain(':data-testid="card.summaryTestId"')
    expect(viewSource).toContain(':data-testid="card.confirmTestId"')
    expect(viewSource).toContain("summaryTestId: `selected-template-preview-post-${index}`")
    expect(viewSource).toContain("confirmTestId: `execution-confirm-preview-post-${index}`")
    expect(viewSource).toContain("summaryTestId: 'selected-template-preview-avatar'")
    expect(viewSource).toContain("confirmTestId: 'execution-confirm-preview-avatar'")
    expect(viewSource).toContain("summaryTestId: 'selected-template-preview-banner'")
    expect(viewSource).toContain("confirmTestId: 'execution-confirm-preview-banner'")
    expect(viewSource).toContain("t('accountWorkbench.execution.templateDetails')")
    expect(viewSource).toContain('function buildTemplateMetricRows(template: TaskTemplate)')
    expect(templateSummarySource).toContain("t('accountWorkbench.execution.postRichSummary'")
    expect(templateSummarySource).toContain("t('accountWorkbench.execution.profileSummary'")
    expect(templateSummarySource).toContain("t('accountWorkbench.execution.avatarSummary')")
    expect(templateSummarySource).toContain("t('accountWorkbench.execution.bannerSummary')")
  })

  it('keeps the empty task-template state visible instead of masking it with unavailable actions', () => {
    const viewSource = readViewSource()
    const optionsStart = viewSource.indexOf('const executionActionOptions = computed<SelectOption[]>(() => {')
    const emptyBranchIndex = viewSource.indexOf('if (runtimeExecutionActions.length === 0)', optionsStart)
    const messageOptionIndex = viewSource.indexOf("value: '" + 'message' + "'", optionsStart)

    expect(optionsStart).toBeGreaterThanOrEqual(0)
    expect(emptyBranchIndex).toBeGreaterThan(optionsStart)
    expect(messageOptionIndex).toBe(-1)
    expect(viewSource).toContain("return [{ value: null, label: t('accountWorkbench.execution.noActions'), disabled: true }]")
  })

  it('does not keep stale raw execution target/content placeholders in account workbench copy', () => {
    expect(accountWorkbenchLocaleSource).not.toContain('targetPlaceholder')
    expect(accountWorkbenchLocaleSource).not.toContain('contentPlaceholder')
    expect(accountWorkbenchLocaleSource).not.toContain('targetRequired')
    expect(accountWorkbenchLocaleSource).not.toContain('contentRequired')
  })
})
