import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const testDir = dirname(fileURLToPath(import.meta.url))
const viewPath = resolve(testDir, '../../accounts/UnifiedAccountWorkbenchView.vue')
const routeViewPath = resolve(testDir, '../../AccountWorkbenchRoute.vue')
const staleUserWorkbenchPath = resolve(testDir, '../AccountWorkbenchView.vue')
const routerPath = resolve(testDir, '../../../router/index.ts')
const sidebarPath = resolve(testDir, '../../../components/layout/AppSidebar.vue')
const zhLocalePath = resolve(testDir, '../../../i18n/locales/zh.ts')
const enLocalePath = resolve(testDir, '../../../i18n/locales/en.ts')

const routerSource = readFileSync(routerPath, 'utf8')
const sidebarSource = readFileSync(sidebarPath, 'utf8')
const routeViewSource = readFileSync(routeViewPath, 'utf8')
const accountWorkbenchLocaleSource = [
  readFileSync(zhLocalePath, 'utf8'),
  readFileSync(enLocalePath, 'utf8'),
].join('\n')

function readViewSource() {
  return readFileSync(viewPath, 'utf8')
}

function extractFunctionSource(source: string, signature: string) {
  const start = source.indexOf(signature)
  expect(start).toBeGreaterThanOrEqual(0)
  const bodyStart = source.indexOf('{', start)
  expect(bodyStart).toBeGreaterThanOrEqual(start)
  let depth = 0
  for (let index = bodyStart; index < source.length; index += 1) {
    const char = source[index]
    if (char === '{') depth += 1
    if (char === '}') {
      depth -= 1
      if (depth === 0) return source.slice(start, index + 1)
    }
  }
  throw new Error(`Unable to extract function source for ${signature}`)
}

describe('user AccountWorkbenchView source contract', () => {
  it('removes the stale user workbench implementation so /accounts has one source of truth', () => {
    expect(existsSync(staleUserWorkbenchPath)).toBe(false)
  })

  it('is reachable from the router and discoverable from the user sidebar', () => {
    expect(routerSource).toContain("path: '/accounts'")
    expect(routerSource).toContain("name: 'AccountWorkbench'")
    expect(routerSource).toContain("component: () => import('@/views/AccountWorkbenchRoute.vue')")
    expect(routerSource).toContain("titleKey: 'accountWorkbench.title'")
    expect(routerSource).toContain("path: '/admin/accounts'")
    expect(routerSource).toContain("redirect: '/accounts'")
    expect(routerSource).not.toContain("path: '/admin/accounts',\n    name: 'AdminAccounts'")
    expect(routerSource).not.toContain("path: '/social-accounts'")
    expect(sidebarSource).toContain("path: '/accounts'")
    expect(sidebarSource.indexOf("path: '/accounts'")).toBeLessThan(sidebarSource.indexOf("path: '/usage'"))
  })

  it('uses the table-first account management layout instead of the old workbench card shell', () => {
    const viewSource = readViewSource()

    expect(viewSource).toContain("import AppLayout from '@/components/layout/AppLayout.vue'")
    expect(viewSource).toContain("import TablePageLayout from '@/components/layout/TablePageLayout.vue'")
    expect(viewSource).toContain('<AppLayout')
    expect(viewSource).toContain('<TablePageLayout')
    expect(viewSource).toContain('data-testid="accounts-toolbar"')
    expect(viewSource).toContain('data-testid="accounts-batch-import-dialog"')
    expect(viewSource).not.toContain("import AccountWorkbenchShell")
    expect(viewSource).not.toContain('<AccountWorkbenchShell')
    expect(viewSource).not.toContain('<template #import>')
    expect(viewSource).not.toContain('data-testid="accounts-import-dialog"')
    expect(viewSource).not.toContain("t('accountWorkbench.billing.title')")
  })

  it('keeps /accounts on one implementation for admins and users', () => {
    expect(routeViewSource).toContain("import UnifiedAccountWorkbenchView from '@/views/accounts/UnifiedAccountWorkbenchView.vue'")
    expect(routeViewSource).toContain('<UnifiedAccountWorkbenchView')
    expect(routeViewSource).not.toContain('AdminAccountWorkbenchView')
  })

  it('keeps /accounts scoped to the current user workbench APIs', () => {
    const viewSource = readViewSource()

    expect(viewSource).toContain('accountWorkbenchAPI.listMyAccounts')
    expect(viewSource).toContain('accountWorkbenchAPI.batchImportMyAccounts')
    expect(viewSource).toContain('accountWorkbenchAPI.deleteMyAccount')
    expect(viewSource).toContain('accountWorkbenchAPI.batchDeleteMyAccounts')
    expect(viewSource).toContain('accountWorkbenchAPI.updateMyAccount')
    expect(viewSource).toContain('accountWorkbenchAPI.submitTask')
    expect(viewSource).toContain('accountWorkbenchAPI.setDefaultProxy')
    expect(viewSource).toContain('accountWorkbenchAPI.batchSetDefaultProxy')
    expect(viewSource).toContain("import proxiesAPI from '@/api/proxies'")
    expect(viewSource).toContain("import taskSettingsAPI from '@/api/taskSettings'")
    expect(viewSource).toContain('selectedAccount.value.password')
    expect(viewSource).toContain('selectedAccount.value.emailPassword')
    expect(viewSource).toContain('selectedAccount.value.authCookie')
    expect(viewSource).toContain('selectedAccount.value.executionAuth')
    expect(viewSource).toContain('selectedAccount.value.defaultProxySnapshot')
    expect(viewSource).toContain('selectedAccount.value.remark')
    expect(viewSource).toContain('account.password ??')
    expect(viewSource).toContain('account.email_password ??')
    expect(viewSource).toContain('account.auth_cookie ??')
    expect(viewSource).toContain('account.execution_auth ??')
    expect(viewSource).toContain('account.default_proxy_snapshot ??')
    expect(viewSource).toContain('account.remark ??')
    expect(viewSource).toContain("value: 'message'")
    expect(viewSource).toContain('disabled: true')
    expect(viewSource).toContain('messageUnavailable')
    expect(viewSource).not.toContain('canUseAdminTools')
    expect(viewSource).not.toContain('adminTools')
    expect(viewSource).not.toContain('adminUploadDialog')
    expect(viewSource).not.toContain('adminRegisterDialog')
    expect(viewSource).not.toContain('adminRegisterForm')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.register')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.storeWorkbenchAccounts')
    expect(viewSource).not.toContain('selectedUploadableAccounts')
    expect(viewSource).toContain("return 'invalid'")
    expect(viewSource).toContain("t(`accountWorkbench.accountStatus.${normalized}`")
    expect(viewSource).not.toContain('accountWorkbench.accountStatus.illegal')
    expect(viewSource).not.toContain('非法账号')
    expect(viewSource).not.toContain('无效账号')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.create')
    expect(viewSource).not.toContain('buildPoolAccountPayload')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.importAccounts')
    expect(viewSource).not.toContain('actionPickerValue')
    expect(viewSource).toContain('platformFilterOptions')
    expect(viewSource).toContain('openBatchImportDialog')
    expect(viewSource).toContain("import * as XLSX from 'xlsx'")
    expect(viewSource).toContain('handleBatchImportFileChange')
    expect(viewSource).toContain('batchImportFileRows')
    expect(viewSource).toContain('activeBatchImportRows')
    expect(viewSource).toContain('existingWorkbenchImportKeys')
    expect(viewSource).toContain('markExistingWorkbenchDuplicates')
    expect(viewSource).toContain("status: 'existing_workbench_duplicate' as const")
    expect(viewSource).toContain('filter(isBatchImportRowSubmittable)')
    expect(viewSource).toContain('function isBatchImportRowSubmittable')
    expect(viewSource).not.toContain("row.status === 'format_valid'")
    expect(viewSource).toContain('batchImportFileRows.value = parseBatchImportRows(fileText, importForm.platform.trim())')
    expect(viewSource).toContain('@input="clearBatchImportFileSource"')
    expect(viewSource).not.toContain('batchImportText.value = await file.text()')
    expect(viewSource).not.toContain('batchImportText.value = await importWorkbookToText(file)')
    expect(viewSource).toContain('accept=".txt,.xls,.xlsx')
    expect(viewSource).toContain('importAccountDedupKey')
    expect(viewSource).toContain("t('accountWorkbench.import.errors.duplicateAccount')")
    expect(viewSource).not.toContain('openImportDialog')
    expect(viewSource).not.toContain('importDialogOpen')
    expect(viewSource).not.toContain('importAccount(')
    const normalizeImportSource = viewSource.slice(
      viewSource.indexOf('function normalizeImportAccount'),
      viewSource.indexOf('function setImportField'),
    )
    expect(normalizeImportSource).not.toContain('default_proxy_snapshot')
    expect(viewSource).toContain("t('accountWorkbench.import.pendingCount')")
    expect(viewSource).toContain("t('accountWorkbench.import.submitReady')")
    expect(viewSource).toContain("t('accountWorkbench.import.previewMeta'")
    expect(viewSource).toContain("t('accountWorkbench.import.previewScopeUser')")
    expect(viewSource).not.toContain('pendingBackendCheckCount')
    expect(viewSource).not.toContain('localCheckReady')
    expect(viewSource).not.toContain('previewMetaAdmin')
    expect(viewSource).not.toContain('previewScopeAdmin')
    expect(viewSource).not.toContain("t('accountWorkbench.import.previewScope')")
    expect(viewSource).toContain('batchImportRowStatusLabel')
    expect(viewSource).toContain("t('accountWorkbench.import.status.batchDuplicate')")
    expect(viewSource).toContain("t('accountWorkbench.import.status.existingWorkbenchDuplicate')")
    expect(viewSource).toContain("t('accountWorkbench.import.errors.duplicateInWorkbench')")
    expect(viewSource).toContain("t('accountWorkbench.accountStatus.not_stored')")
    expect(viewSource).not.toContain('pendingBackendCheck')
    expect(viewSource).not.toContain('platformAccount')
    expect(viewSource).not.toContain('平台账号')
    expect(viewSource).not.toContain("t('accountWorkbench.import.status.formatValid')")
    expect(viewSource).not.toContain('pending_backend_check')
    expect(viewSource).not.toContain("t('accountWorkbench.import.valid')")
    expect(viewSource).not.toContain("t('accountWorkbench.import.invalid')")
    expect(viewSource).not.toContain("t('admin.socialAccountWorkbench.uploadPreview.ready')")
    expect(viewSource).not.toContain('可导入')
    expect(viewSource).not.toContain('待导入')
    expect(viewSource).toContain('batchImportResult')
    expect(viewSource).toContain('batchImportResultPreviewItems')
    expect(viewSource).toContain('remainingBatchImportResultItemCount')
    expect(viewSource).toContain("t('accountWorkbench.import.resultSummary'")
    expect(viewSource).toContain("t('accountWorkbench.import.resultTitle')")
    expect(viewSource).toContain("t('accountWorkbench.import.resultRowsMore'")
    expect(viewSource).toContain('batchImportResult.items.slice(0, 12)')
    expect(viewSource).toContain('dependencyLoadError')
    expect(viewSource).toContain("t('accountWorkbench.dependencyLoadWarning')")
    expect(viewSource).toContain('async function loadOptionalAccountDependencies()')
    expect(viewSource).toContain('Promise.allSettled')
    expect(viewSource).not.toContain('const [accountsResult, proxyResult, templateResult] = await Promise.all([')
    expect(viewSource).not.toContain('addMenu')
    expect(viewSource).not.toContain('accountWorkbenchAPI.listMy' + 'TaskLogs')
    expect(viewSource).not.toContain('source' + 'Filter')
    expect(viewSource).not.toContain('source' + 'FilterOptions')
    expect(viewSource).not.toContain('source' + 'Label')
    expect(viewSource).not.toContain('recentTask' + 'Summaries')
    expect(viewSource).not.toContain('task' + 'Logs')
    expect(viewSource).not.toContain('logs' + 'Loading')
    expect(viewSource).not.toContain('selected' + 'Log')
    expect(viewSource).not.toContain('logDetail' + 'DialogOpen')
    expect(viewSource).not.toContain('loadTaskLogs')
    expect(viewSource).not.toContain('openLogDetail')
    expect(viewSource).not.toContain('chargedTasks')
    expect(viewSource).not.toContain("t('accountWorkbench." + 'logs')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.list')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.delete')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.batchDelete')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.submitTask')
    expect(viewSource).not.toContain('adminAPI.accountWorkbench.list' + 'TaskLogs')
    expect(viewSource).not.toContain('loadAdminAccounts')
    expect(viewSource).not.toContain('assignedUser')
    expect(viewSource).not.toContain('assignDialog')
    expect(viewSource).not.toContain('reclaim')
    expect(viewSource).not.toContain('poolTabCount')
    expect(viewSource).not.toContain("to=\"/admin/total-accounts\"")
    expect(viewSource).not.toContain(' 路 ')
    expect(viewSource).not.toContain("t('admin.socialAccountWorkbench.title')")
  })

  it('lets users edit mutable credentials without editing identity fields', () => {
    const viewSource = readViewSource()
    const saveSource = extractFunctionSource(viewSource, 'async function saveAccountEdit()')

    expect(viewSource).toContain('editDialogOpen')
    expect(viewSource).toContain('openEditDialog(row)')
    expect(viewSource).toContain('data-testid="account-edit-identity"')
    expect(viewSource).toContain('data-testid="account-edit-form"')
    expect(viewSource).toContain("t('accountWorkbench.detailSections.credentials')")
    expect(viewSource).toContain("t('accountWorkbench.detailSections.operations')")
    expect(viewSource).toContain('for="account-edit-password"')
    expect(viewSource).toContain('for="account-edit-auth-cookie"')
    expect(viewSource).toContain('for="account-edit-remark"')
    expect(viewSource).toContain('editAccountForm.password')
    expect(viewSource).toContain('editAccountForm.emailPassword')
    expect(viewSource).toContain('editAccountForm.twoFactor')
    expect(viewSource).toContain('editAccountForm.authCookie')
    expect(viewSource).toContain('editAccountForm.executionAuth')
    expect(viewSource).toContain('editAccountForm.remark')
    expect(viewSource).toContain('const canSaveAccountEdit = computed(() => !!editAccount.value)')
    expect(viewSource).not.toContain("const canSaveAccountEdit = computed(() => !!editAccount.value && trimEditableField(editAccountForm.password) !== '')")
    expect(saveSource).toContain('accountWorkbenchAPI.updateMyAccount(editAccount.value.id')
    expect(saveSource).toContain('password: trimEditableField(editAccountForm.password)')
    expect(saveSource).toContain('email_password: trimEditableField(editAccountForm.emailPassword)')
    expect(saveSource).toContain('auth_cookie: trimEditableField(editAccountForm.authCookie)')
    expect(saveSource).toContain('execution_auth: trimEditableField(editAccountForm.executionAuth)')
    expect(saveSource).not.toContain('name:')
    expect(saveSource).not.toContain('platform:')
    expect(saveSource).not.toContain('platform_user_id')
    expect(saveSource).not.toContain('registration_ip')
    expect(saveSource).not.toContain('account_status')
    expect(saveSource).not.toContain('task_status')
    expect(saveSource).not.toContain('default_proxy_snapshot')
  })

  it('keeps execution submission direct and user-safe', () => {
    const viewSource = readViewSource()

    expect(viewSource).toContain('MAX_TEMPLATE_POOL_VALUES = 500')
    expect(viewSource).toContain('MAX_TEMPLATE_VALUE_LENGTH = 2048')
    expect(viewSource).toContain('selectedTemplateId')
    expect(viewSource).toContain('template_id')
    expect(viewSource).not.toContain('action: selectedTemplate.value.type')
    expect(viewSource).toContain('executionConfirmDialogOpen')
    expect(viewSource).toContain('lastTaskResult')
    expect(viewSource).toContain('taskResultPreviewLogs')
    expect(viewSource).toContain('taskResultPanelToneClass')
    expect(viewSource).toContain('taskResultRowToneClass(log)')
    expect(viewSource).toContain('hasFailedTaskNoChargeSummary')
    expect(viewSource).toContain("t('accountWorkbench.execution.failureNoChargeSummary')")
    expect(accountWorkbenchLocaleSource).toContain('failureNoChargeSummary')
    expect(viewSource).toContain('isFailedTaskResultLog')
    expect(viewSource).toContain("t('accountWorkbench.execution.resultRows')")
    expect(viewSource).toContain('accountWorkbench.execution.taskStatuses.${normalized}')
    expect(viewSource).toContain('accountWorkbench.execution.chargeStatuses.${normalized}')
    expect(accountWorkbenchLocaleSource).toContain('"charge_failed"')
    expect(viewSource).toContain('log.result_message')
    expect(viewSource).toContain('log.charged_amount')
    expect(viewSource).toContain('proxyAssignmentResult')
    expect(viewSource).toContain('proxyAssignmentResultPreviewItems')
    expect(viewSource).toContain('remainingProxyAssignmentResultItemCount')
    expect((viewSource.match(/accountWorkbench\.proxy\.resultSummary/g) || []).length).toBeGreaterThanOrEqual(2)
    expect(viewSource).toContain('proxyAssignmentResultStatusLabel')
    expect(viewSource).toContain('proxyAssignmentResultRowToneClass(item.status)')
    expect(viewSource).toContain('client_request_id')
    expect(viewSource).toContain('canStartExecution')
    expect(viewSource).toContain('hasNonExecutableSelection')
    expect(viewSource).toContain('batchImportText')
    expect(viewSource).toContain('deleteSelectedAccounts')
    expect(viewSource).toContain('loadError')
    expect(viewSource).toContain('@click="loadData"')
    expect(viewSource).toContain('extractSafeApiErrorMessage')
    expect(viewSource).toContain('recordClientDiagnostic')
    expect(viewSource).not.toContain('accountWorkbenchAPI.estimateTask')
    expect(viewSource).not.toContain('billingEstimate')
    expect(viewSource).not.toContain('canEstimateExecution')
    expect(viewSource).not.toContain('executionTarget')
    expect(viewSource).not.toContain('executionContent')
    expect(viewSource).not.toContain('targetPlaceholder')
    expect(viewSource).not.toContain('contentPlaceholder')
    expect(viewSource).not.toContain('proxyForm.proxyId')
    expect(viewSource).not.toContain('adminRegisterForm.proxyId')
    expect(viewSource).not.toContain('proxy_id: Number')
    expect(viewSource).not.toContain("t('accountWorkbench.billing")
    expect(viewSource).not.toContain('extractApiErrorMessage')
    expect(viewSource).not.toContain('console.error')
  })

  it('treats accounts without an assignable default proxy as not execution-ready', () => {
    const viewSource = readViewSource()
    const readinessSource = extractFunctionSource(viewSource, 'function isExecutableAccount(account: AccountRow)')

    expect(readinessSource).toContain('account.defaultProxyConfigured')
  })

  it('does not allow stale oversized task templates to be auto-selected for execution', () => {
    const viewSource = readViewSource()
    const templateDisabledSource = extractFunctionSource(viewSource, 'function templateDisabled(template: TaskTemplate)')
    const poolValidSource = extractFunctionSource(viewSource, 'function templatePoolValuesValid(values?: string[])')

    expect(templateDisabledSource).toContain('templatePoolValuesValid')
    expect(poolValidSource).toContain('MAX_TEMPLATE_POOL_VALUES')
    expect(poolValidSource).toContain('MAX_TEMPLATE_VALUE_LENGTH')
    expect(poolValidSource).toContain('Array.from(value).length')
    expect(viewSource).toContain('taskTemplates.value.find(template => template.is_default && !templateDisabled(template))')
  })

  it('keeps the empty task-template state visible instead of masking it with unavailable actions', () => {
    const viewSource = readViewSource()
    const optionsStart = viewSource.indexOf('const executionTemplateOptions = computed<SelectOption[]>(() => {')
    const emptyBranchIndex = viewSource.indexOf('if (taskTemplates.value.length === 0)', optionsStart)
    const messageOptionIndex = viewSource.indexOf("value: 'message'", optionsStart)

    expect(optionsStart).toBeGreaterThanOrEqual(0)
    expect(emptyBranchIndex).toBeGreaterThan(optionsStart)
    expect(messageOptionIndex).toBeGreaterThan(optionsStart)
    expect(emptyBranchIndex).toBeLessThan(messageOptionIndex)
    expect(viewSource).toContain("return [{ value: null, label: t('accountWorkbench.execution.noTemplates'), disabled: true }]")
  })

  it('does not keep stale raw execution target/content placeholders in account workbench copy', () => {
    expect(accountWorkbenchLocaleSource).not.toContain('targetPlaceholder')
    expect(accountWorkbenchLocaleSource).not.toContain('contentPlaceholder')
    expect(accountWorkbenchLocaleSource).not.toContain('targetRequired')
    expect(accountWorkbenchLocaleSource).not.toContain('contentRequired')
  })
})
