// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "ip_whitelist", Type: field.TypeJSON, Nullable: true},
		{Name: "ip_blacklist", Type: field.TypeJSON, Nullable: true},
		{Name: "quota", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "quota_used", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "rate_limit_5h", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "rate_limit_1d", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "rate_limit_7d", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "usage_5h", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "usage_1d", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "usage_7d", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "window_5h_start", Type: field.TypeTime, Nullable: true},
		{Name: "window_1d_start", Type: field.TypeTime, Nullable: true},
		{Name: "window_7d_start", Type: field.TypeTime, Nullable: true},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_groups_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[22]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[23]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_user_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[23]},
			},
			{
				Name:    "apikey_group_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[22]},
			},
			{
				Name:    "apikey_status",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[6]},
			},
			{
				Name:    "apikey_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[3]},
			},
			{
				Name:    "apikey_last_used_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[7]},
			},
			{
				Name:    "apikey_quota_quota_used",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[10], APIKeysColumns[11]},
			},
			{
				Name:    "apikey_expires_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[12]},
			},
		},
	}
	// AnnouncementsColumns holds the columns for the "announcements" table.
	AnnouncementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 200},
		{Name: "content", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "draft"},
		{Name: "notify_mode", Type: field.TypeString, Size: 20, Default: "silent"},
		{Name: "targeting", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "starts_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "ends_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// AnnouncementsTable holds the schema information for the "announcements" table.
	AnnouncementsTable = &schema.Table{
		Name:       "announcements",
		Columns:    AnnouncementsColumns,
		PrimaryKey: []*schema.Column{AnnouncementsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "announcement_status",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[3]},
			},
			{
				Name:    "announcement_created_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[10]},
			},
			{
				Name:    "announcement_starts_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[6]},
			},
			{
				Name:    "announcement_ends_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementsColumns[7]},
			},
		},
	}
	// AnnouncementReadsColumns holds the columns for the "announcement_reads" table.
	AnnouncementReadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "read_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "announcement_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// AnnouncementReadsTable holds the schema information for the "announcement_reads" table.
	AnnouncementReadsTable = &schema.Table{
		Name:       "announcement_reads",
		Columns:    AnnouncementReadsColumns,
		PrimaryKey: []*schema.Column{AnnouncementReadsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "announcement_reads_announcements_reads",
				Columns:    []*schema.Column{AnnouncementReadsColumns[3]},
				RefColumns: []*schema.Column{AnnouncementsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "announcement_reads_users_announcement_reads",
				Columns:    []*schema.Column{AnnouncementReadsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "announcementread_announcement_id",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[3]},
			},
			{
				Name:    "announcementread_user_id",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[4]},
			},
			{
				Name:    "announcementread_read_at",
				Unique:  false,
				Columns: []*schema.Column{AnnouncementReadsColumns[1]},
			},
			{
				Name:    "announcementread_announcement_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{AnnouncementReadsColumns[3], AnnouncementReadsColumns[4]},
			},
		},
	}
	// AuthIdentitiesColumns holds the columns for the "auth_identities" table.
	AuthIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "provider_type", Type: field.TypeString, Size: 20},
		{Name: "provider_key", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "provider_subject", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "verified_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "issuer", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "metadata", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// AuthIdentitiesTable holds the schema information for the "auth_identities" table.
	AuthIdentitiesTable = &schema.Table{
		Name:       "auth_identities",
		Columns:    AuthIdentitiesColumns,
		PrimaryKey: []*schema.Column{AuthIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "auth_identities_users_auth_identities",
				Columns:    []*schema.Column{AuthIdentitiesColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "authidentity_provider_type_provider_key_provider_subject",
				Unique:  true,
				Columns: []*schema.Column{AuthIdentitiesColumns[3], AuthIdentitiesColumns[4], AuthIdentitiesColumns[5]},
			},
			{
				Name:    "authidentity_user_id",
				Unique:  false,
				Columns: []*schema.Column{AuthIdentitiesColumns[9]},
			},
			{
				Name:    "authidentity_user_id_provider_type",
				Unique:  false,
				Columns: []*schema.Column{AuthIdentitiesColumns[9], AuthIdentitiesColumns[3]},
			},
		},
	}
	// AuthIdentityChannelsColumns holds the columns for the "auth_identity_channels" table.
	AuthIdentityChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "provider_type", Type: field.TypeString, Size: 20},
		{Name: "provider_key", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "channel", Type: field.TypeString, Size: 20},
		{Name: "channel_app_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "channel_subject", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "metadata", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "identity_id", Type: field.TypeInt64},
	}
	// AuthIdentityChannelsTable holds the schema information for the "auth_identity_channels" table.
	AuthIdentityChannelsTable = &schema.Table{
		Name:       "auth_identity_channels",
		Columns:    AuthIdentityChannelsColumns,
		PrimaryKey: []*schema.Column{AuthIdentityChannelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "auth_identity_channels_auth_identities_channels",
				Columns:    []*schema.Column{AuthIdentityChannelsColumns[9]},
				RefColumns: []*schema.Column{AuthIdentitiesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "authidentitychannel_provider_type_provider_key_channel_channel_app_id_channel_subject",
				Unique:  true,
				Columns: []*schema.Column{AuthIdentityChannelsColumns[3], AuthIdentityChannelsColumns[4], AuthIdentityChannelsColumns[5], AuthIdentityChannelsColumns[6], AuthIdentityChannelsColumns[7]},
			},
			{
				Name:    "authidentitychannel_identity_id",
				Unique:  false,
				Columns: []*schema.Column{AuthIdentityChannelsColumns[9]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "is_exclusive", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "platform", Type: field.TypeString, Size: 50, Default: "social"},
		{Name: "subscription_type", Type: field.TypeString, Size: 20, Default: "subscription"},
		{Name: "daily_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "weekly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "monthly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "default_validity_days", Type: field.TypeInt, Default: 30},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "rpm_limit", Type: field.TypeInt, Default: 0},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "group_status",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[8]},
			},
			{
				Name:    "group_platform",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[9]},
			},
			{
				Name:    "group_subscription_type",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[10]},
			},
			{
				Name:    "group_is_exclusive",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[7]},
			},
			{
				Name:    "group_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[3]},
			},
			{
				Name:    "group_sort_order",
				Unique:  false,
				Columns: []*schema.Column{GroupsColumns[15]},
			},
		},
	}
	// IdentityAdoptionDecisionsColumns holds the columns for the "identity_adoption_decisions" table.
	IdentityAdoptionDecisionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "adopt_display_name", Type: field.TypeBool, Default: false},
		{Name: "adopt_avatar", Type: field.TypeBool, Default: false},
		{Name: "decided_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "identity_id", Type: field.TypeInt64, Nullable: true},
		{Name: "pending_auth_session_id", Type: field.TypeInt64, Unique: true},
	}
	// IdentityAdoptionDecisionsTable holds the schema information for the "identity_adoption_decisions" table.
	IdentityAdoptionDecisionsTable = &schema.Table{
		Name:       "identity_adoption_decisions",
		Columns:    IdentityAdoptionDecisionsColumns,
		PrimaryKey: []*schema.Column{IdentityAdoptionDecisionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "identity_adoption_decisions_auth_identities_adoption_decisions",
				Columns:    []*schema.Column{IdentityAdoptionDecisionsColumns[6]},
				RefColumns: []*schema.Column{AuthIdentitiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "identity_adoption_decisions_pending_auth_sessions_adoption_decision",
				Columns:    []*schema.Column{IdentityAdoptionDecisionsColumns[7]},
				RefColumns: []*schema.Column{PendingAuthSessionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "identityadoptiondecision_pending_auth_session_id",
				Unique:  true,
				Columns: []*schema.Column{IdentityAdoptionDecisionsColumns[7]},
			},
			{
				Name:    "identityadoptiondecision_identity_id",
				Unique:  false,
				Columns: []*schema.Column{IdentityAdoptionDecisionsColumns[6]},
			},
		},
	}
	// PaymentAuditLogsColumns holds the columns for the "payment_audit_logs" table.
	PaymentAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "order_id", Type: field.TypeString, Size: 64},
		{Name: "action", Type: field.TypeString, Size: 50},
		{Name: "detail", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "operator", Type: field.TypeString, Size: 100, Default: "system"},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// PaymentAuditLogsTable holds the schema information for the "payment_audit_logs" table.
	PaymentAuditLogsTable = &schema.Table{
		Name:       "payment_audit_logs",
		Columns:    PaymentAuditLogsColumns,
		PrimaryKey: []*schema.Column{PaymentAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentauditlog_order_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentAuditLogsColumns[1]},
			},
			{
				Name:    "paymentauditlog_order_id_action",
				Unique:  true,
				Columns: []*schema.Column{PaymentAuditLogsColumns[1], PaymentAuditLogsColumns[2]},
			},
		},
	}
	// PaymentOrdersColumns holds the columns for the "payment_orders" table.
	PaymentOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_email", Type: field.TypeString, Size: 255},
		{Name: "user_name", Type: field.TypeString, Size: 100},
		{Name: "user_notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "pay_amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "fee_rate", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "recharge_code", Type: field.TypeString, Size: 64},
		{Name: "out_trade_no", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "payment_type", Type: field.TypeString, Size: 30},
		{Name: "payment_trade_no", Type: field.TypeString, Size: 128},
		{Name: "pay_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "qr_code", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "qr_code_img", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "order_type", Type: field.TypeString, Size: 20, Default: "balance"},
		{Name: "plan_id", Type: field.TypeInt64, Nullable: true},
		{Name: "subscription_group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "subscription_days", Type: field.TypeInt, Nullable: true},
		{Name: "provider_instance_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "provider_key", Type: field.TypeString, Nullable: true, Size: 30},
		{Name: "provider_snapshot", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "status", Type: field.TypeString, Size: 30, Default: "PENDING"},
		{Name: "refund_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "refund_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "force_refund", Type: field.TypeBool, Default: false},
		{Name: "refund_requested_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "refund_request_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_requested_by", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "failed_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "failed_reason", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "client_ip", Type: field.TypeString, Size: 50},
		{Name: "src_host", Type: field.TypeString, Size: 255},
		{Name: "src_url", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// PaymentOrdersTable holds the schema information for the "payment_orders" table.
	PaymentOrdersTable = &schema.Table{
		Name:       "payment_orders",
		Columns:    PaymentOrdersColumns,
		PrimaryKey: []*schema.Column{PaymentOrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payment_orders_users_payment_orders",
				Columns:    []*schema.Column{PaymentOrdersColumns[39]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "paymentorder_out_trade_no",
				Unique:  true,
				Columns: []*schema.Column{PaymentOrdersColumns[8]},
				Annotation: &entsql.IndexAnnotation{
					Where: "out_trade_no <> ''",
				},
			},
			{
				Name:    "paymentorder_user_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[39]},
			},
			{
				Name:    "paymentorder_status",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[21]},
			},
			{
				Name:    "paymentorder_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[29]},
			},
			{
				Name:    "paymentorder_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[37]},
			},
			{
				Name:    "paymentorder_paid_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[30]},
			},
			{
				Name:    "paymentorder_payment_type_paid_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[9], PaymentOrdersColumns[30]},
			},
			{
				Name:    "paymentorder_order_type",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[14]},
			},
		},
	}
	// PaymentProviderInstancesColumns holds the columns for the "payment_provider_instances" table.
	PaymentProviderInstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "provider_key", Type: field.TypeString, Size: 30},
		{Name: "name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "config", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "supported_types", Type: field.TypeString, Size: 200, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "payment_mode", Type: field.TypeString, Size: 20, Default: ""},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "limits", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "refund_enabled", Type: field.TypeBool, Default: false},
		{Name: "allow_user_refund", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// PaymentProviderInstancesTable holds the schema information for the "payment_provider_instances" table.
	PaymentProviderInstancesTable = &schema.Table{
		Name:       "payment_provider_instances",
		Columns:    PaymentProviderInstancesColumns,
		PrimaryKey: []*schema.Column{PaymentProviderInstancesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentproviderinstance_provider_key",
				Unique:  false,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[1]},
			},
			{
				Name:    "paymentproviderinstance_enabled",
				Unique:  false,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[5]},
			},
		},
	}
	// PendingAuthSessionsColumns holds the columns for the "pending_auth_sessions" table.
	PendingAuthSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "session_token", Type: field.TypeString, Size: 255},
		{Name: "intent", Type: field.TypeString, Size: 40},
		{Name: "provider_type", Type: field.TypeString, Size: 20},
		{Name: "provider_key", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "provider_subject", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "redirect_to", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "resolved_email", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "registration_password_hash", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "upstream_identity_claims", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "local_flow_state", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "browser_session_key", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "completion_code_hash", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "completion_code_expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "email_verified_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "password_verified_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "totp_verified_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "consumed_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "target_user_id", Type: field.TypeInt64, Nullable: true},
	}
	// PendingAuthSessionsTable holds the schema information for the "pending_auth_sessions" table.
	PendingAuthSessionsTable = &schema.Table{
		Name:       "pending_auth_sessions",
		Columns:    PendingAuthSessionsColumns,
		PrimaryKey: []*schema.Column{PendingAuthSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "pending_auth_sessions_users_pending_auth_sessions",
				Columns:    []*schema.Column{PendingAuthSessionsColumns[21]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pendingauthsession_session_token",
				Unique:  true,
				Columns: []*schema.Column{PendingAuthSessionsColumns[3]},
			},
			{
				Name:    "pendingauthsession_target_user_id",
				Unique:  false,
				Columns: []*schema.Column{PendingAuthSessionsColumns[21]},
			},
			{
				Name:    "pendingauthsession_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PendingAuthSessionsColumns[19]},
			},
			{
				Name:    "pendingauthsession_provider_type_provider_key_provider_subject",
				Unique:  false,
				Columns: []*schema.Column{PendingAuthSessionsColumns[5], PendingAuthSessionsColumns[6], PendingAuthSessionsColumns[7]},
			},
			{
				Name:    "pendingauthsession_completion_code_hash",
				Unique:  false,
				Columns: []*schema.Column{PendingAuthSessionsColumns[14]},
			},
		},
	}
	// PromoCodesColumns holds the columns for the "promo_codes" table.
	PromoCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "bonus_amount", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "max_uses", Type: field.TypeInt, Default: 0},
		{Name: "used_count", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// PromoCodesTable holds the schema information for the "promo_codes" table.
	PromoCodesTable = &schema.Table{
		Name:       "promo_codes",
		Columns:    PromoCodesColumns,
		PrimaryKey: []*schema.Column{PromoCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "promocode_status",
				Unique:  false,
				Columns: []*schema.Column{PromoCodesColumns[5]},
			},
			{
				Name:    "promocode_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PromoCodesColumns[6]},
			},
		},
	}
	// PromoCodeUsagesColumns holds the columns for the "promo_code_usages" table.
	PromoCodeUsagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "bonus_amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "used_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "promo_code_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// PromoCodeUsagesTable holds the schema information for the "promo_code_usages" table.
	PromoCodeUsagesTable = &schema.Table{
		Name:       "promo_code_usages",
		Columns:    PromoCodeUsagesColumns,
		PrimaryKey: []*schema.Column{PromoCodeUsagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "promo_code_usages_promo_codes_usage_records",
				Columns:    []*schema.Column{PromoCodeUsagesColumns[3]},
				RefColumns: []*schema.Column{PromoCodesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "promo_code_usages_users_promo_code_usages",
				Columns:    []*schema.Column{PromoCodeUsagesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "promocodeusage_promo_code_id",
				Unique:  false,
				Columns: []*schema.Column{PromoCodeUsagesColumns[3]},
			},
			{
				Name:    "promocodeusage_user_id",
				Unique:  false,
				Columns: []*schema.Column{PromoCodeUsagesColumns[4]},
			},
			{
				Name:    "promocodeusage_promo_code_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{PromoCodeUsagesColumns[3], PromoCodeUsagesColumns[4]},
			},
		},
	}
	// RedeemCodesColumns holds the columns for the "redeem_codes" table.
	RedeemCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "type", Type: field.TypeString, Size: 20, Default: "balance"},
		{Name: "value", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "unused"},
		{Name: "used_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "plan_id", Type: field.TypeInt64, Nullable: true},
		{Name: "validity_days", Type: field.TypeInt, Default: 30},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "used_by", Type: field.TypeInt64, Nullable: true},
	}
	// RedeemCodesTable holds the schema information for the "redeem_codes" table.
	RedeemCodesTable = &schema.Table{
		Name:       "redeem_codes",
		Columns:    RedeemCodesColumns,
		PrimaryKey: []*schema.Column{RedeemCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "redeem_codes_groups_redeem_codes",
				Columns:    []*schema.Column{RedeemCodesColumns[11]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "redeem_codes_users_redeem_codes",
				Columns:    []*schema.Column{RedeemCodesColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "redeemcode_status",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[4]},
			},
			{
				Name:    "redeemcode_used_by",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[12]},
			},
			{
				Name:    "redeemcode_group_id",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[11]},
			},
			{
				Name:    "redeemcode_plan_id",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[9]},
			},
			{
				Name:    "redeemcode_expires_at",
				Unique:  false,
				Columns: []*schema.Column{RedeemCodesColumns[8]},
			},
		},
	}
	// SecuritySecretsColumns holds the columns for the "security_secrets" table.
	SecuritySecretsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
	}
	// SecuritySecretsTable holds the schema information for the "security_secrets" table.
	SecuritySecretsTable = &schema.Table{
		Name:       "security_secrets",
		Columns:    SecuritySecretsColumns,
		PrimaryKey: []*schema.Column{SecuritySecretsColumns[0]},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "value", Type: field.TypeString, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// SocialAccountsColumns holds the columns for the "social_accounts" table.
	SocialAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "platform", Type: field.TypeString, Size: 50},
		{Name: "platform_key", Type: field.TypeString, Size: 50},
		{Name: "name_key", Type: field.TypeString, Size: 100},
		{Name: "identity_kind", Type: field.TypeString, Size: 30, Default: "username"},
		{Name: "identity_key", Type: field.TypeString, Size: 100},
		{Name: "platform_user_id", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "password", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "phone", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "email", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "email_password", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "two_factor", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "backup_code", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "email_client_id", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "email_token", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "registration_ip", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "auth_cookie", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "execution_auth", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "account_status", Type: field.TypeString, Size: 30, Default: "pending_check"},
		{Name: "task_status", Type: field.TypeString, Size: 30, Default: "pending"},
		{Name: "task_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "default_proxy_snapshot", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "user_workbench_deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "assigned_user_id", Type: field.TypeInt64, Nullable: true},
	}
	// SocialAccountsTable holds the schema information for the "social_accounts" table.
	SocialAccountsTable = &schema.Table{
		Name:       "social_accounts",
		Columns:    SocialAccountsColumns,
		PrimaryKey: []*schema.Column{SocialAccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "social_accounts_users_social_accounts",
				Columns:    []*schema.Column{SocialAccountsColumns[28]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "socialaccount_platform",
				Unique:  false,
				Columns: []*schema.Column{SocialAccountsColumns[5]},
			},
			{
				Name:    "socialaccount_account_status",
				Unique:  false,
				Columns: []*schema.Column{SocialAccountsColumns[22]},
			},
			{
				Name:    "socialaccount_task_status",
				Unique:  false,
				Columns: []*schema.Column{SocialAccountsColumns[23]},
			},
			{
				Name:    "socialaccount_assigned_user_id",
				Unique:  false,
				Columns: []*schema.Column{SocialAccountsColumns[28]},
			},
			{
				Name:    "socialaccount_assigned_user_id_user_workbench_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SocialAccountsColumns[28], SocialAccountsColumns[26]},
			},
			{
				Name:    "socialaccount_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SocialAccountsColumns[3]},
			},
			{
				Name:    "socialaccount_platform_account_status",
				Unique:  false,
				Columns: []*schema.Column{SocialAccountsColumns[5], SocialAccountsColumns[22]},
			},
			{
				Name:    "socialaccount_platform_user_id",
				Unique:  false,
				Columns: []*schema.Column{SocialAccountsColumns[10]},
			},
			{
				Name:    "socialaccount_platform_key_identity_kind_identity_key",
				Unique:  true,
				Columns: []*schema.Column{SocialAccountsColumns[6], SocialAccountsColumns[8], SocialAccountsColumns[9]},
				Annotation: &entsql.IndexAnnotation{
					Where: "deleted_at IS NULL",
				},
			},
		},
	}
	// SocialIpsColumns holds the columns for the "social_ips" table.
	SocialIpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "ip_type", Type: field.TypeString, Size: 30, Default: "residential"},
		{Name: "endpoint", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "unknown"},
		{Name: "latency_ms", Type: field.TypeInt, Nullable: true},
		{Name: "last_check_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "bound_social_account_id", Type: field.TypeInt64, Nullable: true},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// SocialIpsTable holds the schema information for the "social_ips" table.
	SocialIpsTable = &schema.Table{
		Name:       "social_ips",
		Columns:    SocialIpsColumns,
		PrimaryKey: []*schema.Column{SocialIpsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "social_ips_users_social_ips",
				Columns:    []*schema.Column{SocialIpsColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "socialip_user_id",
				Unique:  false,
				Columns: []*schema.Column{SocialIpsColumns[12]},
			},
			{
				Name:    "socialip_status",
				Unique:  false,
				Columns: []*schema.Column{SocialIpsColumns[7]},
			},
			{
				Name:    "socialip_ip_type",
				Unique:  false,
				Columns: []*schema.Column{SocialIpsColumns[5]},
			},
			{
				Name:    "socialip_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{SocialIpsColumns[3]},
			},
			{
				Name:    "socialip_user_id_status",
				Unique:  false,
				Columns: []*schema.Column{SocialIpsColumns[12], SocialIpsColumns[7]},
			},
		},
	}
	// SocialTaskLogsColumns holds the columns for the "social_task_logs" table.
	SocialTaskLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "action", Type: field.TypeString, Size: 50},
		{Name: "target", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "pending"},
		{Name: "result_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "price", Type: field.TypeFloat64, Default: 0.1},
		{Name: "charged_amount", Type: field.TypeFloat64, Default: 0},
		{Name: "charge_status", Type: field.TypeString, Size: 30, Default: "not_charged"},
		{Name: "charge_source", Type: field.TypeString, Nullable: true, Size: 30},
		{Name: "proxy_id", Type: field.TypeInt64, Nullable: true},
		{Name: "proxy_snapshot", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "billing_request_id", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "idempotency_key", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "executed_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "social_account_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// SocialTaskLogsTable holds the schema information for the "social_task_logs" table.
	SocialTaskLogsTable = &schema.Table{
		Name:       "social_task_logs",
		Columns:    SocialTaskLogsColumns,
		PrimaryKey: []*schema.Column{SocialTaskLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "social_task_logs_social_accounts_task_logs",
				Columns:    []*schema.Column{SocialTaskLogsColumns[17]},
				RefColumns: []*schema.Column{SocialAccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "social_task_logs_users_social_task_logs",
				Columns:    []*schema.Column{SocialTaskLogsColumns[18]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "socialtasklog_social_account_id",
				Unique:  false,
				Columns: []*schema.Column{SocialTaskLogsColumns[17]},
			},
			{
				Name:    "socialtasklog_user_id",
				Unique:  false,
				Columns: []*schema.Column{SocialTaskLogsColumns[18]},
			},
			{
				Name:    "socialtasklog_action",
				Unique:  false,
				Columns: []*schema.Column{SocialTaskLogsColumns[3]},
			},
			{
				Name:    "socialtasklog_status",
				Unique:  false,
				Columns: []*schema.Column{SocialTaskLogsColumns[6]},
			},
			{
				Name:    "socialtasklog_user_id_action",
				Unique:  false,
				Columns: []*schema.Column{SocialTaskLogsColumns[18], SocialTaskLogsColumns[3]},
			},
			{
				Name:    "socialtasklog_social_account_id_status",
				Unique:  false,
				Columns: []*schema.Column{SocialTaskLogsColumns[17], SocialTaskLogsColumns[6]},
			},
			{
				Name:    "socialtasklog_user_id_social_account_id_action_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{SocialTaskLogsColumns[18], SocialTaskLogsColumns[17], SocialTaskLogsColumns[3], SocialTaskLogsColumns[15]},
				Annotation: &entsql.IndexAnnotation{
					Where: "idempotency_key IS NOT NULL",
				},
			},
			{
				Name:    "socialtasklog_charge_status",
				Unique:  false,
				Columns: []*schema.Column{SocialTaskLogsColumns[10]},
			},
			{
				Name:    "socialtasklog_proxy_id",
				Unique:  false,
				Columns: []*schema.Column{SocialTaskLogsColumns[12]},
			},
		},
	}
	// SubscriptionPlansColumns holds the columns for the "subscription_plans" table.
	SubscriptionPlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "group_id", Type: field.TypeInt64},
		{Name: "platform", Type: field.TypeString, Size: 50, Default: "social"},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "original_price", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,2)"}},
		{Name: "validity_days", Type: field.TypeInt, Default: 30},
		{Name: "validity_unit", Type: field.TypeString, Size: 10, Default: "day"},
		{Name: "features", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "product_name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "for_sale", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "daily_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "weekly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "monthly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// SubscriptionPlansTable holds the schema information for the "subscription_plans" table.
	SubscriptionPlansTable = &schema.Table{
		Name:       "subscription_plans",
		Columns:    SubscriptionPlansColumns,
		PrimaryKey: []*schema.Column{SubscriptionPlansColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "subscriptionplan_group_id",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlansColumns[1]},
			},
			{
				Name:    "subscriptionplan_platform",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlansColumns[2]},
			},
			{
				Name:    "subscriptionplan_for_sale",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlansColumns[11]},
			},
		},
	}
	// UsageCleanupTasksColumns holds the columns for the "usage_cleanup_tasks" table.
	UsageCleanupTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "status", Type: field.TypeString, Size: 20},
		{Name: "filters", Type: field.TypeJSON},
		{Name: "created_by", Type: field.TypeInt64},
		{Name: "deleted_rows", Type: field.TypeInt64, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "canceled_by", Type: field.TypeInt64, Nullable: true},
		{Name: "canceled_at", Type: field.TypeTime, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// UsageCleanupTasksTable holds the schema information for the "usage_cleanup_tasks" table.
	UsageCleanupTasksTable = &schema.Table{
		Name:       "usage_cleanup_tasks",
		Columns:    UsageCleanupTasksColumns,
		PrimaryKey: []*schema.Column{UsageCleanupTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "usagecleanuptask_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageCleanupTasksColumns[3], UsageCleanupTasksColumns[1]},
			},
			{
				Name:    "usagecleanuptask_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageCleanupTasksColumns[1]},
			},
			{
				Name:    "usagecleanuptask_canceled_at",
				Unique:  false,
				Columns: []*schema.Column{UsageCleanupTasksColumns[9]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "account_id", Type: field.TypeInt64, Nullable: true},
		{Name: "request_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "model", Type: field.TypeString, Size: 100, Default: "social-action"},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_read_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_5m_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_creation_1h_tokens", Type: field.TypeInt, Default: 0},
		{Name: "input_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "output_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "cache_creation_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "cache_read_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "total_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "actual_cost", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "rate_multiplier", Type: field.TypeFloat64, Default: 1, SchemaType: map[string]string{"postgres": "decimal(10,4)"}},
		{Name: "billing_type", Type: field.TypeInt8, Default: 0},
		{Name: "stream", Type: field.TypeBool, Default: false},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "first_token_ms", Type: field.TypeInt, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "ip_address", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "api_key_id", Type: field.TypeInt64, Nullable: true},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "subscription_id", Type: field.TypeInt64, Nullable: true},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "usage_logs_api_keys_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[24]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_groups_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[25]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "usage_logs_users_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[26]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "usage_logs_user_subscriptions_usage_logs",
				Columns:    []*schema.Column{UsageLogsColumns[27]},
				RefColumns: []*schema.Column{UserSubscriptionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usagelog_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[26]},
			},
			{
				Name:    "usagelog_api_key_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[24]},
			},
			{
				Name:    "usagelog_account_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[1]},
			},
			{
				Name:    "usagelog_group_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[25]},
			},
			{
				Name:    "usagelog_subscription_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[27]},
			},
			{
				Name:    "usagelog_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[23]},
			},
			{
				Name:    "usagelog_model",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[3]},
			},
			{
				Name:    "usagelog_request_id",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[2]},
			},
			{
				Name:    "usagelog_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[26], UsageLogsColumns[23]},
			},
			{
				Name:    "usagelog_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[24], UsageLogsColumns[23]},
			},
			{
				Name:    "usagelog_group_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[25], UsageLogsColumns[23]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "password_hash", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "user"},
		{Name: "balance", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "concurrency", Type: field.TypeInt, Default: 5},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "token_version", Type: field.TypeInt64, Default: 0},
		{Name: "username", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "notes", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "totp_secret_encrypted", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "totp_enabled", Type: field.TypeBool, Default: false},
		{Name: "totp_enabled_at", Type: field.TypeTime, Nullable: true},
		{Name: "signup_source", Type: field.TypeString, Default: "email"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "last_active_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "balance_notify_enabled", Type: field.TypeBool, Default: true},
		{Name: "balance_notify_threshold_type", Type: field.TypeString, Default: "fixed"},
		{Name: "balance_notify_threshold", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "balance_notify_extra_emails", Type: field.TypeString, Default: "[]", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "total_recharged", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "rpm_limit", Type: field.TypeInt, Default: 0},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[9]},
			},
			{
				Name:    "user_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
		},
	}
	// UserAllowedGroupsColumns holds the columns for the "user_allowed_groups" table.
	UserAllowedGroupsColumns = []*schema.Column{
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64},
	}
	// UserAllowedGroupsTable holds the schema information for the "user_allowed_groups" table.
	UserAllowedGroupsTable = &schema.Table{
		Name:       "user_allowed_groups",
		Columns:    UserAllowedGroupsColumns,
		PrimaryKey: []*schema.Column{UserAllowedGroupsColumns[1], UserAllowedGroupsColumns[2]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_allowed_groups_users_user",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_allowed_groups_groups_group",
				Columns:    []*schema.Column{UserAllowedGroupsColumns[2]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userallowedgroup_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserAllowedGroupsColumns[2]},
			},
		},
	}
	// UserAttributeDefinitionsColumns holds the columns for the "user_attribute_definitions" table.
	UserAttributeDefinitionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "key", Type: field.TypeString, Size: 100},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Default: "", SchemaType: map[string]string{"postgres": "text"}},
		{Name: "type", Type: field.TypeString, Size: 20},
		{Name: "options", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "required", Type: field.TypeBool, Default: false},
		{Name: "validation", Type: field.TypeJSON, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "placeholder", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "display_order", Type: field.TypeInt, Default: 0},
		{Name: "enabled", Type: field.TypeBool, Default: true},
	}
	// UserAttributeDefinitionsTable holds the schema information for the "user_attribute_definitions" table.
	UserAttributeDefinitionsTable = &schema.Table{
		Name:       "user_attribute_definitions",
		Columns:    UserAttributeDefinitionsColumns,
		PrimaryKey: []*schema.Column{UserAttributeDefinitionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userattributedefinition_key",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[4]},
			},
			{
				Name:    "userattributedefinition_enabled",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[13]},
			},
			{
				Name:    "userattributedefinition_display_order",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[12]},
			},
			{
				Name:    "userattributedefinition_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeDefinitionsColumns[3]},
			},
		},
	}
	// UserAttributeValuesColumns holds the columns for the "user_attribute_values" table.
	UserAttributeValuesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "value", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "attribute_id", Type: field.TypeInt64},
	}
	// UserAttributeValuesTable holds the schema information for the "user_attribute_values" table.
	UserAttributeValuesTable = &schema.Table{
		Name:       "user_attribute_values",
		Columns:    UserAttributeValuesColumns,
		PrimaryKey: []*schema.Column{UserAttributeValuesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_attribute_values_users_attribute_values",
				Columns:    []*schema.Column{UserAttributeValuesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_attribute_values_user_attribute_definitions_values",
				Columns:    []*schema.Column{UserAttributeValuesColumns[5]},
				RefColumns: []*schema.Column{UserAttributeDefinitionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userattributevalue_user_id_attribute_id",
				Unique:  true,
				Columns: []*schema.Column{UserAttributeValuesColumns[4], UserAttributeValuesColumns[5]},
			},
			{
				Name:    "userattributevalue_attribute_id",
				Unique:  false,
				Columns: []*schema.Column{UserAttributeValuesColumns[5]},
			},
		},
	}
	// UserSubscriptionsColumns holds the columns for the "user_subscriptions" table.
	UserSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "plan_id", Type: field.TypeInt64, Nullable: true},
		{Name: "plan_name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "plan_platform", Type: field.TypeString, Size: 50, Default: ""},
		{Name: "daily_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "weekly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "monthly_limit_usd", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "decimal(20,8)"}},
		{Name: "starts_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expires_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "status", Type: field.TypeString, Size: 20, Default: "active"},
		{Name: "daily_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "weekly_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "monthly_window_start", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "daily_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "weekly_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "monthly_usage_usd", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(20,10)"}},
		{Name: "assigned_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "notes", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "text"}},
		{Name: "group_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "assigned_by", Type: field.TypeInt64, Nullable: true},
	}
	// UserSubscriptionsTable holds the schema information for the "user_subscriptions" table.
	UserSubscriptionsTable = &schema.Table{
		Name:       "user_subscriptions",
		Columns:    UserSubscriptionsColumns,
		PrimaryKey: []*schema.Column{UserSubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_subscriptions_groups_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[21]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_subscriptions_users_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[22]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_subscriptions_users_assigned_subscriptions",
				Columns:    []*schema.Column{UserSubscriptionsColumns[23]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usersubscription_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[22]},
			},
			{
				Name:    "usersubscription_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[21]},
			},
			{
				Name:    "usersubscription_plan_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[4]},
			},
			{
				Name:    "usersubscription_status",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[12]},
			},
			{
				Name:    "usersubscription_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[11]},
			},
			{
				Name:    "usersubscription_user_id_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[22], UserSubscriptionsColumns[12], UserSubscriptionsColumns[11]},
			},
			{
				Name:    "usersubscription_assigned_by",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[23]},
			},
			{
				Name:    "usersubscription_user_id_group_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[22], UserSubscriptionsColumns[21]},
			},
			{
				Name:    "usersubscription_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		AnnouncementsTable,
		AnnouncementReadsTable,
		AuthIdentitiesTable,
		AuthIdentityChannelsTable,
		GroupsTable,
		IdentityAdoptionDecisionsTable,
		PaymentAuditLogsTable,
		PaymentOrdersTable,
		PaymentProviderInstancesTable,
		PendingAuthSessionsTable,
		PromoCodesTable,
		PromoCodeUsagesTable,
		RedeemCodesTable,
		SecuritySecretsTable,
		SettingsTable,
		SocialAccountsTable,
		SocialIpsTable,
		SocialTaskLogsTable,
		SubscriptionPlansTable,
		UsageCleanupTasksTable,
		UsageLogsTable,
		UsersTable,
		UserAllowedGroupsTable,
		UserAttributeDefinitionsTable,
		UserAttributeValuesTable,
		UserSubscriptionsTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = GroupsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	APIKeysTable.Annotation = &entsql.Annotation{
		Table: "api_keys",
	}
	AnnouncementsTable.Annotation = &entsql.Annotation{
		Table: "announcements",
	}
	AnnouncementReadsTable.ForeignKeys[0].RefTable = AnnouncementsTable
	AnnouncementReadsTable.ForeignKeys[1].RefTable = UsersTable
	AnnouncementReadsTable.Annotation = &entsql.Annotation{
		Table: "announcement_reads",
	}
	AuthIdentitiesTable.ForeignKeys[0].RefTable = UsersTable
	AuthIdentitiesTable.Annotation = &entsql.Annotation{
		Table: "auth_identities",
	}
	AuthIdentityChannelsTable.ForeignKeys[0].RefTable = AuthIdentitiesTable
	AuthIdentityChannelsTable.Annotation = &entsql.Annotation{
		Table: "auth_identity_channels",
	}
	GroupsTable.Annotation = &entsql.Annotation{
		Table: "groups",
	}
	IdentityAdoptionDecisionsTable.ForeignKeys[0].RefTable = AuthIdentitiesTable
	IdentityAdoptionDecisionsTable.ForeignKeys[1].RefTable = PendingAuthSessionsTable
	IdentityAdoptionDecisionsTable.Annotation = &entsql.Annotation{
		Table: "identity_adoption_decisions",
	}
	PaymentAuditLogsTable.Annotation = &entsql.Annotation{
		Table: "payment_audit_logs",
	}
	PaymentOrdersTable.ForeignKeys[0].RefTable = UsersTable
	PaymentOrdersTable.Annotation = &entsql.Annotation{
		Table: "payment_orders",
	}
	PaymentProviderInstancesTable.Annotation = &entsql.Annotation{
		Table: "payment_provider_instances",
	}
	PendingAuthSessionsTable.ForeignKeys[0].RefTable = UsersTable
	PendingAuthSessionsTable.Annotation = &entsql.Annotation{
		Table: "pending_auth_sessions",
	}
	PromoCodesTable.Annotation = &entsql.Annotation{
		Table: "promo_codes",
	}
	PromoCodeUsagesTable.ForeignKeys[0].RefTable = PromoCodesTable
	PromoCodeUsagesTable.ForeignKeys[1].RefTable = UsersTable
	PromoCodeUsagesTable.Annotation = &entsql.Annotation{
		Table: "promo_code_usages",
	}
	RedeemCodesTable.ForeignKeys[0].RefTable = GroupsTable
	RedeemCodesTable.ForeignKeys[1].RefTable = UsersTable
	RedeemCodesTable.Annotation = &entsql.Annotation{
		Table: "redeem_codes",
	}
	SecuritySecretsTable.Annotation = &entsql.Annotation{
		Table: "security_secrets",
	}
	SettingsTable.Annotation = &entsql.Annotation{
		Table: "settings",
	}
	SocialAccountsTable.ForeignKeys[0].RefTable = UsersTable
	SocialAccountsTable.Annotation = &entsql.Annotation{
		Table: "social_accounts",
	}
	SocialIpsTable.ForeignKeys[0].RefTable = UsersTable
	SocialIpsTable.Annotation = &entsql.Annotation{
		Table: "social_ips",
	}
	SocialTaskLogsTable.ForeignKeys[0].RefTable = SocialAccountsTable
	SocialTaskLogsTable.ForeignKeys[1].RefTable = UsersTable
	SocialTaskLogsTable.Annotation = &entsql.Annotation{
		Table: "social_task_logs",
	}
	SubscriptionPlansTable.Annotation = &entsql.Annotation{
		Table: "subscription_plans",
	}
	UsageCleanupTasksTable.Annotation = &entsql.Annotation{
		Table: "usage_cleanup_tasks",
	}
	UsageLogsTable.ForeignKeys[0].RefTable = APIKeysTable
	UsageLogsTable.ForeignKeys[1].RefTable = GroupsTable
	UsageLogsTable.ForeignKeys[2].RefTable = UsersTable
	UsageLogsTable.ForeignKeys[3].RefTable = UserSubscriptionsTable
	UsageLogsTable.Annotation = &entsql.Annotation{
		Table: "usage_logs",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	UserAllowedGroupsTable.ForeignKeys[0].RefTable = UsersTable
	UserAllowedGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	UserAllowedGroupsTable.Annotation = &entsql.Annotation{
		Table: "user_allowed_groups",
	}
	UserAttributeDefinitionsTable.Annotation = &entsql.Annotation{
		Table: "user_attribute_definitions",
	}
	UserAttributeValuesTable.ForeignKeys[0].RefTable = UsersTable
	UserAttributeValuesTable.ForeignKeys[1].RefTable = UserAttributeDefinitionsTable
	UserAttributeValuesTable.Annotation = &entsql.Annotation{
		Table: "user_attribute_values",
	}
	UserSubscriptionsTable.ForeignKeys[0].RefTable = GroupsTable
	UserSubscriptionsTable.ForeignKeys[1].RefTable = UsersTable
	UserSubscriptionsTable.ForeignKeys[2].RefTable = UsersTable
	UserSubscriptionsTable.Annotation = &entsql.Annotation{
		Table: "user_subscriptions",
	}
}
